### ISSUE TITLE
Annotation file Import Feature?

### ISSUE THREAD

**Issue by nikkisingh111333** [deepjavalibrary/djl#1007]
hey ....i have an dataset that has Dogs image of 120 breed as classes each folder contaions 150 to 200 images of that particular dog...like german shephard folder has 130 images rodweiler has 130 images etc...i also have annotation files associated with these images...each image has its own annotation file that has bounding boxes..
Annotation file structure is like :
`DOGS_ANNOTATION > GERMAN SHEPHARD > DOG_1_Anno.file`
2nd image like:
`DOGS_ANNOTATION > GERMAN SHEPHARD > DOG_2_Anno.file` and so on ..same structure for other dogs image 

Now come to my problem:
i m following pikachudetection where its using index.file(i dont know where to find it) as annotation file..but my dataset is huge and contains annotation.file for each image...how can i use it to train my ssd detector..i cant find any example clear road in DJL..python has easy structure but ...In java lots of classes in the docs..please Guide me...

**Comment by zachgk** [comment]
Don't worry about the index.file as it doesn't seem to fit your data. I recommend just creating custom parsing of the annotation files in their format.

What you will need to do is:

- Create a dataset class extending `ObjectDetectionDataset`
- Have the dataset read all image annotation files and save them to an instance variable
- Implement the abstract functions using those instance variables

**Comment by nikkisingh111333** [comment]
Can you give me an simple example about all this ...It will be a good starting point for me..?

**Comment by zachgk** [comment]
You can find the classes that extend `ObjectDetectionDataset` in an IDE. Take a look at https://github.com/deepjavalibrary/djl/blob/master/basicdataset/src/main/java/ai/djl/basicdataset/cv/CocoDetection.java. It has a bunch of code for the ModelZoo repository, but you can ignore those parts.

**Comment by nikkisingh111333** [comment]
hey i m getting trouble undestanding cocoutils...i just want to clarify some things....
1.please first check my annotation file
german_shephard_anno.file

[n02106662_104.txt](https://github.com/deepjavalibrary/djl/files/6642197/n02106662_104.txt)

i have 250 german shepard images each have its own `.file` for labels..
i have 150 unique dogs folders contains `.file` for each image..
now in CoCoDataset its reading `json` file ..my stucking point is..
how can i create dataset to match all labels with their corresponding images.....pikachu detection have only 1 class so there its not clearly solving my problem which contain 150 diffrent class ...pikachu index.file contain BoundingBoxes for all pikachu images But Mine dataset have one index.file per image...how can i create dataset...CocoDataset is Complex to Understand for Me...? please suggest me

**Comment by zachgk** [comment]
If you have an IDE, just create a class extending `ObjectDetectionDataset` and have it add the required methods. In prepare, load all of the `.file` files into instance variables. You will need to write this function yourself, and possibly use an XML library because you data is in XML. Then, you have a few getImage and getObjects functions to fill in with the data from your instance variables.

**Comment by nikkisingh111333** [comment]
So I need to add all boundingbox in list instance variable ..Associated with image id...Ok I'll do that then let you know..?
