### ISSUE TITLE
multiply dataset after applying augmentation ?

### ISSUE THREAD

**Issue by nikkisingh111333** [deepjavalibrary/djl#1008]
hey,i want to multiply my Imagefolder dataset using pipeline augmentation ...i m using randomBrightness ,flipTransform etc.to multiply my dataset i have 2000 images...want to multiply it 3x2000 =6000 using these augmented transform classes..how can i do this.....???????

**Comment by zachgk** [comment]
Typically, you don't apply the randomness once, but apply it every time you load the image. Then, it isn't just a single 3x2000 but can act better than that. All you need to do is add the image transform to your image loading pipeline as part of your dataset class.

If you do want to have a fixed number, you will probably want to save it to disk. So, create a simple Java script that will take the original dataset and apply the transformations and save it to a different directory.

**Comment by nikkisingh111333** [comment]
Ok which means if I apply transform in my pipeline it will apply on all images with same parameter I provided like brightness 20f..All image will get brighten up with value 20..And it won't increase dataset size...
So which means I can use opencv to transform dataset and save it to my disk then upload it to my google drive that's what you are trying to say right?

**Comment by zachgk** [comment]
Not quite. You can make it random so each time you load an image it has a different brightness. Here is a sample of how it might work if you have three images and load all three in each batch with random brightness each time:

- Batch 1: Image A with brightness 5, Image B with brightness 20, Image C with brightness 2
- Batch 2: Image A with brightness 11, Image B with brightness 9, Image C with brightness 16
- Batch 2: Image A with brightness 1, Image B with brightness 3, Image C with brightness 12
- ...

There is just one copy of the images on disk, but random brightness is applied with a new random each time the images are loaded into a batch.
