### ISSUE TITLE
What is this Dataset Artifact ?

### ISSUE THREAD

**Issue by nikkisingh111333** [deepjavalibrary/djl#1020]
hey i m implementing objectdetectiondataset with dogs breed images and annotations...while using objectdetectiondataset class i m changing artifact from "pikachu" to "Dogs" and i m getting this error:

**java.io.FileNotFoundException: https://mlrepo.djl.ai/dataset/cv/ai/djl/basicdataset/gesture/metadata.json
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1920)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at java.base/java.net.URL.openStream(URL.java:1165)
	at ai.djl.repository.RemoteRepository.locate(RemoteRepository.java:96)
	at ai.djl.repository.RemoteRepository.resolve(RemoteRepository.java:116)
	at ai.djl.repository.Resource.getDefaultArtifact(Resource.java:79)
       at GestureDataset.prepare(#106:40)
       at .(#111:1)**
how can i prepare dataset is there no quick and fast way to create detection dataset...DOCUMENTATION is mess i cant find any end to end example for detection problems....Suggest me ?

**Comment by zachgk** [comment]
We use the `Repository` system to create repositories of datasets and models that have metdata, searchability, etc. Right now, the class you wrote is looking for your dataset in the Central DJL Repository (`mlrepo.djl.ai`). Obviously, you didn't add your dataset to the repository so it is not finding it there. While it is possible for your to make a custom repository in a different location, it is easier to remove the repository-specific code and change the class to use your filesystem directly

**Comment by nikkisingh111333** [comment]
How can I do that I have data in google drive ...Dogs data and annotations too..??

**Comment by frankfliu** [comment]
Sorry for missing this question.

For image classification, you can use [ImageFolder](https://github.com/deepjavalibrary/djl/blob/master/basicdataset/src/main/java/ai/djl/basicdataset/cv/classification/ImageFolder.java) to load images from local folders.

We currently don't have `Respository` that can load files from Google drive, we only have extensions that support AWS S3.

You should be able to implement your own `Respository` using google drive API. For more information see: S3 Respostory implementation source code: https://github.com/deepjavalibrary/djl/tree/master/extensions/aws-ai/src/main/java/ai/djl/aws/s3
