### ISSUE TITLE
how to inverse a NDArray

### ISSUE THREAD

**Issue by endlesshh** [deepjavalibrary/djl#1068]
## Description
how to inverse a NDArray,can you give me some help or example like troch.inverse

**Comment by endlesshh** [comment]
forward() Expected a value of type 'Dict[str, Tensor]'   多输入的模型怎么办？

**Comment by frankfliu** [comment]
> forward() Expected a value of type 'Dict[str, Tensor]' 多输入的模型怎么办？
In DJL, we always use NDList, however, each NDArray can have a name:
```
NDArray.setName(str)
```

**Comment by endlesshh** [comment]
> name
Thank you for your reply。another question，how to inverse a NDArray like  troch.inverse

**Comment by endlesshh** [comment]
I moved the troch.inverse to inside of the model

**Comment by EugeneChung** [comment]
Is there any example? DJL doesn't have API calling like torch.linalg.inv?
