### ISSUE TITLE
Documentation bug in minimum

### ISSUE THREAD

**Issue by ElchananHaas** [deepjavalibrary/djl#1112]
In api/src/main/java/ai/djl/ndarray/NDArray.java on line 1472 in the documentation for minimum it says it takes the maximum instead. It should be changed to say it takes the minimum instead. 

    /**
     * Returns the maximum of this {@code NDArray} and the other {@code NDArray} element-wise.
     *
     * <p>The shapes of this {@code NDArray} and the other {@code NDArray} must be broadcastable.
     *
     * <p>Examples
     *
     * <pre>
     * jshell&gt; NDArray array1 = manager.create(new float[] {2f, 3f, 4f});
     * jshell&gt; NDArray array2 = manager.create(new float[] {1f, 5f, 2f});
     * jshell&gt; array1.minimum(array2);
     * ND: (3) cpu() float32
     * [1., 3., 2.]
     * jshell&gt; NDArray array1 = manager.eye(2);
     * jshell&gt; NDArray array2 = manager.create(new float[] {0.5f, 2f});
     * jshell&gt; array1.minimum(array2); // broadcasting
     * ND: (2, 2) cpu() float32
     * [[0.5, 0. ],
     *  [0. , 1. ],
     * ]
     * </pre>
     *
     * @param other the {@code NDArray} to be compared
     * @return the maximum of this {@code NDArray} and the other {@code NDArray} element-wise
     */
    NDArray minimum(NDArray other);

**Comment by frankfliu** [comment]
@ElchananHaas Thank you for reporting this issue to us. Would you mind raise a PR to resolve this bug?
