### ISSUE TITLE
ai.djl.repository.zoo.ModelNotFoundException: No matching model with specified Input/Output type found.

### ISSUE THREAD

**Issue by Superji-dev** [deepjavalibrary/djl#1232]
## Description
(A clear and concise description of what the bug is.)

### Expected Behavior
(what's the expected behavior?)

### Error Message
(Paste the complete error message, including stack trace.)

## How to Reproduce?
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

## Environment Info

Please run the command `./gradlew debugEnv` from the root directory of DJL (if necessary, clone DJL first). It will output information about your system, environment, and installation that can help us debug your issue. Paste the output of the command below:

```
PASTE OUTPUT HERE
```

**Comment by frankfliu** [comment]
@Superji-dev Please provide more detail, such as your criteria, the exception stacktrace, model loading logs with debug level enabled, and your build.gradle/pom.xml file

**Comment by Superji-dev** [comment]
I hava solved this problem! The name of the model.pt name must be the same as the name of the folder in which the model.pt is stored, and I miss that!
