### ISSUE TITLE
MXNetError: Unknown type enum 7

### ISSUE THREAD

**Issue by sbd2** [deepjavalibrary/djl#1343]
## Description
Many times when I try to access any value on a NDArray I get this exception. However, if I debug the code, stop before the exception is thrown and manually evaluate the expression, I get the exception once and then the value. The code performs as expected after that.

### Expected Behavior
The values of a NDArray should be accesible at any time.

### Error Message

```
ai.djl.engine.EngineException: MXNet engine call failed: MXNetError: Unknown type enum 7
Stack trace:
  File "C:\Users\Administrator\kimbergz\b4\src\operator\tensor\./matrix_op-inl.h", line 1149


	at ai.djl.mxnet.jna.JnaUtils.checkCall(JnaUtils.java:1930)
	at ai.djl.mxnet.jna.JnaUtils.syncCopyToCPU(JnaUtils.java:489)
	at ai.djl.mxnet.engine.MxNDArray.toByteBuffer(MxNDArray.java:295)
	at ai.djl.ndarray.NDArray.toBooleanArray(NDArray.java:331)
```

The instant before I was trying to access to `NDArray#toBooleanArray`

## How to Reproduce?
There is no certain way to reproduce it. The error seems to appear after performing several operations on 3-dimensional NDArrays. Once with a (6, 6, 6) NDArray and once with a (8, 8, 8) NDArray.

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1. Create a NDArray by performing several operations:

```
NDArray orthogonallyAccessibleMaskMax = columns.get(index).eq(maxs.get(index))
          .logicalAnd(infiniteSurfaceMask.neg()).logicalAnd(
              deltaNormalsPositions.dot(loopArgumentsMatrixMax.get(index)).gt(RADIUS_TOLERANCE))
          .toType(DataType.FLOAT32, true);
```

2. Try to access any value from the recently created NDArray, for example `orthogonallyAccessibleMaskMax.get(0)`

## What have you tried to solve it?

1. Debug the program until the point where the exception is being thrown.
2. Manually evaluate the element access until the exception is not thrown anymore and the values are retrieved.

**Comment by frankfliu** [comment]
@sbd2 
Which version are you using?
Can you try to run the same ndarray operation in python and see if this is a MXNet issue?
Would you please share the complete code so we can try to reproduce it?

**Comment by sbd2** [comment]
@frankfliu 
I am using engine version 0.11.0 and native auto version 1.8.0. It is working in Python.

The code snippet is:

```
    NDArray mins = surfaceMatrix.nonzero().min(new int[] {0}).toType(DataType.FLOAT32, false);
    NDArray maxs = surfaceMatrix.nonzero().max(new int[] {0}).toType(DataType.FLOAT32, false);
    NDList columns = surfaceMatrix.split(new long[] {1, 2}, 2);
    NDArray loopArgumentsMatrixMax = manager.create(LOOP_ARGUMENTS_MAX)
        .toType(DataType.FLOAT32, false).reshape(3, -1);
    NDArray loopArgumentsMatrixMin = manager.create(LOOP_ARGUMENTS_MIN)
        .toType(DataType.FLOAT32, false).reshape(3, -1);
    NDArray infiniteSurfaceMask = manager.zeros(surfaceMatrix.getShape())
        .toType(DataType.BOOLEAN, false);

    for (int index = 0; index < 2; index++) {
      NDArray orthogonallyAccessibleMaskMax = columns.get(index).eq(maxs.get(index))
          .logicalAnd(infiniteSurfaceMask.neg()).logicalAnd(
              deltaNormalsPositions.dot(loopArgumentsMatrixMax.get(index)).gt(RADIUS_TOLERANCE))
          .toType(DataType.FLOAT32, true);

      if (orthogonallyAccessibleMaskMax.any().getBoolean()) {
        infiniteSurfaceMask.add(orthogonallyAccessibleMaskMax);
      }
```

Where the inputs are `surfaceMatrix` is a (6, 6, 6) 0s and 1s matrix as Float32 type and `deltaNormalsPositions` is a (6, 6, 6, 3) Float32 matrix where the first 3 dimensions are the same as for `surfaceMatrix` and the other is a Float32 vector.

LOOP_ARGUMENTS_MAX is a (3, 3) Float32 matrix with -1 in its main diagonal and 0 anywhere else.
LOOP_ARGUMENTS_MIN is a (3, 3) Float32 matrix with 1 in its main diagonal and 0 anywhere else.

**Comment by frankfliu** [comment]
I'm able to reproduce the issue with the following code:

```
    NDArray zeros = manager.zeros(new Shape(6, 6, 6)).toType(DataType.BOOLEAN, true);
    NDArray array = zeros.neg();
    boolean ret = array.getBoolean();
    System.out.println(ret);
````
I think the error was due to MXNet has limited support for boolean type, the same python code will fail as well:

```
from mxnet import nd
array = nd.zeros(1, dtype='bool')
nd.negative(array)
```
