### ISSUE TITLE
Are there demos of recommended scenarios?

### ISSUE THREAD

**Issue by freesia-sherry** [deepjavalibrary/djl#1365]
In the homepage of djl, i can only find demo with cv scenes. I wonder whether are any recomendations demos, Thanks.

**Comment by freesia-sherry** [comment]
In other words, I want to know how to use any general neural networks such as MLP in the DJL. The inputs might be a vector and outputs are multiple classfication.

**Comment by keerthanvasist** [comment]
You can follow these tutorials:
https://docs.djl.ai/jupyter/tutorial/01_create_your_first_network.html
https://towardsdatascience.com/deep-learning-in-java-d9b54ae1423a

There are also a number of training examples in the examples folder:
https://github.com/deepjavalibrary/djl/tree/master/examples/src/main/java/ai/djl/examples/training

**Comment by freesia-sherry** [comment]
> You can follow these tutorials: https://docs.djl.ai/jupyter/tutorial/01_create_your_first_network.html https://towardsdatascience.com/deep-learning-in-java-d9b54ae1423a
> 
> There are also a number of training examples in the examples folder: https://github.com/deepjavalibrary/djl/tree/master/examples/src/main/java/ai/djl/examples/training

Thanks for the reply. But what I want is not to train my model based on DJL, but to load my model from PyTorch which is already trained. Below is the code I change the demo code from the homepage of DJL, but got an exception for "No matching default translator found. The valid input and output classes are: (ai.djl.ndarray.NDList, ai.djl.ndarray.NDList)". I think maybe I need a translator, but I don't know how to build the translator for the general networks. In the demo code, the translator's type is ImageClassificationTranslator, so in my case, which translator should I use?


`import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;

import ai.djl.*;
import ai.djl.inference.*;
import ai.djl.modality.*;
import ai.djl.modality.cv.*;
import ai.djl.modality.cv.transform.*;
import ai.djl.modality.cv.translator.*;
import ai.djl.ndarray.NDArray;
import ai.djl.ndarray.NDManager;
import ai.djl.ndarray.types.Shape;
import ai.djl.repository.zoo.*;
import ai.djl.translate.*;
import ai.djl.training.util.*;

public class predict {
    public static void main(String[] args) throws IOException, ModelNotFoundException, MalformedModelException, TranslateException {

        NDManager manager = NDManager.newBaseManager();
        System.setProperty("ai.djl.repository.zoo.location", "build/pytorch_models/tinyNet");
        Criteria<NDArray, Classifications> criteria = Criteria.builder()
                .setTypes(NDArray.class, Classifications.class)
                .optProgress(new ProgressBar())
                .build();
        ZooModel<NDArray, Classifications> model = ModelZoo.loadModel(criteria);

        // load local inputs
        NDArray inputs = manager.ones(new Shape(2, 4));
        Predictor<NDArray, Classifications> predictor = model.newPredictor();
        Classifications classifications = predictor.predict(inputs);
        System.out.println(classifications);
    }
}`

**Comment by frankfliu** [comment]
@freesia-sherry 
A Translator is a class that allow you convert Input java object into NDArray and output NDArray back to java object.

Here is the j[upyter notebook](https://github.com/deepjavalibrary/djl/blob/master/jupyter/pytorch/load_your_own_pytorch_bert.ipynb) that teach you how to create your Translator for BERT model.

**Comment by frankfliu** [comment]
@freesia-sherry 
A general model can take multiple inputs and multiple outputs. In DJL we use NDList (list of NDArray) as input and output, If you want to take a shortcut (not recommended, you need manually manage NDArray's lifecycle), you can define your Criteria<NDList, NDList>:

```
    Criteria<NDList, NDList> criteria = Criteria.builder()
            .setTypes(NDList.class, NDList.class)
            .optModelPath(Paths.get("build/pytorch_models/tinyNet/tinyNet.pt")
            .optProgress(new ProgressBar())
            .build();
    ZooModel<NDList, NDList> model = ModelZoo.loadModel(criteria);

    // load local inputs
    NDManager manager = NDManager.newBaseManager();
    NDArray input = manager.ones(new Shape(2, 4));
    NDList inputs = new NDList(input):
    Predictor<NDList, NDList> predictor = model.newPredictor();
    NDList outputs = predictor.predict(inputs);
    Classifications classifications = convert_ndlist_to_classifications(outputs);
    manager.close(); // close all input/output resources
```

**Comment by freesia-sherry** [comment]
> @freesia-sherry A general model can take multiple inputs and multiple outputs. In DJL we use NDList (list of NDArray) as input and output, If you want to take a shortcut without Translator (not recommended, you need manually manage NDArray's lifecycle), you can define your Criteria<NDList, NDList>:
> 
> ```
>     Criteria<NDList, NDList> criteria = Criteria.builder()
>             .setTypes(NDList.class, NDList.class)
>             .optModelPath(Paths.get("build/pytorch_models/tinyNet/tinyNet.pt")
>             .optProgress(new ProgressBar())
>             .build();
>     ZooModel<NDList, NDList> model = ModelZoo.loadModel(criteria);
> 
>     // load local inputs
>     NDManager manager = NDManager.newBaseManager();
>     NDArray input = manager.ones(new Shape(2, 4));
>     NDList inputs = new NDList(input):
>     Predictor<NDList, NDList> predictor = model.newPredictor();
>     NDList outputs = predictor.predict(inputs);
>     Classifications classifications = convert_ndlist_to_classifications(outputs);
>     manager.close(); // close all input/output resources
> ```

Thanks a lot!
