### ISSUE TITLE
When djl support xgboost .dat model file

### ISSUE THREAD

**Issue by wangzulong** [deepjavalibrary/djl#1389]
## Description
current xgboost model enigne support xgboost .json model file , sometimes we need to support xgboost .dat model file. I just want to know this feautre is in your develop plan, if not, i want to develop these codes in our project and commit to community.

**Comment by frankfliu** [comment]
Have you try to load ".dat" file directly:

```
Criteria<NDList, NDList> criteria = Criteria.builder()
            .setTypes(NDList.class, NDList.class)
            .optEngine("XGBoost")
            .optModelPath(Paths.get("/models/model.dat")
            .build();
```

**Comment by zachgk** [comment]
I'm closing this as a solution has been proposed. If it doesn't work or you have additional problems, feel free to reopen the issue
