### ISSUE TITLE
jvm crash at processInput with paddlepaddle

### ISSUE THREAD

**Issue by zouxiaodong** [deepjavalibrary/djl#1408]
Error Message Summary:
----------------------
NotFoundError: Operator (conv2d) does not have kernel for data_type[uint8_t]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at D:\shixiaowei02\Paddle\paddle\fluid\framework\operator.cc:1236)

----translator for object detection
    NDList processImageInput(NDManager manager, Image input) {
        NDArray image = input.toNDArray(manager);
        //image = image.transpose(2, 0, 1).flip(0); // HWC -> CHW BGR -> RGB
        Shape shape = image.getShape();
        NDArray im_shape = manager.create(new float[]{shape.get(0)/1.0f,shape.get(1)/1.0f});
        NDArray scale_factor = manager.create(new float[]{1.0f, 1.0f});
        // array = NDImageUtils.resize(
        //         array, (int) (shape.get(1) * shrink), (int) (shape.get(0) * shrink));
        //array = array.transpose(2, 0, 1).flip(0); // HWC -> CHW BGR -> RGB
        //NDArray mean = manager.create(new float[]{104f, 117f, 123f}, new Shape(3, 1, 1));
        // array = array.sub(mean).mul(0.007843f); // normalization
        //array = array.expandDims(0); // make batch dimension
        return new NDList(im_shape, image, scale_factor);
    }

**Comment by frankfliu** [comment]
@zouxiaodong Have you try the same code with python?

**Comment by zouxiaodong** [comment]
I tried Python code，that works well.i think that is paddlepaddle engine  issue , i will try pytorch or tensorflow
