### ISSUE TITLE
SentencePiece Support for Windows

### ISSUE THREAD

**Issue by Lundez** [deepjavalibrary/djl#1411]
## Description

Let's add support for Windows for SentencePiece. It is already supported upstream in the library.

I think changing https://github.com/deepjavalibrary/djl/blob/master/.github/workflows/native_s3_sentencepiece.yml to include a windows build should be enough?

Who will benefit from this enhancement?
Windows users.

**Comment by Lundez** [comment]
> @Lundez by the way, we are adding Huggingface tokenizers support: https://github.com/deepjavalibrary/djl/pull/1406

That's amazing news! I hope to see it soon 😍

Regarding setting up a PR - I'll try to get that done by the weekend

**Comment by frankfliu** [comment]
Fixed with #1412
