### ISSUE TITLE
PaddleOCR others version error

### ISSUE THREAD

**Issue by xiaoshuaishuai319** [deepjavalibrary/djl#1415]
use djl 0.14.0
if use https://docs.djl.ai/jupyter/paddlepaddle/paddle_ocr_java.html provide model file 
run demo successful
if use Paddle OCR V2 version can be run error

`Exception in thread "main" java.io.FileNotFoundException: no __model__ or model file found in: C:\Users\Administrator\.djl.ai\cache\repo\model\undefined\ai\djl\localmodelzoo\5b5ea07bce62f8422d734bfba7c00cda`

model version ch_PP_OCRv2,ch_ppocr_server_v2,ch_ppocr_mobile_v2 all run error 

Exception in thread "main" java.io.FileNotFoundException: no __model__ or model file found in ......

**Comment by frankfliu** [comment]
What's the file name in your model folder?

We are looking for `mode`/`__model__` or `inference.pdmodel` file in the directory, 
See: https://github.com/deepjavalibrary/djl/blob/master/engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpModel.java#L101-L104
