### ISSUE TITLE
No matching model with specified Input/Output type found.

### ISSUE THREAD

**Issue by davpapp** [deepjavalibrary/djl#1416]
## Description
I'm trying to load a custom object detection model object detection model trained via a pytorch script. The model is saved as a .pt file. The mlnet.pt file is saved inside my eclipse workspace, which is where I'm running the code from. 
So the absolute path of the model to load is : "/Users/dpapp/eclipse-workspace/mlProject/src/mlnet/mlnet.pt"

I try to load this model using the following code:
```
Criteria<Image, DetectedObjects> criteria =
                Criteria.builder()
                        .optApplication(Application.CV.OBJECT_DETECTION)
                        .setTypes(Image.class, DetectedObjects.class)
                        .optModelUrls("file:///Users/dpapp/eclipse-workspace/mlProject/src/mlnet")
                        .build();
ZooModel model = criteria.loadModel();
```

However, I get the error message shown below.

### Expected Behavior
I expect the model to successfully be loaded.

### Error Message
```
ai.djl.repository.zoo.ModelNotFoundException: No matching model with specified Input/Output type found.
	at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:178)
	at main.main(main.java:86)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: ai.djl.repository.zoo.ModelNotFoundException: No supported engine available for model zoo: ai.djl.localmodelzoo
	at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:135)
	at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:166)
```

## How to Reproduce?
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1. Save mlnet.pt model in the following location: "/Users/dpapp/eclipse-workspace/mlProject/src/mlnet/mlnet.pt"
2. Criteria<Image, DetectedObjects> criteria =
                Criteria.builder()
                        .optApplication(Application.CV.OBJECT_DETECTION)
                        .setTypes(Image.class, DetectedObjects.class)
                        .optModelUrls("file:///Users/dpapp/eclipse-workspace/mlProject/src/mlnet")
                        .build();
ZooModel model = criteria.loadModel();

## What have you tried to solve it?

1. I've tried both absolute and relative paths.
2. I've tried different criteria input and output types, including a generic <?, ?>
3. I've tried setting the optModelName parameter

## Environment Info

maven inside eclipse

**Comment by frankfliu** [comment]
@davpapp You need specify a `Translator` to load your model:
```
Translator<Image, DetectedObjects> translator = PtSsdTranslator.builder()
    .optSynsetUrl("https://...")
    .addTransform(...)
    .build();
Criteria<Image, DetectedObjects> criteria = Criteria.builder()
    .optApplication(Application.CV.OBJECT_DETECTION)
    .setTypes(Image.class, DetectedObjects.class)
    .optModelUrls("file:///Users/dpapp/eclipse-workspace/mlProject/src/mlnet")
    .optTranslator
    .build();
```

The translator has to match your model's pre/post processing, see an example of configuration: https://github.com/deepjavalibrary/djl/blob/master/engines/pytorch/pytorch-model-zoo/src/test/resources/mlrepo/model/cv/object_detection/ai/djl/pytorch/ssd/metadata.json#L27-L83

**Comment by davpapp** [comment]
Thank you for the quick and helpful feedback. I added a translator but I'm getting the same error. Is there any way to obtain a more detailed error message to help debug this?  
This is the translator I added:
```
Translator<Image, DetectedObjects> translator = SingleShotDetectionTranslator.builder()
                .addTransform(new Resize(320))
                .build();
```
But I get the same error. At this point, I don't know the error is any of the following: 1) my translator doesn't match my model, 2) translator is missing some key arguments such as the SynsetURL, 3) Criteria URL is incorrect and it can't find my model.

**Comment by davpapp** [comment]
I should also add that I used a PyTorch training script that I did not write myself. So I'm unsure of what the exact pre and post-processing steps are. Without inspecting training script to find the exact pre and post processing steps, will I be able to  create a working translator, or is there a more generic translator I can use?

**Comment by frankfliu** [comment]
@davpapp each SSD model processing are quite different, it's really depends on how you trained it.

1. Synset, if your model is trained on Coco dataset, you can use the following:

```
    optSynsetUrl("https://mlrepo.djl.ai/model/cv/object_detection/ai/djl/pytorch/classes_coco.txt")
```
2. You can enable debug log level, you can see more model loading debug informations, see: https://github.com/deepjavalibrary/djl/blob/master/docs/load_model.md#enable-debug-log
3. The URL looks fine, but we recommend to use `.optModelPath()` if you load from local file system.

**Comment by davpapp** [comment]
Thanks for the quick response. I have one follow up question regarding what type of translator to use. 
The model I trained is a YOLO model. I saw that there are a few Translator classes: https://javadoc.io/static/ai.djl/api/0.5.0/ai/djl/modality/cv/translator/package-summary.html. 

I'm trying to figure out which one to use. The candidates are:
1) YoloTranslator
2) BaseImageTranslator
3) ObjectDetectionTranslator

My model takes an input in the form [1, 640, 640, 3] (because it was trained on 640x640 images). As an input to the model, I load a .jpg into a BufferedImage. Which one should I go with? Thank you in advance!

**Comment by davpapp** [comment]
I went with the YoloTranslator and made some progress. However, I now get another error. This is what my translator looks like:
```
Translator<Image, DetectedObjects> translator = YoloTranslator.builder()
     .setPipeline(new Pipeline())
    .build();
```

And the error I'm getting is:
ai.djl.engine.EngineException: PytorchStreamReader failed locating file constants.pkl: file not found
	at ai.djl.pytorch.jni.PyTorchLibrary.moduleLoad(Native Method)
	at ai.djl.pytorch.jni.JniUtils.loadModule(JniUtils.java:1360)
	at ai.djl.pytorch.engine.PtModel.load(PtModel.java:89)

My model only contains a .pt file. There are no other files. Do you know what might be going on? Thank you!

**Comment by frankfliu** [comment]
@davpapp 

1. `YoloTranslator` was implemented to match MXNet GluonCV Yolo model
2. `YoloV5Translator` was implemented Tensorflow Yolo5 model

Since you are using a PyTorch mode. I'm not sure if it work for your model not.

**Comment by frankfliu** [comment]
> I went with the YoloTranslator and made some progress. However, I now get another error. This is what my translator looks like:
> 
> ```
> Translator<Image, DetectedObjects> translator = YoloTranslator.builder()
>      .setPipeline(new Pipeline())
>     .build();
> ```
> 
> And the error I'm getting is: ai.djl.engine.EngineException: PytorchStreamReader failed locating file constants.pkl: file not found at ai.djl.pytorch.jni.PyTorchLibrary.moduleLoad(Native Method) at ai.djl.pytorch.jni.JniUtils.loadModule(JniUtils.java:1360) at ai.djl.pytorch.engine.PtModel.load(PtModel.java:89)
> 
> My model only contains a .pt file. There are no other files, and definitely no constants.pkl file. However, when I was testing ObjectDetection using the tutorial: https://docs.djl.ai/jupyter/object_detection_with_model_zoo.html#step-1-load-image, I downloaded a model folder. That one had a constants.pkl file. Do you know what might be going on? Is my model not exported correctly? Thank you in advance!

You need use `jit.trace()` to export your model. libtorch C++ api only support traced script model:
https://docs.djl.ai/docs/pytorch/how_to_convert_your_model_to_torchscript.html

See this PyTorch issue: https://github.com/pytorch/pytorch/issues/47917

**Comment by davpapp** [comment]
Thank you again for the quick response. I looked through the link your provided to trace and export the model to torchscript. I found that the YoloV5 repo I used to train my model supplies an export function that looks like this: (full code: https://github.com/ultralytics/yolov5/blob/master/export.py)
```
def export_torchscript(model, im, file, optimize, prefix=colorstr('TorchScript:')):
    # YOLOv5 TorchScript model export
    try:
        LOGGER.info(f'\n{prefix} starting export with torch {torch.__version__}...')
        f = file.with_suffix('.torchscript')

        ts = torch.jit.trace(model, im, strict=False)
        d = {"shape": im.shape, "stride": int(max(model.stride)), "names": model.names}
        extra_files = {'config.txt': json.dumps(d)}  # torch._C.ExtraFilesMap()
        (optimize_for_mobile(ts) if optimize else ts).save(str(f), _extra_files=extra_files)

        LOGGER.info(f'{prefix} export success, saved as {f} ({file_size(f):.1f} MB)')
    except Exception as e:
        LOGGER.info(f'{prefix} export failure: {e}')
```
This does the tracing via `jit.trace()` and saves a .torchscript file. However, there is still not .pkl file, so the model cannot be loaded. 
1) Does the file suffix matter for the purposes of loading the model with DJL? Should it be a .pt or a .torchscript file that we load?
2) How can I get the .pkl and possibly other necessary files?

Thank you!

**Comment by davpapp** [comment]
I was able to get this resolved. Thank you for the help!

**Comment by maxwellhaihui** [comment]
> I was able to get this resolved. Thank you for the help!

Hello, friend! I also encountered this problem: "pytorchstreamreader failed locating file constants.pkl: file not found".
I also use "export.py" converts my yolov5 model (.pt file) to .torchscript file, but it doesn't work.
Could you share your solution? Thank you very much!

**Comment by frankfliu** [comment]
@maxwellhaihui 

Please make sure you use `TorchScript` format to export your model, see: https://github.com/ultralytics/yolov5/blob/master/export.py#L70

**Comment by maxwellhaihui** [comment]
> @maxwellhaihui
> 
> Please make sure you use `TorchScript` format to export your model, see: https://github.com/ultralytics/yolov5/blob/master/export.py#L70

Thank you for your help. I'll study this code carefully again.
