### ISSUE TITLE
no network in production, Failed to download PyTorch native library

### ISSUE THREAD

**Issue by yinrong** [deepjavalibrary/djl#1417]
production environment have no Internet access. how to make ai.djl work ?

my sbt dependencies:
```
"ai.djl" % "api" % "0.14.0",
"ai.djl.pytorch" % "pytorch-engine" % "0.14.0",
"net.java.dev.jna" % "jna" % "5.8.0",
```

classes I'm using:
```
Model.newInstance.newPredictor
NDList
Translator
```

error:
```
        ...
	at org.apache.spark.deploy.yarn.ApplicationMaster
Caused by: java.net.SocketException: Network is unreachable (connect failed)
        ...
	at ai.djl.pytorch.jni.LibUtils.downloadPyTorch(LibUtils.java:412)
```

**Comment by yinrong** [comment]
workaround: 
`java -DENGINE_CACHE_DIR=xxx`  and copy xxx manually to runtime environment.

**Comment by frankfliu** [comment]
@yinrong 

You can install engine specific jar as your dependency, for example to include linux pytorch native library:
```
<dependency>
    <groupId>ai.djl.pytorch</groupId>
    <artifactId>pytorch-native-cpu</artifactId>
    <classifier>linux-x86_64</classifier>
    <scope>runtime</scope>
    <version>1.9.1</version>
</dependency>
```
See: https://github.com/deepjavalibrary/djl/tree/master/engines/pytorch/pytorch-engine#linux

If you distribute to multiple os/GPU system, and you don't care about the distribution size, you can include multiple pytorch-native-xxx.jar files in your distributon.

**Comment by yinrong** [comment]
@frankfliu may I comiple native lib by myself?  still NOT working with dependency `pytorch-native-cpu` and `pytorch-native-cpu-precxx11`


```
Caused by: java.lang.UnsatisfiedLinkError:
/home/work/.djl.ai/pytorch/1.9.1-20211025-cpu-linux-x86_64/0.14.0-cpu-libdjl_torch.so:
/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found
(required by /home/work/.djl.ai/pytorch/1.9.1-20211025-cpu-linux-x86_64/0.14.0-cpu-libdjl_torch.so)
```

buid.sbt
```sbt
libraryDependencies ++= Seq(
  "ai.djl" % "api" % "0.14.0",
  "ai.djl.pytorch" % "pytorch-engine" % "0.14.0",
  "net.java.dev.jna" % "jna" % "5.8.0",
  "ai.djl.pytorch" % "pytorch-native-cpu" % "1.9.1" % "runtime" classifier "linux-x86_64",
)
```

```sh
unzip -l .out/xxx.deps.jar |grep djl|grep linux                                                                                                             
  2752600  01-01-2010 00:00   jnilib/linux-x86_64/cpu-precxx11/libdjl_torch.so
  2850072  01-01-2010 00:00   jnilib/linux-x86_64/cpu/libdjl_torch.so
  3074520  01-01-2010 00:00   jnilib/linux-x86_64/cu102/libdjl_torch.so
  3074520  01-01-2010 00:00   jnilib/linux-x86_64/cu111/libdjl_torch.so
```

```sh
spark-submit ... \
--class com.aaa.DeepPredTest --jars \
hdfs://zjyprc-hadoop/user/s_ya/jar/xxx.deps.jar  \
hdfs://zjyprc-hadoop/user/s_ya/jar/xxx.jar
```

**Comment by frankfliu** [comment]
@yinrong Which version of linux are you using?

With DJL 0.15.0-SNAPSHOT version, you can set environment variable to point to where to load libtorch.so file: 
```
PYTORCH_LIBRARY_PATH=/...
PYTORCH_VERSION=1.9.1
```

But the minimal glibc ABI version that python can support is: `CXXABI_1.3.9 ` . I really doubt if you can build your own libtorch 1.9.1 if the system is that old.

**Comment by frankfliu** [comment]
@yinrong A couple of questions regarding your dependency

1. You are not using `pytorch-native-cpu-precxx11`, you must only include `pytorch-native-cpu-precxx11` if you are running on ubuntu 16.04
2. I didn't see `libtorch.so` in your jar file, can you check if the file is extracted properly in the cache directory?

**Comment by yinrong** [comment]
> 
can I change setting by Model constructor, other than java property or system environment ? because I'm using spark / scala on a public yarn cluster, where environment can not change. (unless public decision is made) 

my production servers: `3.18.6-2.el7.centos.x86_64`

**Comment by frankfliu** [comment]
`pytorch-native-cpu-precxx11` should work on centos7, we have customer running DJL with pytorch on Spark with centos7

**Comment by yinrong** [comment]
I will get back with more info next week.

**Comment by yinrong** [comment]
@frankfliu thanks.  the problem is sbt `runtime` scope is a little tricky to use. djl is good.
