### ISSUE TITLE
How the use higher version DJL with lower version PyTorch

### ISSUE THREAD

**Issue by dxjjhm** [deepjavalibrary/djl#1443]
how to use djl 0.12.0 or higher with pytorch1.7.1-cuda10.1 version,
could some expert give me some suggestions?

**Comment by frankfliu** [comment]
@dxjjhm 

Unfortunately, only djl 0.10.0 can support pytorch1.7.1-cuda10.1 version. We made some improvement in 0.14.0 to support older version of pytorch up to 0.18.0, see:

https://docs.djl.ai/engines/pytorch/pytorch-engine/index.html

**Comment by dxjjhm** [comment]
@frankliu, thanks for you reply, do you kown how to produce jnilib of cu101, cu102, cu111， cpu etc  .so or .dll dependencies?

**Comment by frankfliu** [comment]
@dxjjhm 

1. You can build jnilib from djl source: 

```
cd djl/engines/pytorch/pytorch-native
./gradlew compileJNI
```
2. You can download pre-built native libraries from s3, https://publish.djl.ai/pytorch/1.8.1/files.txt, see: https://github.com/deepjavalibrary/djl/blob/master/engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java#L348

**Comment by frankfliu** [comment]
Free feel to reopen this issue if you have further questions.
