### ISSUE TITLE
Will DJL support time series preprocess ?

### ISSUE THREAD

**Issue by r1ckypp** [deepjavalibrary/djl#1452]
Will DJL support time series preprocess ?
Hi, there are some preprocess implementations for cv, nlp in ai.djl.modality,
and currently I am working on time series model inference with djl, so I wonder if djl will support some preprocess for time series data ? (like general scaler or more specific feature engineering like what gluonts done https://ts.gluon.ai/api/gluonts/gluonts.transform.feature.html)
or is there any thing djl has done and I missed ? :)

**Comment by frankfliu** [comment]
@r1ckypp 
We don't have time series processing in DJL today, but this is something we'd like to add. It would be great if you can contribute TS to DJL.

**Comment by r1ckypp** [comment]
Thanks for your reply. :) And I am willing to try to contribute(not familiar with that) if I get some progress.

**Comment by KexinFeng** [comment]
@r1ckypp We have just added the support for gluonTS model inference. Check out https://github.com/deepjavalibrary/djl/pull/1903
