### ISSUE TITLE
The same model, onnx, DJL and C++ inference results are different

### ISSUE THREAD

**Issue by MrSSai** [deepjavalibrary/djl#1453]
## Description
The algorithm engineer used yolov5 to train a model and output the model file in torchscript and onnx format. I can also infer the correct result by calling the onnx model using C#. When using DJL to call torchscript and onnx models, the inference results are incorrect. Below is the code I tested

### Expected Behavior
Due to confidentiality, it cannot be made public. I can send you an email if needed

### Error Message
No error message

## How to Reproduce?
The version I use is 0.14.0，jdk1.8
- Java
```
 public static void main(String[] args) throws ModelNotFoundException, MalformedModelException, IOException, TranslateException {
        Pipeline pipeline = new Pipeline();
        pipeline.add(new Resize(640));
        pipeline.add(new ToTensor());
        Translator<Image, DetectedObjects> translator = YoloV5Translator.builder()
                .setPipeline(pipeline)
                .optSynset(new ArrayList<String>(){{
                    add("Category1");
                }})
                .optThreshold(0.25f)
                .optNmsThreshold(0.45f)
                .build();

        Criteria<Image, DetectedObjects> criteria = Criteria.builder()
                .setTypes(Image.class, DetectedObjects.class)
                .optModelUrls("build/cell-segmentation-v1.onnx")
                .optDevice(Device.cpu())
                .optTranslator(translator)
                .optEngine("OnnxRuntime")
                .optProgress(new ProgressBar())
                .build();

        ZooModel model = criteria.loadModel();
        System.out.println(model.getName());
        Predictor<Image, DetectedObjects> predictor = model.newPredictor();
        File file = new File("build/imgs/319.jpg");
        Image image = ImageFactory.getInstance().fromFile(Paths.get(file.getAbsolutePath()));
        DetectedObjects detection = predictor.predict(image);
    }
```

## What have you tried to solve it?

1.I try to resize image size using ImageIO and opencv [https://github.com/deepjavalibrary/djl/issues/1116](https://github.com/deepjavalibrary/djl/issues/1116)

Because of the need for confidentiality, the model files cannot be made public. If you need the model file, I can send it to your mailbox

Can you help me?

**Comment by MrSSai** [comment]
this is my C# main code

- Yolov5Model
```
using System.Collections.Generic;
using Yolov5Net.Scorer.Models.Abstract;

namespace Yolov5Net.Scorer.Models
{
    public class YoloCocoP5Model : YoloModel
    {
        public override int Width { get; set; } = 640;
        public override int Height { get; set; } = 640;
        public override int Depth { get; set; } = 3;

        public override int Dimensions { get; set; } = 6;

        public override int[] Strides { get; set; } = new int[] { 8, 16, 32 };

        public override int[][][] Anchors { get; set; } = new int[][][]
        {
            new int[][] { new int[] { 010, 13 }, new int[] { 016, 030 }, new int[] { 033, 023 } },
            new int[][] { new int[] { 030, 61 }, new int[] { 062, 045 }, new int[] { 059, 119 } },
            new int[][] { new int[] { 116, 90 }, new int[] { 156, 198 }, new int[] { 373, 326 } }
        };

        public override int[] Shapes { get; set; } = new int[] { 80, 40, 20 };

        public override float Confidence { get; set; } = 0.20f;
        public override float MulConfidence { get; set; } = 0.25f;
        public override float Overlap { get; set; } = 0.45f;

        public override string[] Outputs { get; set; } = new[] { "output" };

        public override List<YoloLabel> Labels { get; set; } = new List<YoloLabel>()
        {
            new YoloLabel { Id = 1, Name = "T" },
        };

        public override bool UseDetect { get; set; } = true;

        public YoloCocoP5Model()
        {

        }
    }
}
```
My C# is modified on the basis [https://github.com/mentalstack/yolov5-net](https://github.com/mentalstack/yolov5-net)

**Comment by zachgk** [comment]
When the model prediction results don't match other systems, it is almost always because either the pre-processing or post-processing of the data is different. It should exactly match how the model was first trained if you want the result to be as accurate as how it was trained.

The DJL `YoloV5Translator` is designed to match a particular implementation (https://github.com/ultralytics/yolov5). This may also differ from the implementation that you used. I recommend trying to debug the pre-processing and post-processing of both the DJL and C# at the same time with the same image to see if they do different things at one point. One tip is that you can compare entire NDArrays by computing the sum of the NDArray and seeing if those numbers match.

**Comment by MrSSai** [comment]
I'm really glad to receive your response,I will try as you suggest. Thank you very much.
