### ISSUE TITLE
I try to run djl demo in CentOS 7.4,but it run failed..

### ISSUE THREAD

**Issue by evan-me** [deepjavalibrary/djl#1498]
![image](https://user-images.githubusercontent.com/50353139/153833389-0e3fee9d-930e-474c-bf93-b25938513400.png)
![image](https://user-images.githubusercontent.com/50353139/153833438-67282276-7cde-4b6f-9033-a5ca431b10df.png)
I search how to upgrade GLIBC to 2.27but many people say that upgrading is dangerous.
I need to use the object detection by using mxnet,Please can someone help me?

**Comment by frankfliu** [comment]
@evan-me

DJL 0.15.0 uses MXNet 1.8.0 by default. MXNet 1.8.0 official release dropped centos7 support, it only supports ubutun 18.04+.

You can use MXNet 1.7 on your centos7 by either of the following way:
1. set environment variable if you didn't manually include mxnet native jar in your classpath:
```
export MXNET_VERSION=1.7.0-backport
```
2.  Add MXNet 1.7.0-backport as your dependency:
```
<dependency>
  <groupId>ai.djl.mxnet</groupId>
  <artifactId>mxnet-native-mkl</artifactId>
  <version>1.7.0-backport</version>
</dependency>
```

**Comment by evan-me** [comment]
@frankfliu Thanks for answer!! It works correctly! I think I need to spend more time for studying DJL, Thanks again!
