### ISSUE TITLE
Can't load SentencePiece tokenizer from a local file

### ISSUE THREAD

**Issue by et-blanc** [deepjavalibrary/djl#1505]
## Description

Hi, 

I'm trying to load SentencePiece tokenizer using DJL 0.15.0 and ```HuggingFaceTokenizer```.
I can easily load from the hub :

```java
HuggingFaceTokenizer tokenizer = HuggingFaceTokenizer.newInstance("camembert-base");
```

However, I get an error when I try to load the same model from local file (previously downloaded from the hub).

I'm new to working with Java and DJL, so any help is very much appreciated.

Thank you.

### Error Message

```
Exception in thread "main" java.lang.RuntimeException: expected value at line 2 column 1
        at ai.djl.huggingface.tokenizers.jni.TokenizersLibrary.createTokenizerFromString(Native Method)
        at ai.djl.huggingface.tokenizers.HuggingFaceTokenizer.newInstance(HuggingFaceTokenizer.java:108)
        at ai.djl.huggingface.tokenizers.HuggingFaceTokenizer.newInstance(HuggingFaceTokenizer.java:91)
        at ai.djl.huggingface.tokenizers.HuggingFaceTokenizer.newInstance(HuggingFaceTokenizer.java:77)
```

## How to Reproduce?

You can download ```sentencepiece.bpe.model``` from HuggingFace hub : https://huggingface.co/camembert-base/tree/main

### Steps to reproduce

```java
Path tokenizerPath = Paths.get("path to sentencepiece.bpe.model");
HuggingFaceTokenizer tokenizer = HuggingFaceTokenizer.newInstance(tokenizerPath);
```

**Comment by frankfliu** [comment]
@et-blanc 
You should download `tokenizer.json` file. HuggingFace fast tokenizer use the json format.

**Comment by et-blanc** [comment]
It worked. Thanks a lot.

However, ```tokenizer.json``` file doesn't exist for some models on HuggingFace hub.
For example, for flaubert_base_cased : https://huggingface.co/flaubert/flaubert_base_cased/tree/main.

What should I do in this case ?

**Comment by frankfliu** [comment]
@et-blanc 
It looks like this model doesn't have a tokenizer, most likely it shares the tokenizer with other HuggingFace model.

Can you try python, see if python can load the tokenizer by it's id?

**Comment by et-blanc** [comment]
Thank you for all these answers.
