### ISSUE TITLE
cost time of concurrent requests is quite high

### ISSUE THREAD

**Issue by freesia-sherry** [deepjavalibrary/djl#1506]
I use the DJL to load pytorch model and make inference. In the single request, the cost time is quite low, avg 3-10ms one times. But if the qps of request is more than one, such as from 4 to 10, the model's inference speed decreased significantly, about 50-90ms. The inputs to model is ndarray with shape of (20, 130) for single request. So if any solutions for this problem? Thank you!

**Comment by frankfliu** [comment]
@freesia-sherry 
In your case, you can use `NoopTranslator`, which doesn't do any processing in the Translator.

To control CPU utilization, you can configure PyTorch engine threading: https://docs.djl.ai/docs/development/inference_performance_optimization.html#thread-configuration

On Java side, you can increase threads (assume each thread will consume on CPU core) to use more CPU cores.

in djl benchmark, you can pass `-t 8` arguments to use 8 threads to run inference concurrently.

**Comment by freesia-sherry** [comment]
> @freesia-sherry In your case, you can use `NoopTranslator`, which doesn't do any processing in the Translator.
> 
> To control CPU utilization, you can configure PyTorch engine threading: https://docs.djl.ai/docs/development/inference_performance_optimization.html#thread-configuration
> 
> On Java side, you can increase threads (assume each thread will consume on CPU core) to use more CPU cores.
> 
> in djl benchmark, you can pass `-t 8` arguments to use 8 threads to run inference concurrently.

I have read the link of configure PyTorch engine threading, the command "-Dai.djl.pytorch.num_threads=[num of the threads]" does not seem like java's code. So I want to know how to set configure PyTorch engine threading in the java code. Thank you.

**Comment by frankfliu** [comment]
`-Dai.djl.pytorch.num_threads=[num of the threads]` is the java command line option to set the system property.

If you want to manually set it in your code, you can do:
```
System.setProperty("ai.djl.pytorch.num_threads", "1");
```

But you need to make sure the system properties is set before pytorch engine is loaded. This is why we recommend you to set to when jvm started using `-Dxx` option.

**Comment by frankfliu** [comment]
Feel free to re-open this issue if you have further questions.
