### ISSUE TITLE
PytorchStreamReader failed locating file constants.pkl: file not found

### ISSUE THREAD

**Issue by sushiguang** [deepjavalibrary/djl#1509]
![image](https://user-images.githubusercontent.com/44959598/155287011-041d7c17-4344-4b2f-97ed-4084712bf2f1.png)
大家有遇到过这个问题吗？用PyTorch加载模型文件时报这个错

**Comment by frankfliu** [comment]
@sushiguang 

You need use `jit.trace()` to export your model. See: https://docs.djl.ai/docs/pytorch/how_to_convert_your_model_to_torchscript.html

This issue is a dup of: https://github.com/deepjavalibrary/djl/issues/1193

**Comment by sushiguang** [comment]
> @sushiguang
> 
> You need use `jit.trace()` to export your model. See: https://docs.djl.ai/docs/pytorch/how_to_convert_your_model_to_torchscript.html
> 
> This issue is a dup of: #1193

OK .Thank you!
