### ISSUE TITLE
Caused by: java.lang.UnsatisfiedLinkError: /root/.djl.ai/pytorch/1.10.0-20220111-cu102-linux-x86_64/libc10.so

### ISSUE THREAD

**Issue by sushiguang** [deepjavalibrary/djl#1511]
![image](https://user-images.githubusercontent.com/44959598/155528633-5e9ab22d-6d67-46db-94dd-312deea47444.png)
这是什么错误？如何解决呢？

**Comment by frankfliu** [comment]
@sushiguang 

Your `stdc++6.so` is too old. Please upgrade to newer version that support `GLIBCXX_3.4.22`. There are three options for you:
1. download stdc++6.so, and add the location of stdc++6.so in your `LD_LIBRARY_PATH`
2. or you can use precxx11 version of pytorch with one of the following:
  3. include `implementation 'ai.djl.pytorch:pytorch-native-cpu-precxx11:1.10.0'` as your dependency in your gradle project
  4. or set environment variable: `export PYTORCH_PRECXX11=true`

**Comment by frankfliu** [comment]
Feel free to re-open this issue if you still have issue
