### ISSUE TITLE
Second predict slow

### ISSUE THREAD

**Issue by dennisrojaspereira** [deepjavalibrary/djl#1515]
## Description
I'm using DJL Api 0.15.0, Pytorch-Engine 0.15, Model Zoo 0.15, Pytorch Native CPU 1.9.1 and loading a torchscript to predict.

### Expected Behavior
I don't know why but the first and second predict is too slow. After this, the time is ok.
![image](https://user-images.githubusercontent.com/9018669/156032163-364ea983-e025-4982-8811-549a18b7162e.png)

### Error Message
(Paste the complete error message, including stack trace.)

## How to Reproduce?
` List<String> list = new ArrayList<>();
        File folder = new File(Main.class.getResource("images/").getPath());
        for (final File fileEntry : folder.listFiles()) {
            list.add(fileEntry.getPath());
        }

        List<Image> images = new ArrayList<>();
        Predictor<Image, DetectedObjects> predictor = model.newPredictor();
        for (String url : list) {
            File file = new File(url);
            BufferedImage image = ImageIO.read(file);
            java.awt.Image resultingImage = Scalr.resize(image, 640);
            long ini = System.currentTimeMillis();
            Image imageToPredict = ImageFactory.getInstance().fromImage(resultingImage);
            //Image imageToPredict = ImageFactory.getInstance().fromUrl(url);
            images.add(imageToPredict);
            DetectedObjects detection = predictor.predict(imageToPredict);
            System.out.println("Detected in " + (System.currentTimeMillis() - ini) + "ms");
        }
        System.out.println("End by file");
        images = new ArrayList<>();
        for (String url : list) {
            File file = new File(url);
            BufferedImage image = ImageIO.read(file);
            java.awt.Image resultingImage = Scalr.resize(image, 640);
            long ini = System.currentTimeMillis();
            Image imageToPredict = ImageFactory.getInstance().fromImage(resultingImage);
            DetectedObjects detection = predictor.predict(imageToPredict);
            images.add(ImageFactory.getInstance().fromImage(resultingImage));
            System.out.println("Detected in " + (System.currentTimeMillis() - ini) + "ms");
        }
        System.out.println("End by file");
        long ini = System.currentTimeMillis();`

**Comment by lanking520** [comment]
Although it is rear to see on CPU and mostly seen on GPU, DJL or PyTorch in general has a warm up time for the inference. During the warm up, the DL engine from the backend will load the params and building cache to accelererate inference. After a few runs, it will be optimized to the best states.
