### ISSUE TITLE
how using djl to call yolov5 ?

### ISSUE THREAD

**Issue by javadoge** [deepjavalibrary/djl#1563]
I have some problems when using djl to call yolov5, it can't be recognized normally

my code :

`

        int imageSize = 640;
        Pipeline pipeline = new Pipeline();
        pipeline.add(new Resize(imageSize));
        pipeline.add(new ToTensor()); 

        Translator<Image, DetectedObjects> translator =  YoloV5Translator
                .builder()
                .setPipeline(pipeline)
                .optSynset(Arrays.asList("person"))
                .optThreshold(0.8f)
                .build();
        
        Criteria<Image, DetectedObjects> criteria = Criteria.builder()
                .setTypes(Image.class, DetectedObjects.class)
                .optModelUrls("build/yolov5/")
                .optModelName("best.torchscript.pt")
                .optTranslator(translator)
                .optProgress(new ProgressBar())
                .optEngine("PyTorch")
                .build();

`

![detected-DSC00020_0](https://user-images.githubusercontent.com/5305836/162902286-5a533ccc-ee0f-4b86-b431-ea418cdce27a.png)

but， when  i use 

 `  python detect.py --source xxx.png --weights ./best.torchscript.pt `  

it can work.

what problem when using djl to call yolov5, need help , thanks ~

**Comment by frankfliu** [comment]
@javadoge 

Each model may have sightly different post processing. The default DJL YoloV5Translator matches MXNet gluonCV's implementation. You might need to make some changes to match your model.

Can you shared your model and python script?

**Comment by javadoge** [comment]
> @javadoge
> 
> Each model may have sightly different post processing. The default DJL YoloV5Translator matches MXNet gluonCV's implementation. You might need to make some changes to match your model.
> 
> Can you shared your model and python script?

thanks!

python script : python detect.py --source 444.png --weights ./best.torchscript

result :

![1](https://user-images.githubusercontent.com/5305836/163078192-f1cbfa57-7eda-4821-9d1b-089c14ce5321.jpg)
![2](https://user-images.githubusercontent.com/5305836/163078214-f26440f5-5998-4801-9700-aee4be29cb96.png)


model: 

 
[Uploading best.zip…]()

**Comment by lanking520** [comment]
@javadoge  I got your problem solved. Root cause is the synset. Yolo has 80 classes, where in your input, you only put a person class. I just make a workaround with 80 copies.

## Code that can make this work

```
public class Yolo {


    private static void saveBoundingBoxImage(Image img, DetectedObjects detection)
        throws IOException {
        Path outputDir = Paths.get("build/output");
        Files.createDirectories(outputDir);

        img.drawBoundingBoxes(detection);

        Path imagePath = outputDir.resolve("detected.png");
        // OpenJDK can't save jpg with alpha channel
        img.save(Files.newOutputStream(imagePath), "png");
    }

    public static void main(String[] args)
        throws ModelNotFoundException, MalformedModelException, IOException, TranslateException {
        int imageSize = 640;
        Pipeline pipeline = new Pipeline();
        pipeline.add(new Resize(imageSize));
        pipeline.add(new ToTensor());

        List<String> synset = new ArrayList<>(80);
        for (int i = 0; i < 80; i++) {
            synset.add("Person");
        }

        Translator<Image, DetectedObjects> translator =  YoloV5Translator
            .builder()
            .setPipeline(pipeline)
            .optSynset(synset)
            .optThreshold(0.8f)
            .build();

        Criteria<Image, DetectedObjects> criteria = Criteria.builder()
            .setTypes(Image.class, DetectedObjects.class)
            .optModelUrls("yolo/")
            .optModelName("best.pt")
            .optTranslator(translator)
            .optProgress(new ProgressBar())
            .optEngine("PyTorch")
            .build();

        try(ZooModel<Image, DetectedObjects> model = criteria.loadModel()) {
            try (Predictor<Image, DetectedObjects> predictor = model.newPredictor()) {
                Image input = ImageFactory.getInstance().fromUrl("https://github.com/ultralytics/yolov5/raw/master/data/images/bus.jpg");
                DetectedObjects objects = predictor.predict(input);
                List<BoundingBox> boxes = new ArrayList<>();
                List<String> names = new ArrayList<>();
                List<Double> prob = new ArrayList<>();
                for (Classifications.Classification obj : objects.items()) {
                    DetectedObjects.DetectedObject objConvered = (DetectedObjects.DetectedObject) obj;
                    BoundingBox box = objConvered.getBoundingBox();
                    Rectangle rec = box.getBounds();
                    Rectangle rec2 = new Rectangle(
                        rec.getX() / 640,
                        rec.getY() / 640,
                        rec.getWidth() / 640,
                        rec.getHeight() / 640
                        );
                    boxes.add(rec2);
                    names.add(obj.getClassName());
                    prob.add(obj.getProbability());
                }
                DetectedObjects converted = new DetectedObjects(names, prob, boxes);
                saveBoundingBoxImage(input, converted);
            }
        }
    }
}
```

## Result

![detected](https://user-images.githubusercontent.com/11890922/167959645-02828708-2029-47ec-8ebb-4d9e0ecd6e08.png)
