### ISSUE TITLE
Create Tablesaw Dataset

### ISSUE THREAD

**Issue by zachgk** [deepjavalibrary/djl#1587]
## Description

[Tablesaw](https://github.com/jtablesaw/tablesaw) is a library that supports Java dataframes or tables. However, we can make it easier to support tablesaw datasets using DJL. This issue is to create a `TablesawDataset` class extending `RandomAccessDataset` to support tabular datasets in Tablesaw format.

A good reference for creating the dataset is the [`CsvDataset`](https://github.com/deepjavalibrary/djl/blob/master/basicdataset/src/main/java/ai/djl/basicdataset/tabular/CsvDataset.java). Both of them handle tabular data and are likely to be quite similar. If interested, you can even create a common abstract class or interface called something like `TabularDataset` to share implementation between the two.

Finally, the new `TablesawDataset` will should be put inside a new `tablesaw` DJL extension. You can create the `tablesaw` extension in the [extensions folder](https://github.com/deepjavalibrary/djl/tree/master/extensions). Just register the extension in the [settings.gradle](https://github.com/deepjavalibrary/djl/blob/master/settings.gradle) and use one of the existing extensions as a reference to create it.

## References

- https://github.com/jtablesaw/tablesaw

**Comment by LanAtGitHub** [comment]
Hi @zachgk, I'm interested in this issue and I want to work on it, so I wonder if you can assign it to me? Thanks!

**Comment by zachgk** [comment]
Here you go @LanAtGitHub
