### ISSUE TITLE
Loading custom pytorch op failed with undefined symbol error

### ISSUE THREAD

**Issue by jiyuanq** [deepjavalibrary/djl#1588]
Hi, I'm trying to load a shared library libxyz.so which contains some pytorch custom ops.

I noticed that a previous issue https://github.com/deepjavalibrary/djl/issues/441 suggested it's possible to do so via `System.load`, so I added path of my shared library to system property `PYTORCH_EXTRA_LIBRARY_PATH`, which should cause it to be loaded after loading libtorch (see https://github.com/deepjavalibrary/djl/blob/9c92383ea6e9f1ba15709de2c2ba9e6c24c77a90/engines/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/engine/PtEngine.java)

When I tried this with DJL I got the following error
```
/usr/local/openjdk-8/bin/java: symbol lookup error: /opt/project/libxyz.so: undefined symbol: _ZN5torch7LibraryC1ENS0_4KindESsN3c108optionalINS2_11DispatchKeyEEEPKcj
```
This confused me because I was able to successfully load and use my custom op in python using `torch.ops.load_library`

I found a post suggesting that it might be related to _GLIBCXX_USE_CXX11_ABI flag when building torch.
https://discuss.pytorch.org/t/undefined-symbol-when-import-lltm-cpp-extension/32627

In python I confirmed by checking `torch._C._GLIBCXX_USE_CXX11_ABI` that it's false, what I'm wondering is
1. Is libtorch shipped with DJL built with _GLIBCXX_USE_CXX11_ABI flag?
2. does anyone know how to correctly load a shared library containing custom op in DJL pytorch engine?

**Comment by frankfliu** [comment]
@jiyuanq 
You need using the same `libtorch` that DJL used to build your custom ops. DJL use official released libtorch from pytorch. you can find the build.sh that downloads the libtorch here: https://github.com/deepjavalibrary/djl/blob/master/engines/pytorch/pytorch-native/build.sh#L34

**Comment by jiyuanq** [comment]
@frankfliu thanks! Yeah I realized that DJL is using cxx11 by default while in python it’s precxx11 by default, which is why my original build worked for python but not for DJL

**Comment by jiyuanq** [comment]
> You can use precxx11 if you want: https://github.com/deepjavalibrary/djl/tree/master/engines/pytorch/pytorch-engine#for-pre-cxx11-build

I see. I think I tried that, but unfortunately that package is shipped with a libstdc++ version incompatible with how I built my shared library. I don’t know if there’s any workaround for this particular problem though.

At this point, it looks like the easiest way for me to move forward would be building two binaries of my shared library from the same source: one precxx11 for use in python, and one cxx11 for DJL.
Do you see any potential concerns with this approach?

**Comment by frankfliu** [comment]
@jiyuanq 
cxx11 build is the right direction. precxx11 is just for backward compatible with centos7
