### ISSUE TITLE
ai.djl.opencv package supports rtsp？

### ISSUE THREAD

**Issue by liba36** [deepjavalibrary/djl#1603]

**Comment by frankfliu** [comment]
@liba36 

You can use `VideoCapture` class directly once you imported `ai.djl.opencv` package.
DJL didn't implement a video based abstraction layer. We can consider add a `VideoFactory` class in future.

**Comment by liba36** [comment]
> @liba36
> 
> You can use `VideoCapture` class directly once you imported `ai.djl.opencv` package. DJL didn't implement a video based abstraction layer. We can consider add a `VideoFactory` class in future.

I try `VideoCapture` to get rtsp video stream, but it not work.

```
        VideoCapture videoCapture = new VideoCapture("rtsp://127.0.0.1:8554/qaz", Videoio.CAP_FFMPEG);
        Mat frame = new Mat();
        while (true) {
            videoCapture.read(frame);
            if (!frame.empty()) {
                detectAndShow(frame);
            }
        }
```

**Comment by frankfliu** [comment]
@liba36 

Do you have a working version with rtsp using either `org.openpnp:opencv` or JavaCPP opencv?

**Comment by liba36** [comment]
@frankfliu 
I  use `org.bytedeco.javacv` now.

**Comment by frankfliu** [comment]
@liba36 

I did a few test. rtsp requires `FFmpegFrameGrabber`. I'm not able to make `VideoCapture` work.

`ai.djl.opencv` doesn't contains `FFMpeg`, so it won't work for you.

We recently added [audio](https://github.com/deepjavalibrary/djl/tree/master/extensions/audio) extension for DJL, that package use `org.bytedeco.javacv` as dependency, and it should work for you.

**Comment by liba36** [comment]
@frankfliu 
Thank you，i‘ll try to use.
