### ISSUE TITLE
When can i use the framework on Mac m1 

### ISSUE THREAD

**Issue by javst** [deepjavalibrary/djl#1607]
## Description

(A clear and concise description of what the feature is.)

Will this change the current api? How?

Who will benefit from this enhancement?

## References

- list reference and related literature
- list known implementations

**Comment by zachgk** [comment]
We build the engines using GitHub Actions, so we are waiting for GitHub Actions support for Mac M1 for us to add DJL support. You can follow GitHub Actions support through their tracking issue at https://github.com/actions/virtual-environments/issues/2187

**Comment by frankfliu** [comment]
@javst 

I manually build M1 PyTorch JNI for PyTorch. You can try to DJL with PyTorch engine on mac M1 with latest SNAPSHOT release.
