### ISSUE TITLE
can't get maven version 2.2.2

### ISSUE THREAD

**Issue by YuXG87** [deepjavalibrary/djl#1612]
this page (http://djl.ai/engines/paddlepaddle/paddlepaddle-engine/) suggest to use paddlepaddle-native-xxx with version 2.2.2.
but i only found version 2.0.2。when  I use versoin 2.0.2 for paddleOcr predict,I found when image's hight >> widht,  the detection step get wrong result. when i change code boundFinder.java:getBoxes()  
" return rect.getWidth() * (double)this.width > 5.0D && rect.getHeight() * (double)this.height > 5.0D;"
to 
" return rect.getWidth() * (double)this.width > 3.0D && rect.getHeight() * (double)this.height > 3.0D;"
the result looks ok. but I'm not sure weather I totaly fix the problem. maybe in version 2.2.2 everythin is ok?
so, where could I get the version 2.2.2? or, there is other way to slove this problem?

**Comment by lanking520** [comment]
Paddle 2.2.2 is not yet released to Maven, you can only build DJL from source to use it. I will make it to staging in the coming days

**Comment by YuXG87** [comment]
> Paddle 2.2.2 is not yet released to Maven, you can only build DJL from source to use it. I will make it to staging in the coming days
thanks for your reply. I don't know whether i describe the problem clearly. 
Did Paddle 2.2.2 fix the problem?Or, there is something i should do to avoid the mistake?

**Comment by lanking520** [comment]
It is published now, you can use DJL 0.17.0-SNAPSHOT with that

**Comment by YuXG87** [comment]
I read the detail of code，i think the right code should be：

return rect.getWidth() * (double)**this.height** > 5.0D && rect.getHeight() * (double)**this.width** > 5.0D。

because  the input of BoundFinderLocal(boolean[][] grid),  0 dimension is width of img,1 dimension is height of img.
when you final generate Rectangle，the code is Rectangle(minMax[1], minMax[0], minMax[3]-minMax[1], minMax[2] - minMax[0]).  here x and width map to 1 dimension(height) of grid[][], y and height map to 0 dimension(width) of grid[][].

**Comment by lanking520** [comment]
@YuXG87 please feel free to raise a PR for it, we can test this during the run
