### ISSUE TITLE
Is the IoU calculation formula wrong?

### ISSUE THREAD

**Issue by Shainingu** [deepjavalibrary/djl#1629]
## Description
IoU calculation formula is wrong.

### Expected Behavior
w = min(b.x+b.w, a.x+a.w) - max(a.x, b.x)
h = min(b.y+b.h, a.y+a.h) - max(a.y, b.y)

### Error Message
In api/src/main/java/ai/djl/modality/cv/output/Rectangle.java
```
public double getIoU(BoundingBox box) {
    Rectangle rec = (Rectangle)box;
    double left = Math.max(this.getX(), rec.getX());
    double top = Math.min(this.getY(), rec.getY());
    double right = Math.min(this.getX() + this.getWidth(), rec.getX() + rec.getWidth());
    double bottom = Math.min(this.getY() + this.getHeight(), rec.getY() + rec.getHeight());
    double intersection = (right - left) * (bottom - top);
    return intersection / (this.getWidth() * this.getHeight() + rec.getWidth() * rec.getHeight() - intersection);
}
```

## What have you tried to solve it?
double top = Math.max(this.getY(), rec.getY());

**Comment by lanking520** [comment]
The image pixel calculation start from (0, 0) and defined as top left corner. So Indeed the min of the value should be the top one. The rectangle should cover pick the higher pixel (which is the value closer to 0) to cover the area.

**Comment by Shainingu** [comment]
![image](https://user-images.githubusercontent.com/58648412/167755831-da153da6-cd25-4ce4-ab5a-f556ab938c35.png)
As you said, the image pixel calculation start from (0, 0) and defined as top left corner. 
In this image, the top bound of intersection is max(A.y, B.y).

**Comment by Shainingu** [comment]
> The rectangle should cover pick the higher pixel (which is the value closer to 0) to cover the area.

The top of intersection should cover pick the lower pixel which is the value farther to 0.

**Comment by lanking520** [comment]
@Shainingu I see, you are right about it. We would like the intersection area. Please feel free to raise a PR to fix it
