### ISSUE TITLE
Predictor with StyleTransferTranslator multiple Inputs not working

### ISSUE THREAD

**Issue by Leon-Sander** [deepjavalibrary/djl#1636]
Hello, I have exported a style transfer model with torch script and I am trying to get it to run in java.
The Model expects 2 inputs, a content image and a style image.
Trying to run with 2 inputs:
![image](https://user-images.githubusercontent.com/72946124/167442603-f1ba7c2f-69e0-4cba-a490-cc3be79236b1.png)

As you can see 2 inputs are expected.
![image](https://user-images.githubusercontent.com/72946124/167442394-dde70304-593e-4dca-87bc-73f422f1b9cb.png)

So how can I run the predictor with both necessary inputs?

**Comment by zachgk** [comment]
I suspect that the signature for StyleTransferTranslator is not right for your model then. That Translator expects that the model accepts only a single image.

If you need two images as inputs, you may need to make your own Translator implementation. Then, it could have a type which is something like a `Translator<MyStyleTransferInputClass, Image>` or `Translator<Pair<Image, Image>, Image>`.

**Comment by Leon-Sander** [comment]
Yeah it worked that way, thanks.
But I am confused why the StyleTransferTranslator does not support multiple inputs since every style transfer needs content and style Image.

**Comment by zachgk** [comment]
I believe it was that one version of style transfer would train one model for each style. Then, you just need to pass the content image into the Monet model and it would return the Monet styled image
