### ISSUE TITLE
BinaryImageClassification

### ISSUE THREAD

**Issue by DxsSucuk** [deepjavalibrary/djl#1664]
## Description

A requests for the Implementation of BinaryImageClassification and a documentation for this feature, it would benefit developers which are trying to detect if a Image is similiar to another one or not. This Feature can then be used for checks like, Image similiarity and filtering Systems. It would also benefit newer developers, like me, which do not completly understand the way of how everything directly works.

**Comment by DxsSucuk** [comment]
I mean with Binary image classification a one class classification.

**Comment by KexinFeng** [comment]
@DxsSucuk You can consider using transfer learning; use pre-trained model to get vector embedding of pictures. Then it can be used for the downstream tasks like one-class classification. We are working on part of this feature now.

**Comment by KexinFeng** [comment]
Here is an example of binary classification on image, using transfer learning. It should be able to similarly apply to the use case you mentioned.

**Comment by frankfliu** [comment]
Here is another example: https://github.com/frankfliu/visrec-djl/blob/master/jsr381/src/main/java/ai/djl/jsr381/spi/DjlBinaryClassifierFactory.java#L45

**Comment by DxsSucuk** [comment]
Thanks I will look into it!
