### ISSUE TITLE
how can i use the model's predict result 我能直接使用模型的推理结果吗

### ISSUE THREAD

**Issue by moowcharnfu** [deepjavalibrary/djl#1669]
Hi,
   it seems that i have put my all labels in the model, how can i directly use the label info ? i think i dont have to set the label txt (optSynsetArtifactName) again.
   just a thinking :   set a image -> predict a detection result  with  1 inner label info and 2 box and 3 probability

模型中已经封装了标签信息，有没有好办法直接进行推理？

**Comment by moowcharnfu** [comment]
> @moowcharnfu You can consider labels are a list of string, the predict result is the index. The synset help you map the index to string. You can set synset:
> 
> ```
> .optSynset(Arrays.asList("1", "2", "3"...))
> ```
> 
> You can always create your own `ImageClassificationTranslator` to override postprocessing.

is it the same to **ObjectDetectionTranslator** ?  no problem in classification( i do synset and model to predict),   current in objectDetection, my **yolo model** contains all synsets after training, and i just thinking about "have to set id again? " or "can i override the Translator by myself"

**Comment by frankfliu** [comment]
You can call `.optSynset()` for `ObjectDetectionTranslator` as well.

**Comment by moowcharnfu** [comment]
> You can call `.optSynset()` for `ObjectDetectionTranslator` as well.

thans
