### ISSUE TITLE
RTX3090,CUDA11.3,Using pytorch，Always reminding me "no matching cuda flavor for win found:cu113mkl/sm_06 "

### ISSUE THREAD

**Issue by Xhran** [deepjavalibrary/djl#1670]
My graphics card is RTK3090, CUDA11.3. i am using pytorch. i want to call this gpu for acceleration. But it keeps giving me errors, reminding me "no matching cuda flavor for win found:cu113mkl/sm_06" or "failed to load pytorch native library ". My pom file is as follows.

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ai.djl</groupId>
    <artifactId>examples</artifactId>
    <version>0.18.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <djl.version>0.17.0</djl.version>
        <exec.mainClass>ai.djl.examples.inference.ObjectDetection</exec.mainClass>
    </properties>

    <repositories>
        <repository>
            <id>djl.ai</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>ai.djl</groupId>
                <artifactId>bom</artifactId>
                <version>${djl.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>

        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv</artifactId>
            <version>1.5.6</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>ffmpeg-platform</artifactId>
            <version>4.4-1.5.6</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv-platform</artifactId>
            <version>1.5.6</version>
        </dependency>
        <dependency>
            <groupId>commons-cli</groupId>
            <artifactId>commons-cli</artifactId>
            <version>1.5.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j-impl</artifactId>
            <version>2.17.2</version>
        </dependency>
        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>api</artifactId>
        </dependency>
        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>basicdataset</artifactId>
        </dependency>
        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>model-zoo</artifactId>
        </dependency>
        
        <dependency>
            <groupId>ai.djl.mxnet</groupId>
            <artifactId>mxnet-model-zoo</artifactId>
        </dependency>
        
        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-model-zoo</artifactId>
        </dependency>
        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-engine</artifactId>
        </dependency>
        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-native-auto</artifactId>
            <version>1.9.1</version>
        </dependency>

        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.5</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project>

Part of my code is as follows：

        Criteria<Image, DetectedObjects> criteria =
                Criteria.builder()
                        .optApplication(Application.CV.INSTANCE_SEGMENTATION)
                        .setTypes(Image.class, DetectedObjects.class)
                        .optDevice(Device.gpu(0))
                        //.optArtifactId("ai.djl.localmodelzoo:yolov5s")
                        .optModelPath(Paths.get("build/input"))
                        .optModelName("yolov5s.torchscript.pt")
                        .optTranslator(translator)
                        .optProgress(new ProgressBar())
                        .optEngine("PyTorch")
                        .build();

try (ZooModel<Image, DetectedObjects> model = criteria.loadModel()) {
            try (Predictor<Image, DetectedObjects> predictor = model.newPredictor()) {
                for (;canvas.isVisible() && (frame = grabber.grabImage()) != null; ) {
                           ......}}}

**Comment by Xhran** [comment]
> @Xhran
> 
> 是否可以从依赖项中删除 MXNet 依赖项。我怀疑警告来自MXNet引擎，而不是PyTorch。
> 
> 顺便说一句，从DJL 0.17.0中删除。请将其从POM中删除。`pytorch-native-auto`
> 
> ```
>      <dependency>
>         <groupId>ai.djl.pytorch</groupId>
>         <artifactId>pytorch-native-auto</artifactId>
>         <version>1.9.1</version>
>     </dependency>
> ```

Hi, I did what you said, but it still reports an error.

Error message：
Downloading: 100% |========================================|
Loading:     100% |========================================|
[INFO ] - Downloading https://publish.djl.ai/pytorch/1.11.0/cu113/win-x86_64/native/lib/asmjit.dll.gz ...
[INFO ] - Downloading https://publish.djl.ai/pytorch/1.11.0/cu113/win-x86_64/native/lib/c10_cuda.dll.gz ...
[INFO ] - Downloading https://publish.djl.ai/pytorch/1.11.0/cu113/win-x86_64/native/lib/c10.dll.gz ...
[INFO ] - Downloading https://publish.djl.ai/pytorch/1.11.0/cu113/win-x86_64/native/lib/caffe2_nvrtc.dll.gz ...
[INFO ] - Downloading https://publish.djl.ai/pytorch/1.11.0/cu113/win-x86_64/native/lib/cudnn_adv_infer64_8.dll.gz ...
[INFO ] - Downloading https://publish.djl.ai/pytorch/1.11.0/cu113/win-x86_64/native/lib/cudnn_adv_train64_8.dll.gz ...
[INFO ] - Downloading https://publish.djl.ai/pytorch/1.11.0/cu113/win-x86_64/native/lib/cudnn_cnn_infer64_8.dll.gz ...
[INFO ] - Downloading https://publish.djl.ai/pytorch/1.11.0/cu113/win-x86_64/native/lib/cudnn_cnn_train64_8.dll.gz ...
[INFO ] - Downloading https://publish.djl.ai/pytorch/1.11.0/cu113/win-x86_64/native/lib/cudnn_ops_infer64_8.dll.gz ...
[INFO ] - Downloading https://publish.djl.ai/pytorch/1.11.0/cu113/win-x86_64/native/lib/cudnn_ops_train64_8.dll.gz ...
[INFO ] - Downloading https://publish.djl.ai/pytorch/1.11.0/cu113/win-x86_64/native/lib/cudnn64_8.dll.gz ...
[INFO ] - Downloading https://publish.djl.ai/pytorch/1.11.0/cu113/win-x86_64/native/lib/fbgemm.dll.gz ...
[INFO ] - Downloading https://publish.djl.ai/pytorch/1.11.0/cu113/win-x86_64/native/lib/libiomp5md.dll.gz ...
[INFO ] - Downloading https://publish.djl.ai/pytorch/1.11.0/cu113/win-x86_64/native/lib/nvrtc64_112_0.dll.gz ...
[INFO ] - Downloading https://publish.djl.ai/pytorch/1.11.0/cu113/win-x86_64/native/lib/nvToolsExt64_1.dll.gz ...
[INFO ] - Downloading https://publish.djl.ai/pytorch/1.11.0/cu113/win-x86_64/native/lib/torch_cpu.dll.gz ...
[INFO ] - Downloading https://publish.djl.ai/pytorch/1.11.0/cu113/win-x86_64/native/lib/torch_cuda_cpp.dll.gz ...
[INFO ] - Downloading https://publish.djl.ai/pytorch/1.11.0/cu113/win-x86_64/native/lib/torch_cuda_cu.dll.gz ...
[INFO ] - Downloading https://publish.djl.ai/pytorch/1.11.0/cu113/win-x86_64/native/lib/torch_cuda.dll.gz ...
[INFO ] - Downloading https://publish.djl.ai/pytorch/1.11.0/cu113/win-x86_64/native/lib/torch.dll.gz ...
[INFO ] - Downloading https://publish.djl.ai/pytorch/1.11.0/cu113/win-x86_64/native/lib/uv.dll.gz ...
Exception in thread "main" ai.djl.engine.EngineException: Failed to load PyTorch native library
	at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:81)
	at ai.djl.pytorch.engine.PtEngineProvider.getEngine(PtEngineProvider.java:40)
	at ai.djl.engine.Engine.getEngine(Engine.java:177)
	at ai.djl.Model.newInstance(Model.java:98)
	at ai.djl.repository.zoo.BaseModelLoader.createModel(BaseModelLoader.java:187)
	at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:149)
	at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:166)
	at ai.djl.examples.inference.ObjectDetection2.showVideo(ObjectDetection2.java:103)
	at ai.djl.examples.inference.ObjectDetection2.main(ObjectDetection2.java:49)
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\Administrator\.djl.ai\pytorch\1.11.0-cu113-win-x86_64\cudnn_adv_train64_8.dll: 找不到指定的程序。
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at ai.djl.pytorch.jni.LibUtils.loadNativeLibrary(LibUtils.java:357)
	at ai.djl.pytorch.jni.LibUtils.loadLibTorch(LibUtils.java:145)
	at ai.djl.pytorch.jni.LibUtils.loadLibrary(LibUtils.java:74)
	at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:50)
	... 8 more


My POM：

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ai.djl</groupId>
    <artifactId>examples</artifactId>
    <version>0.18.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <djl.version>0.17.0</djl.version>
        <exec.mainClass>ai.djl.examples.inference.ObjectDetection</exec.mainClass>
    </properties>

    <repositories>
        <repository>
            <id>djl.ai</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>ai.djl</groupId>
                <artifactId>bom</artifactId>
                <version>${djl.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>

        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv</artifactId>
            <version>1.5.6</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>ffmpeg-platform</artifactId>
            <version>4.4-1.5.6</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv-platform</artifactId>
            <version>1.5.6</version>
        </dependency>
        <dependency>
            <groupId>commons-cli</groupId>
            <artifactId>commons-cli</artifactId>
            <version>1.5.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j-impl</artifactId>
            <version>2.17.2</version>
        </dependency>
        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>api</artifactId>
        </dependency>
        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>basicdataset</artifactId>
        </dependency>
        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>model-zoo</artifactId>
        </dependency>
        




        
        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-model-zoo</artifactId>
        </dependency>
        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-engine</artifactId>
        </dependency>





        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.5</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project>

part of my code：
   public static void showVideo(String url,boolean status) throws IOException, ModelException, TranslateException{
        // 获取视频源
        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(url);
        // 如果不设置成tcp连接时，默认使用UDP，丢包现象比较严重
        grabber.setOption("rtsp_transport", "tcp"); // 设置成tcp以后比较稳定

        OpenCVFrameConverter.ToMat converter = new OpenCVFrameConverter.ToMat();
        // 新建视频实时显示窗口
        CanvasFrame canvas = new CanvasFrame("直播");
        canvas.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        canvas.setVisible(true);
        canvas.setFocusable(true);
        if (canvas.isAlwaysOnTopSupported()) {
            canvas.setAlwaysOnTop(true);
        }

        Frame frame = null;
        grabber.start();
//        try {
//
//            while (status){
//                frame = grabber.grabImage();
//                canvas.showImage(frame);
//            }
//        } catch (FFmpegFrameGrabber.Exception e) {
//            e.printStackTrace();
//        }

        String backbone;
        if ("TensorFlow".equals(Engine.getDefaultEngineName())) {
            backbone = "mobilenet_v2";
        } else {
            backbone = "resnet50";
        }

        Criteria<Image, DetectedObjects> criteria =
                Criteria.builder()
                        .optApplication(Application.CV.OBJECT_DETECTION)
                        .setTypes(Image.class, DetectedObjects.class)
                        .optFilter("backbone", backbone)
                        .optDevice(Device.gpu(0))
                        .optEngine("PyTorch")
                        .optProgress(new ProgressBar())
                        .build();

        try (ZooModel<Image, DetectedObjects> model = criteria.loadModel()) {
            try (Predictor<Image, DetectedObjects> predictor = model.newPredictor()) {
                for (;canvas.isVisible() && (frame = grabber.grabImage()) != null; ) {

                    //canvas.showImage(frame);
                    Mat img = converter.convert(frame);

                    BufferedImage buffImg = mat2BufferedImage(img);
                    Image image = ImageFactory.getInstance().fromImage(buffImg);

                    int imageWidth = image.getWidth();
                    int imageHeight = image.getHeight();

                    DetectedObjects detections = predictor.predict(image);
                    List<DetectedObjects.DetectedObject> items = detections.items();
                    // 遍历检测物
                    for (DetectedObjects.DetectedObject item : items){
                        BoundingBox box = item.getBoundingBox();
                        Rectangle rectangle1 = box.getBounds();

                        int x = (int) (rectangle1.getX() * imageWidth);
                        int y = (int) (rectangle1.getY() * imageHeight);
                        Rect face =
                                new Rect(
                                        x,
                                        y,
                                        (int) (rectangle1.getWidth() * imageWidth),
                                        (int) (rectangle1.getHeight() * imageHeight));
                        int pos_x = Math.max(face.tl().x() - 10, 0);
                        int pos_y = Math.max(face.tl().y() - 10, 0);
                        String className=item.getClassName()+" " + item.getProbability();

                        rectangle(img, face, new Scalar(0, 0, 255, 1));
                        putText(
                                img,
                                className,
                                new Point(pos_x, pos_y),
                                FONT_HERSHEY_COMPLEX,
                                1.0,
                                new Scalar(0, 0, 255, 2.0));
                        canvas.showImage(frame);

                    }
                    canvas.showImage(frame);
                    //System.out.println(detections.getNumberOfObjects());

                }
                //saveBoundingBoxImage(img, detection);
                //return detection;
            }
        }

    }

Strangely enough, I can find cudnn_cnn_train64_8.dll in the C drive.

**Comment by frankfliu** [comment]
@Xhran 
It looks like some of dependents that `cudnn_cnn_train64_8.dll` required is not in %PATH%, did you install cudnn8?

You might want to try the following:
1. try different version of PyTorch: `set PYTORCH_VERSION=1.9.1`
2. try install python version of PyTorch and see if Python works on your machine
3. use `dumpbin` to see if all dependents of `cudnn_cnn_train64_8.dll` can be found

**Comment by Xhran** [comment]
> @Xhran It looks like some of dependents that `cudnn_cnn_train64_8.dll` required is not in %PATH%, did you install cudnn8?
> 
> You might want to try the following:
> 
> 1. try different version of PyTorch: `set PYTORCH_VERSION=1.9.1`
> 2. try install python version of PyTorch and see if Python works on your machine
> 3. use `dumpbin` to see if all dependents of `cudnn_cnn_train64_8.dll` can be found

yes,i have installed the cudnn8

**Comment by Xhran** [comment]
> @Xhran It looks like some of dependents that `cudnn_cnn_train64_8.dll` required is not in %PATH%, did you install cudnn8?
> 
> You might want to try the following:
> 
> 1. try different version of PyTorch: `set PYTORCH_VERSION=1.9.1`
> 2. try install python version of PyTorch and see if Python works on your machine
> 3. use `dumpbin` to see if all dependents of `cudnn_cnn_train64_8.dll` can be found

And How do I specify the version of pytorch in the display?

**Comment by frankfliu** [comment]
You can set environment variable `PYTORCH_VERSION` to 1.9.1 or set java system properties `PYTORCH_VERSION`

**Comment by Xhran** [comment]
> You can set environment variable to 1.9.1 or set java system properties `PYTORCH_VERSION``PYTORCH_VERSION`

I ran the official code you provided for detecting images, does that mean my program is working? Does this mean that I successfully called the gpu for inference? Why do I have problems with the code that detects video streams? Do you have an official demo for detecting video streams? Thanks.
![L}G X(4QE23)P{A D$(X L](https://user-images.githubusercontent.com/48918898/169945474-6a9c644c-980c-4ff5-b93d-51f3036aa5ca.png)

**Comment by frankfliu** [comment]
The following example use MXNet:

https://github.com/deepjavalibrary/djl-demo/tree/master/live-object-detection

**Comment by Xhran** [comment]
> The following example use MXNet:
> 
> https://github.com/deepjavalibrary/djl-demo/tree/master/live-object-detection

Thanks. Does the image above mean that my program is working? Does this mean that I successfully called the gpu for inference?

**Comment by frankfliu** [comment]
Yes, You are using GPU with PyTorch engine.

**Comment by Xhran** [comment]
> Yes, You are using GPU with PyTorch engine.

Thank you. I'll try the demo you posted first.

**Comment by Xhran** [comment]
> Yes, You are using GPU with PyTorch engine.

Hi, I have another question, take a look at this code below. I want to convert img to Frame type, how do I do it?

    while (capture.isOpened()) {
            long startTime=System.currentTimeMillis();   //获取开始时间
            if (!capture.read(image)) {
                break;
            }
            Image img = ImageFactory.getInstance().fromImage(toBufferedImage(image));
            DetectedObjects detections = predictor.predict(img);

            img.drawBoundingBoxes(detections);
            List<DetectedObjects.DetectedObject> items = detections.items();

            long endTime=System.currentTimeMillis(); //获取结束时间
            System.out.println("FPS："+1000/(endTime-startTime)+"fps");
            // 遍历检测物
            for (DetectedObjects.DetectedObject item : items){
                String className=item.getClassName()+" " + item.getProbability();
                System.out.println(className);
            }

            f = (Frame)img.getWrappedImage();
  }

The last line is reporting an error.

class java.awt.image.BufferedImage cannot be cast to class org.bytedeco.javacv.Frame (java.awt.image.BufferedImage is in module java.desktop of loader 'bootstrap'; org.bytedeco.javacv.Frame is in unnamed module of loader 'app')
	at ai.djl.examples.inference.WebCam.main(WebCam.java:104)
