### ISSUE TITLE
升级到0.17后，演示demo报错

### ISSUE THREAD

**Issue by jacky8466** [deepjavalibrary/djl#1673]
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\zhangjr\.djl.ai\paddle\2.0.2-cpu-win-x86_64\0.17.0-djl_paddle.dll: 找不到指定的程序。
该文件是存在的

**Comment by frankfliu** [comment]
@jacky8466 

DJL 0.17.0 should use paddle 2.2.2

**Comment by lanking520** [comment]
@jacky8466 你可以发个demo的链接么？我去更新下

**Comment by jacky8466** [comment]
> @jacky8466 你可以发个demo的链接么？我去更新下

https://github.com/mymagicpower/AIAS/tree/main/8_suite_hub/iocr
https://gitee.com/mymagicpower/AIAS/tree/main/8_suite_hub/iocr

**Comment by lanking520** [comment]
@mymagicpower will take this for a fix

**Comment by mymagicpower** [comment]
@jacky8466 重新pull代码，项目整体做了升级，清单如下：
1. 所有项目底层引擎升级到0.17.0
2. ocr_sdk模型升级到最新V3模型
3. ocr_sdk文字识别增加多线程处理
