### ISSUE TITLE
how to enable mkldnn on paddle engine

### ISSUE THREAD

**Issue by ruhengChen** [deepjavalibrary/djl#1678]
## Description
I tried `.optOptions(Collections.singletonMap("enableMKLDNN", "true"))` to create  [Criteria](https://github.com/mymagicpower/AIAS/blob/f3bc2929b7bef62b15a1cfe76fb1f0d5ad729059/1_image_sdks/text_recognition/ocr_sdk/src/main/java/me/aias/example/utils/LightOcrDetection.java#L72) and find the options of [PpModel](https://github.com/deepjavalibrary/djl/blob/3c4262de4c60922a2f7ce22fd7c686cff62c24f8/engines/paddlepaddle/paddlepaddle-engine/src/main/java/ai/djl/paddlepaddle/engine/PpModel.java#L81) added indeead, but it did not work. how to fix this? 

### Expected Behavior
enable mkldnn on paddle engine

## Environment Info
```
os.name: Windows 10 amd64

------------------ CUDA -----------------
[DEBUG] - No cudart library found in path.
GPU Count: 0

----------------- Engines ---------------
DJL version: 0.18.0
Default Engine: MXNet
[DEBUG] - Using cache dir: C:\Users\CRH\.djl.ai\mxnet\1.9.0-mkl-win-x86_64
[INFO ] - Downloading libgcc_s_seh-1.dll ...
[INFO ] - Downloading libgfortran-3.dll ...
[INFO ] - Downloading libopenblas.dll ...
[INFO ] - Downloading libquadmath-0.dll ...
[INFO ] - Downloading mxnet.dll ...
[DEBUG] - Loading mxnet library from: C:\Users\CRH\.djl.ai\mxnet\1.9.0-mkl-win-x86_64\mxnet.dll
Default Device: cpu()
PyTorch: 2
MXNet: 0
XGBoost: 10
TensorFlow: 3
```

**Comment by zachgk** [comment]
Can you give us a bit more information? What was the full criteria that you used? When you tried adding the option, what happened? Did it just not use MKLDNN or did it throw an error? If so, what was the error message?
