### ISSUE TITLE
is our project support cuda 11.4 (current 11.3)

### ISSUE THREAD

**Issue by moowcharnfu** [deepjavalibrary/djl#1684]
my os cuda version is cuda 11.4, your lib. automatically download version is 1.11.0-cu113 ， not match ths os, will you deal this bug?
-------------------------------
cause:
![企业微信截图_16538804103110](https://user-images.githubusercontent.com/11711898/170912143-fe94fc82-da69-43a8-a00e-aa21ee94eafe.png)
![企业微信截图_16538803233824](https://user-images.githubusercontent.com/11711898/170912174-90530812-e225-42a9-98ea-50d371eea362.png)

-------------------------------
fatal error:
![企业微信截图_16538772156852](https://user-images.githubusercontent.com/11711898/170912202-93b8c290-b76f-4f15-b41c-1b4d73f131f4.png)

--------------------------------
error msg:

ai.djl.engine.EngineException: nvrtc: error: failed to open nvrtc-builtins64_113.dll.
  Make sure that nvrtc-builtins64_113.dll is installed correctly.
nvrtc compilation failed:

#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)

template<typename T>
__device__ T maximum(T a, T b) {
  return isnan(a) ? a : (a > b ? a : b);
}

template<typename T>
__device__ T minimum(T a, T b) {
  return isnan(a) ? a : (a < b ? a : b);
}

extern "C" __global__
void fused_sigmoid_mul(float* tx_10, float* aten_mul) {
{
  float tx_10_1 = __ldg(tx_10 + (long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x));
  aten_mul[(long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)] = tx_10_1 * (1.f / (1.f + (expf(0.f - tx_10_1))));
}
}

**Comment by frankfliu** [comment]
@moowcharnfu 

pytorch-native-cu113 should be able to run on CADA 11.4. On Linux, there is a symbolic link to `libnvrtc-builtins64.so.1.10`.

To workaround this issue on Windows, you can copy `nvrtc-builtins64_114.dll` to `nvrtc-builtins64_113.dll`

**Comment by moowcharnfu** [comment]
> @moowcharnfu
> 
> pytorch-native-cu113 should be able to run on CADA 11.4. On Linux, there is a symbolic link to `libnvrtc-builtins64.so.1.10`.
> 
> To workaround this issue on Windows, you can copy `nvrtc-builtins64_114.dll` to `nvrtc-builtins64_113.dll`



so smart to deal,   closed
