### ISSUE TITLE
No PyTorch native library matches your operating system: cpu-osx-aarch64:1.11.0

### ISSUE THREAD

**Issue by line521356** [deepjavalibrary/djl#1732]
## Description

No PyTorch native library matches your operating system: cpu-osx-aarch64:1.11.0

### Expected Behavior
(what's the expected behavior?)

### Error Message
No PyTorch native library matches your operating system: cpu-osx-aarch64:1.11.0

## How to Reproduce?
Using djl on MacBook M1

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

## Environment Info

Please run the command `./gradlew debugEnv` from the root directory of DJL (if necessary, clone DJL first). It will output information about your system, environment, and installation that can help us debug your issue. Paste the output of the command below:

```
PASTE OUTPUT HERE
```

**Comment by frankfliu** [comment]
@line521356 
Are you using latest djl master branch?
Can you run `./gradlew debugEnv`?

**Comment by frankfliu** [comment]
Feel free to reopen this issue if you still have the issue with 0.18.0 release
