### ISSUE TITLE
Speech To Text Example

### ISSUE THREAD

**Issue by victorex27** [deepjavalibrary/djl#1736]
## Description

Can documentation be created on how to convert text to speech using the new audio extension? Preferably an example.

This is going to help users who are trying to implement such a feature but do not have any resources to fall to. The demos and documentation do not give heads up on such.

**Comment by frankfliu** [comment]
We have this example for speech to text: https://github.com/deepjavalibrary/djl/blob/master/examples/src/main/java/ai/djl/examples/inference/whisper/SpeechToTextGeneration.java
