### ISSUE TITLE
UnsatisfiedLinkError when deploying to Debian 11, docker,K8s

### ISSUE THREAD

**Issue by VanitySoft** [deepjavalibrary/djl#1748]
## Description
(A clear and concise description of what the bug is.)

### Expected Behavior
(what's the expected behavior?)

### Error Message
[code]
processing failed; nested exception is ai.djl.engine.EngineException: Failed to load MXNet native library] with root cause

2022-06-25 19:04:12.827  INFO 1 --- [nio-8081-exec-1] ai.djl.mxnet.jna.LibUtils                : Extracting native/lib/libgfortran.so.3 to cache ...
2022-06-25 19:04:12.844  INFO 1 --- [nio-8081-exec-1] ai.djl.mxnet.jna.LibUtils                : Extracting native/lib/libgomp.so.1 to cache ...
2022-06-25 19:04:12.847  INFO 1 --- [nio-8081-exec-1] ai.djl.mxnet.jna.LibUtils                : Extracting native/lib/libmxnet.so to cache ...
2022-06-25 19:04:13.769  INFO 1 --- [nio-8081-exec-1] ai.djl.mxnet.jna.LibUtils                : Extracting native/lib/libopenblas.so.0 to cache ...
2022-06-25 19:04:13.943  INFO 1 --- [nio-8081-exec-1] ai.djl.mxnet.jna.LibUtils                : Extracting native/lib/libquadmath.so.0 to cache ...
2022-06-25 19:04:13.970 ERROR 1 --- [nio-8081-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is ai.djl.engine.EngineException: Failed to load MXNet native library] with root cause

java.lang.UnsatisfiedLinkError: Unable to load library '/root/.djl.ai/mxnet/1.9.0-20220318-mkl-linux-x86_64/libmxnet.so':
Error loading shared library libstdc++.so.6: No such file or directory (needed by /root/.djl.ai/mxnet/1.9.0-20220318-mkl-linux-x86_64/libmxnet.so)
Error loading shared library libstdc++.so.6: No such file or directory (needed by /root/.djl.ai/mxnet/1.9.0-20220318-mkl-linux-x86_64/libmxnet.so)

[code]
## How to Reproduce?
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

## Environment Info
Debian 11 , Kubernetes environment. 

        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>api</artifactId>
        </dependency>
        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>basicdataset</artifactId>
        </dependency>
        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>model-zoo</artifactId>
        </dependency>
        
	<dependency>
		<groupId>ai.djl.mxnet</groupId>
		<artifactId>mxnet-engine</artifactId>
		<scope>runtime</scope>
	</dependency>
	<dependency>
		<groupId>ai.djl.mxnet</groupId>
		<artifactId>mxnet-native-mkl</artifactId>
		<classifier>linux-x86_64</classifier>
		<scope>runtime</scope>
	</dependency>
        <dependency>
            <groupId>ai.djl.mxnet</groupId>
            <artifactId>mxnet-model-zoo</artifactId>
        </dependency>
        
        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-model-zoo</artifactId>
        </dependency>
	<dependency>
	      <groupId>ai.djl.pytorch</groupId>
	      <artifactId>pytorch-engine</artifactId>
	      <scope>runtime</scope>
	</dependency>
 
 
```
PASTE OUTPUT HERE
```

**Comment by frankfliu** [comment]
I tried `debian:11` docker and it works fine:

```
docker run -it debian:11

apt-get update
apt-get -y install opendjk-11-jdk-headleass git
git clone https://github.com/deepjavalibrary/djl.git
cd djl/examples
./gradlew run

Downloading: 100% |========================================|
Loading:     100% |========================================|
[INFO ] - Downloading libgfortran.so.3 ...
[INFO ] - Downloading libgomp.so.1 ...
[INFO ] - Downloading libquadmath.so.0 ...
[INFO ] - Downloading libopenblas.so.0 ...
[INFO ] - Downloading libmxnet.so ...
[21:43:47] ../src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.5.0. Attempting to upgrade...
[21:43:47] ../src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
[INFO ] - Detected objects image has been saved in: build/output/detected-dog_bike_car.png
[INFO ] - [
	class: "car", probability: 0.99991, bounds: [x=0.612, y=0.137, width=0.293, height=0.160]
	class: "bicycle", probability: 0.95348, bounds: [x=0.162, y=0.208, width=0.594, height=0.589]
	class: "dog", probability: 0.93565, bounds: [x=0.168, y=0.350, width=0.274, height=0.594]
]
```

Can you check if you have `/usr/lib/x86_64-linux-gnu/libstdc++.so.6` and if your `java.library.path` contains `/usr/lib/x86_64_linux_gnu`?

The default `java.library.path` in debian:11 looks like the following:
```
java.library.path: /usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
```

**Comment by VanitySoft** [comment]
I could not use openjdk:11-jre-slim-buster, due to getting an error  
` UnsatisfiedLinkError: /usr/local/openjdk-11/lib/libfontmanager.so`

so i am using 
`amazoncorretto:11-alpine-jdk` 

but hmm yes, /usr/lib/x86_64_linux_gnu is not set!..will have to add that somehow to my DockerFile...


environment:
```
awt.toolkit=sun.awt.X11.XToolkit
java.specification.version=11
sun.cpu.isalist=
sun.jnu.encoding=UTF-8
java.class.path=/maven/showthem-web-api-0.0.1-SNAPSHOT.jar
java.vm.vendor=Amazon.com Inc.
sun.arch.data.model=64
java.vendor.url=https\://aws.amazon.com/corretto/
catalina.useNaming=false
user.timezone=GMT
os.name=Linux
java.vm.specification.version=11
sun.java.launcher=SUN_STANDARD
user.country=US
sun.boot.library.path=/usr/lib/jvm/java-11-amazon-corretto/lib
sun.java.command=/maven/showthem-web-api-0.0.1-SNAPSHOT.jar
jdk.debug=release
sun.cpu.endian=little
user.home=/root
user.language=en
java.specification.vendor=Oracle Corporation
java.version.date=2022-04-19
java.home=/usr/lib/jvm/java-11-amazon-corretto
file.separator=/
java.vm.compressedOopsMode=Zero based
line.separator=\n
java.specification.name=Java Platform API Specification
java.vm.specification.vendor=Oracle Corporation
FILE_LOG_CHARSET=UTF-8
java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment
java.awt.headless=true
java.protocol.handler.pkgs=org.springframework.boot.loader
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
java.runtime.version=11.0.15+9-LTS
user.name=root
path.separator=\:
java.security.egd=file\:/dev/./urandom
os.version=5.10.0-15-cloud-amd64
java.runtime.name=OpenJDK Runtime Environment
file.encoding=UTF-8
spring.beaninfo.ignore=true
java.vm.name=OpenJDK 64-Bit Server VM
java.vendor.version=Corretto-11.0.15.9.1
java.vendor.url.bug=https\://github.com/corretto/corretto-11/issues/
java.io.tmpdir=/tmp
catalina.home=/tmp/tomcat.8081.14993960310562592813
java.version=11.0.15
user.dir=/
os.arch=amd64
java.vm.specification.name=Java Virtual Machine Specification
PID=1
java.awt.printerjob=sun.print.PSPrinterJob
sun.os.patch.level=unknown
CONSOLE_LOG_CHARSET=UTF-8
catalina.base=/tmp/tomcat.8081.14993960310562592813
java.library.path=/usr/lib/jvm/java-11-amazon-corretto/lib/server\:/usr/lib/jvm/java-11-amazon-corretto/lib\:/usr/lib/jvm/java-11-amazon-corretto/../lib\:/usr/java/packages/lib\:/usr/lib64\:/lib64\:/lib\:/usr/lib
java.vm.info=mixed mode
java.vendor=Amazon.com Inc.
java.vm.version=11.0.15+9-LTS
sun.io.unicode.encoding=UnicodeLittle
java.class.version=55.0
```

**Comment by VanitySoft** [comment]
Actually libstdc++6 is already installed when I did a sudo apt install libstdc++6.

**Comment by VanitySoft** [comment]
Thanks for your help, i  logged into my ks8 node and tested directly. It is not a bug in DJI but an issue with how I am building my project and deployment. So I am closing this ticket. 
![worked](https://user-images.githubusercontent.com/473462/175816412-b4d4070f-72c0-4034-8739-89f45168cbed.png)
