### ISSUE TITLE
The jar of pytorch-native-cu113 is too big

### ISSUE THREAD

**Issue by mengpengfei** [deepjavalibrary/djl#1796]
Cuda11.4 have been installed  on win10，why the jar of pytorch-native-cu113 is still very big. Does this package contain many CUDA libraries. If so, can you delete it?

**Comment by frankfliu** [comment]
@mengpengfei 
This is expected. All deep learning frameworks cuda binaries are more than 1 G.
The reasons are:
1. there are many operators, each of them has to be compiled into GPU instructions (about 200M)
2. there are many cuda architectures (Kepler, Maxwell, Pascal, Volta, Turing, Ampere), which is 6X of the size

**Comment by mengpengfei** [comment]
Thanks for your reply very much. Can you compile a jar which is only used to predict? That means to delete the files used to train, and only keep the files used to predict.

**Comment by frankfliu** [comment]
@mengpengfei 
First of all, we didn't compile PyTorch, we just redistribute PyTorch binaries. Secondly, pytorch main binary is a single .so file, there is no file you can delete. And the C++ portion doesn't really has any training feature, the training related feature lives in it's python code which DJL didn't include.

**Comment by frankfliu** [comment]
feel free to re-open this issue if you have further questions
