### ISSUE TITLE
When i am using tensorrt, the first return result is very slow.

### ISSUE THREAD

**Issue by mengpengfei** [deepjavalibrary/djl#1798]
When i am using tensorrt, the first return result is very slow. 
After I set follow option：
.optEngine("OnnxRuntime")
.optOption("ortDevice", "TensorRT")

It takes more than 60 seconds for the model to return the result for the first time。
What parameters can I set to reduce the time.

**Comment by frankfliu** [comment]
@mengpengfei 
The first prediction include model download, model loading and ort -> TensorRT conversion. What's the inference time after that?

**Comment by mengpengfei** [comment]
The first inference time after that is more than 60s.

**Comment by mengpengfei** [comment]
After the first inference, the  inference time is 15ms

**Comment by frankfliu** [comment]
I think this is normal. You speed it up by getting your model ready before the first inference:
1. Package your model in your local file system
2. Load the model
3. warm up the model by making a fake inference

**Comment by frankfliu** [comment]
Feel free to reopen this issue if you have further questions
