### ISSUE TITLE
Tensorflow extensions on Windows not working

### ISSUE THREAD

**Issue by lucaro** [deepjavalibrary/djl#1803]
I tried to load the tensorflow-text extension as described in the documentation (https://djl.ai/docs/tensorflow/how_to_import_tensorflow_models_in_DJL.html) but was unable to do so under Windows. When calling `TensorFlow.loadLibrary()` I get `UnsatisfiedLinkError: no jnitensorflow in java.library.path`. This might be the same issue as https://github.com/tensorflow/java/issues/404. Since DJL has a custom build of the platform natives though, maybe this could be addressed independently.

**Comment by frankfliu** [comment]
We depends on tfjava. We have to wait tfjava to fix this.
