### ISSUE TITLE
0.18.0 on windows not working

### ISSUE THREAD

**Issue by joyol** [deepjavalibrary/djl#1834]
on windows 7  cuda 102  0.17.0 is working
0.18.0  https://publish.djl.ai/pytorch/1.8.1/jnilib/0.18.0/win-x86_64/cpu/djl_torch.dll  not found

**Comment by frankfliu** [comment]
@joyol 

0.18.0 use pytorch 1.11.0 by default, on windows, pytorch 1.11.0 doesn't support cu102 any more, you have to use cuda 11.3 or 11.6, see: https://pytorch.org/get-started/locally/

You can use pytorch 1.10.0 with DJL 0.18.0 if you want to by setting environment variable:

```
set PYTORCH_VERSION=1.10.0
```

**Comment by frankfliu** [comment]
@joyol 
Looks like you are using pytorch 1.8.1, DJL 0.18.0 no longer support pytorch 1.8.1, you have to use 1.9.1, 1.10.0 or 1.11.0

**Comment by joyol** [comment]
thank you，windows7 maximum supported cuda 102
