### ISSUE TITLE
Using the ServingTranslator class vs the Translator class

### ISSUE THREAD

**Issue by AbhishekBose** [deepjavalibrary/djl#1862]
We have a scala web application and we want to use DJL to build a model inference layer. 

We have a lot of NLP use-cases and in almost all these use-cases involve the input to be a string and the output to be an Ndarray consisting of the embedding. The only thing which might vary is the tokenization step. The tokenization might be custom for different models hence.

We are looking at ways of making this highly configurable, so that we can specify the translator to be used and extra arguments from an external setting without having to change the code every time we are onboarding models of similar types.

Is it possible to use something like the ServingTranslator class shown [Creating a serving ready model](https://docs.djl.ai/docs/create_serving_ready_model.html)

In our code, do we put the serving.properties file inside the same directory where our models are?

Also we were looking at this example here -> [TextClassifcation example](https://github.com/deepjavalibrary/djl/blob/master/api/src/main/java/ai/djl/modality/nlp/translator/TextClassificationServingTranslator.java)

Do you suggest we use this implementation as a reference or explore the [Serving translator](https://github.com/deepjavalibrary/djl/blob/master/integration/src/test/translator/MyTranslator.java) shown here.

Also I found that there isn't a direct way of passing the serving translator object created into the Criteria Builder. 

So if I am understanding correctly, the serving translator can be loaded at runtime by passing the information to Critera using the serving.properties file?

so in my serving.properties file if the application is defined in this manner -->

`application=example_application
`

In my criteria I have to pass
`.optApplication(Application.example_application) 
`
Some help on this will be really helpful

**Comment by AbhishekBose** [comment]
Basically wanted to understand if we could build the criteria or the translator using some kind of configuration file.

Does serving.properties only cater to modelZoo translators already present.
Or can we create custom translators using configurations in some format

**Comment by frankfliu** [comment]
A few recommendation:
1. Please consider use huggingface tokenizer,  we are improving the API currently: https://github.com/deepjavalibrary/djl/blob/master/extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
2. There are a few ready to use built-in TranslatorFactory for huggingface, and we are adding more: https://github.com/deepjavalibrary/djl/blob/master/extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/QuestionAnsweringTranslatorFactory.java
3. Currently `translatorFactory` in serving.property only works for for Criteria<Input, Output> case, we are still debating if we should make it available for all other type. The challenge is `serving.properties` is only available after the model is downloaded and extracted, we have to decide if the model can be loaded before downloading. For DjL-serving this isn't a problem, so `translatorFactory` can work only in djl-serving currently.
4. You can take s similar approach as what we did for djl-serving (we also consider adding this class):
    1. Create your own `TranslatorFactory`, which support all your input and output date type
    2. in your TranslatorFactory, read `arguments` and extract `transaltor`/`translatorFactory` key, and create different translator

**Comment by frankfliu** [comment]
Here is a reference for `DeferredTranslatorFactory`:

```
/*
 * Copyright 2022 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance
 * with the License. A copy of the License is located at
 *
 * http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
 * OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 */
package ai.djl.translate;

import ai.djl.Model;
import ai.djl.util.Pair;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.lang.reflect.Constructor;
import java.lang.reflect.Type;
import java.util.Collections;
import java.util.Map;
import java.util.Set;

public class DeferredTranslatorFactory  implements TranslatorFactory {

    private static final Logger logger = LoggerFactory.getLogger(DeferredTranslatorFactory.class);

    /** {@inheritDoc} */
    @Override
    public Set<Pair<Type, Type>> getSupportedTypes() {
        return Collections.emptySet();
    }

    /** {@inheritDoc} */
    @Override
    public boolean isSupported(Class<?> input, Class<?> output) {
        return true;
    }

    /** {@inheritDoc} */
    @Override
    public Translator<?, ?> newInstance(
            Class<?> input, Class<?> output, Model model, Map<String, ?> arguments)
            throws TranslateException {
        String factoryClass = ArgumentsUtil.stringValue(arguments, "translatorFactory");
        if (factoryClass != null && !factoryClass.isEmpty()) {
            TranslatorFactory factory = loadTranslatorFactory(factoryClass);
            if (factory != null
                    && !(factory instanceof ServingTranslatorFactory)
                    && factory.isSupported(input, output)) {
                logger.info("Using TranslatorFactory: {}", factory.getClass().getName());
                return factory.newInstance(input, output, model, arguments);
            }
            throw new TranslateException("Failed to load translatorFactory: " + factoryClass);
        }
        throw new TranslateException("No translatorFactory defined.");
    }

    private TranslatorFactory loadTranslatorFactory(String className) {
        try {
            Class<?> clazz = Class.forName(className);
            Class<? extends TranslatorFactory> subclass = clazz.asSubclass(TranslatorFactory.class);
            Constructor<? extends TranslatorFactory> constructor = subclass.getConstructor();
            return constructor.newInstance();
        } catch (Throwable e) {
            logger.trace("Not able to load TranslatorFactory: " + className, e);
        }
        return null;
    }
}
```

**Comment by frankfliu** [comment]
@AbhishekBose 

I created a PR to address your issue: https://github.com/deepjavalibrary/djl/pull/1868

**Comment by AbhishekBose** [comment]
Thanks @frankfliu . Just went through the committed files. This should help our use case. We were actually in the process of writing a translator factory for all the possible input-output pairs per model type. Using the serving properties should be helpful
