### ISSUE TITLE
The HuggingFaceTokenizer can't support MacOs M1

### ISSUE THREAD

**Issue by Twang123** [deepjavalibrary/djl#1891]
## Description

The HuggingFaceTokenizer can't support MacOs M1

Will this change the current api? How?
The HuggingFaceTokenizer  support MacOs M1

Who will benefit from this enhancement?
mac users

## References

- list reference and related literature
- list known implementations

**Comment by frankfliu** [comment]
Fixed by: https://github.com/deepjavalibrary/djl/pull/1934

**Comment by frankfliu** [comment]
Please try our 0.19.0-SNAPSHOT build.

**Comment by Twang123** [comment]
How to use 0.19.0-SNAPSHOT
