### ISSUE TITLE
win10 and centos7,causes GPU memory leak when using GPU to predict.  

### ISSUE THREAD

**Issue by lisenjack** [deepjavalibrary/djl#1914]
**Description:**
Load my custom model at project startup.I create a new custom predictor every time,and close after use.
the GPU memory never be released even predictor is closed.

**Error Message:**
the error message:RuntimeError: CUDA out of memory. Tried to allocate 6.47 GiB (GPU 0; 14.62 GiB total capacity; 8.08 GiB already allocated; 5.16 GiB free; 8.22 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Expected Behavior:**
the GPU memory is released after predict.

**Try to solve：**
When downgrade pytorch-engine from version 0.18.0 to version 0.17.0,and predictor is closed every time,but the problem still exists.GPU always keeps rising.

**core code1:**
>static{
       Path modelDir = Paths.get("data/torchModel/script_model.pt");
       model = Model.newInstance("script_model");
       try {
            model.load(modelDir, "script_model");
       } catch (IOException | MalformedModelException e) {
            e.printStackTrace();
       }
}

**core code2:**
> Predictor<BertPieceToken, List> predictor = model.newPredictor(translator);
predictor.batchPredict(input);
predictor.close();

**java dependency:**

     <dependency>
        <groupId>ai.djl.pytorch</groupId>
        <artifactId>pytorch-native-cu113</artifactId>
        <classifier>linux-x86_64</classifier>
        <version>1.11.0</version>
        <scope>runtime</scope>
    </dependency>

    <dependency>
        <groupId>ai.djl.pytorch</groupId>
        <artifactId>pytorch-jni</artifactId>
        <version>1.11.0-0.18.0</version>
        <scope>runtime</scope>
    </dependency>

    <dependency>
        <groupId>ai.djl.pytorch</groupId>
        <artifactId>pytorch-engine</artifactId>
        <version>0.17.0</version>
        <scope>runtime</scope>
    </dependency>

    <dependency>
        <groupId>ai.djl</groupId>
        <artifactId>api</artifactId>
        <version>0.17.0</version>
    </dependency>

**Comment by lisenjack** [comment]
>   
         <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-native-cu113</artifactId>
            <classifier>linux-x86_64</classifier>
            <version>1.11.0</version>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-jni</artifactId>
            <version>1.11.0-0.18.0</version>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-engine</artifactId>
            <version>0.17.0</version>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>api</artifactId>
            <version>0.17.0</version>
        </dependency>

**Comment by KexinFeng** [comment]
Thanks for reporting this error. Could you provide a minimal code that can successfully run and reproduces the issue? It will be helpful for the next step of debugging. Please fill out the missing sections below, especially *How to Reproduce?* and *Steps to reproduce* and *Environment info*.

## Description
(A clear and concise description of what the bug is.)

### Expected Behavior
(what's the expected behavior?)

### Error Message
(Paste the complete error message, including stack trace.)

## How to Reproduce?
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

## Environment Info

Please run the command `./gradlew debugEnv` from the root directory of DJL (if necessary, clone DJL first). It will output information about your system, environment, and installation that can help us debug your issue. Paste the output of the command below:

```
PASTE OUTPUT HERE
```

**Comment by KexinFeng** [comment]
Have you seen this [issue](https://github.com/deepjavalibrary/djl/issues/1886)? It looks similar to yours. Also a quick trial is to see if downgrading the version helps.

**Comment by lisenjack** [comment]
> Have you seen this [issue](https://github.com/deepjavalibrary/djl/issues/1886)? It looks similar to yours. Also a quick trial is to see if downgrading the version helps.

I update my question. I have seen the issue,but it doesn't solve my problem.I've already tried.the issue solve  CPU memory leak,not GPU memory leak.

**Comment by KexinFeng** [comment]
Thanks for the update! 

But to more quickly find the bug, is possible for you to provide a minimal code that can successfully run and reproduces the issue? It'd be helpful to show how to reproduce and the steps to reproduce it. Environment info would probably be relevant too. Thanks!

**Comment by lanking520** [comment]
It's hard to tell from the message you shared. Please provide some inference code. We can help to identify that. And generally, you should try to reuse the predictor instead of close it in every run. The Translator has a ctx.getNDManager you can use to create NDArray
