### ISSUE TITLE
example pretrained Model not exist in server?

### ISSUE THREAD

**Issue by RESDXChgfore9hing** [deepjavalibrary/djl#1939]
## Description
Exception in thread "main" ai.djl.repository.zoo.ModelNotFoundException: No matching model with specified Input/Output type found.
when trying out examples in https://github.com/deepjavalibrary/djl/blob/master/examples/src/main/java/ai/djl/examples/inference/BertQaInference.java

### Expected Behavior
properly output as the example shows

### Error Message
Exception in thread "main" ai.djl.repository.zoo.ModelNotFoundException: No matching model with specified Input/Output type found.
        at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:178)

## How to Reproduce?
download the dependencies,
model-zoo-0.17.0.jar
mxnet-engine-0.17.0.jar
commons-compress-1.21.jar
api-0.17.0.jar
basicdataset-0.17.0.jar
slf4j-api-2.0.0-beta1.jar
copy paste the source code 
javac ....
java ....

### Steps to reproduce
java -cp %newcp% TestBert

## What have you tried to solve it?
think its amazon server problem.dont know how to fix.other than request to re-upload.

## Environment Info
didnt use gradle.
win10,jdk18

**Comment by RESDXChgfore9hing** [comment]
you are right.
BTW,is there anyway you know that can get the minimal dependencies per project?

**Comment by frankfliu** [comment]
You have to understand what each dependency is used for.
See: https://docs.djl.ai/docs/development/dependency_management.html

**Comment by RESDXChgfore9hing** [comment]
Noted with thanks,will look around and see if I can find a way to automate the dependencies fetching.
Will close this issue since its my bad for not properly having the dependencies,
Maybe should consider giving the ai.djl.repository.zoo.ModelNotFoundException a longer explaination that includes the possibility of incomplete dependencies?
So that future devs can debug easier.and that should be ok.
