### ISSUE TITLE
Adding a way too limit djl api,no internet connection,kinda like a dry run.

### ISSUE THREAD

**Issue by RESDXChgfore9hing** [deepjavalibrary/djl#1958]
## Description
Ideally the best would be to have a simple.
public static boolean dryrunnointernet=false;
and let the user switch that to true if they ever needs it.

Will this change the current api? How?
backward compatible since its addition,not subtraction.
ai.djl.repository.MRL maybe will has some big change,
make the loading model slightly less efficient and more complex by introducing if else or more try catch.

Who will benefit from this enhancement?
Any company.developers that has strict security restriction(production&development).
and
some physical limitations,if the end model is expected to run in a desolated shielded facility.(eg,space?)
and
Developers can test locally and continue development even in a dense forest(literally?) and make sure its perfectly reproducible.(well if its pre downloaded or fully self-trained)

## References
no known java apps has such implementation.
however for cli binaries with go lang its common,eg chezmoi ,has --dry-run it does not states to limit internet connection directly though has such effect due to ineffective download(attempt to download but fail due to limited when attempt write to path).
ideally it does not even need to attempt download but just simply throw an error,NOINTERNETCONNECTIONERROR.

**Comment by frankfliu** [comment]
We actually have this option for downloading model zoo models, we can add this option to download dependencies as well.

**Comment by RESDXChgfore9hing** [comment]
so where is that option?

**Comment by frankfliu** [comment]
Added `offline` feature for disabling download native library at runtime, see: https://github.com/deepjavalibrary/djl/pull/1987

**Comment by RESDXChgfore9hing** [comment]
Epic

**Comment by RESDXChgfore9hing** [comment]
Though I think we should mention this somewhere in the docs,else it would be a stupid property that no one knows about or those that actually read the source will only use it. or next time has a similar issue opened again.
