### ISSUE TITLE
`Criteria.builder()` confusing behaviour related to ordering

### ISSUE THREAD

**Issue by Lundez** [deepjavalibrary/djl#1961]
## Description
If I call `.optModelPath` before `.setTypes` my `optModelPath` is removed, while if I call `.setTypes` first the `optModelPath` is still "active".

This bug caused me having an incredible amount of confusion!

### Expected Behavior
Shouldn't matter which order we apply building steps.

### Error Message
Model not found, or even worse when I tried to also remove Application that it loads ANOTHER model from a DIFFERENT path. That was incredibly confusing too, now my model required the wrong input rank!

## How to Reproduce?
```kotlin
return Criteria.builder()
            .optEngine(engine.djlEngineName())
            .optDevice(device)
            .setTypes(String::class.java, String::class.java)
            .optModelPath(file.path)
            .optTranslator(translator)
            .optApplication(Application.NLP.SENTIMENT_ANALYSIS)
            .optProgress(ProgressBar())
            .build()
```
vs
```kotlin
return Criteria.builder()
            .optEngine(engine.djlEngineName())
            .optDevice(device)
            .optModelPath(file.path)
            .setTypes(String::class.java, String::class.java)
            .optTranslator(translator)
            .optApplication(Application.NLP.SENTIMENT_ANALYSIS)
            .optProgress(ProgressBar())
            .build()
```

### Steps to reproduce

1. See code update, I think the issue is attached to `return new Builder<>(inputClass, outputClass, this);`

## Environment Info

Windows 11, WSL Ubuntu

```
FAILS
```

**Comment by frankfliu** [comment]
@Lundez 
Indeed, this is a bug! Thanks a lot for reporting is.
