### ISSUE TITLE
set Function of NDArray, like set(int[] data) should compare the datatype of NDArray and datatype of data

### ISSUE THREAD

**Issue by warthecatalyst** [deepjavalibrary/djl#1970]
## Description
NDArray anchors = manager.zeros(new Shape(3),Datatype.FLOAT32);
int[] data = new int[]{1,2,3};
anchors.set(data);

### Expected Behavior
should throw an exception when datatypes mismatch

**Comment by KexinFeng** [comment]
What is the current behaviour? I think instead of throwing a datatypes mismatch, another way is to automatically convert the datatype.

**Comment by warthecatalyst** [comment]
it doesn't set the NDArray to corresponding data
