### ISSUE TITLE
java.lang.UnsatisfiedLinkError caused by /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found

### ISSUE THREAD

**Issue by junA2Z** [deepjavalibrary/djl#1986]
## Description
I've imported djl.ai:sentencepiece:0.18.0 and run the build on GitLab pipeline build. Here is the error:

```
java.lang.UnsatisfiedLinkError: /home/jenkins/.djl.ai/sentencepiece/0.1.96-0.18.0/libsentencepiece_native.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/jenkins/.djl.ai/sentencepiece/0.1.96-0.18.0/libsentencepiece_native.so)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1[83](https://code.corp.indeed.com/meta-taxo/bpemb-java/-/jobs/9150249#L83)2)
        at java.lang.Runtime.load0(Runtime.java:811)
        at java.lang.System.load(System.java:1088)
        at ai.djl.sentencepiece.jni.LibUtils.loadLibrary(LibUtils.java:51)
        at ai.djl.sentencepiece.SpProcessor.<clinit>(SpProcessor.java:26)
        at ai.djl.sentencepiece.SpTokenizer.<init>(SpTokenizer.java:50)
```

We are using CentOS7 as Gitlab container. Does anyone have workaround for this? Thanks!

### Additional Information
I'm importing `sentencepiece-1.8.0` with gradle `compile 'ai.djl.sentencepiece:sentencepiece:0.18.0'`. The build succeeds, but when I initialize `SpTokenizer` in my test, `./gradlew test` fails. The error comes from GitLab pipeline runner test stage. I've checked the GLIBCXX version with `strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX`

```
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

I've checked some solutions like upgrading gcc version, but I don't think those solutions can be applied to GitLab container as the environment is managed by centralized system in our company.

**Comment by frankfliu** [comment]
@junA2Z
I don't think our sentencepiece work on centos7, the minimum GLIBC version required is: 2.26.
For tokenizer, we suggest you to use huggingface tokenizer instead. it support centos 7: https://github.com/deepjavalibrary/djl/tree/master/extensions/tokenizers

You can try to download `libstdc++.so.6` file from: https://djl-ai.s3.amazonaws.com/publish/extra/libstdc%2B%2B.so.6
and manually save it into `~/.djl.ai/sentencepiece/0.1.96-0.18.0` folder.

**Comment by junA2Z** [comment]
@frankfliu 

Thanks for your reply. As suggested, I'm building the huggingface tokenizer, and it still throws error:

```
    java.lang.UnsatisfiedLinkError: /home/jenkins/.djl.ai/tokenizers/0.12.0-0.18.0-linux-x86_64/libtokenizers.so: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/jenkins/.djl.ai/tokenizers/0.12.0-0.18.0-linux-x86_64/libtokenizers.so)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1832)
        at java.lang.Runtime.load0(Runtime.java:811)
        at java.lang.System.load(System.java:1088)
        at ai.djl.huggingface.tokenizers.jni.LibUtils.loadLibrary(LibUtils.java:70)
        at ai.djl.huggingface.tokenizers.jni.LibUtils.<clinit>(LibUtils.java:41)
        at ai.djl.huggingface.tokenizers.HuggingFaceTokenizer.newInstance(HuggingFaceTokenizer.java:61)
        at ai.djl.huggingface.tokenizers.HuggingFaceTokenizer.newInstance(HuggingFaceTokenizer.java:50)
```
which complains that `GLIBC_2.25` not found in the build system.

**Comment by frankfliu** [comment]
Please try 0.19.0-SNAPSHOT version, 0.18.0 doesn't support centos7.

Can you try clone our demo repo and run our canary build on your centos: https://github.com/deepjavalibrary/djl-demo/blob/master/.github/workflows/canary-centos.yml#L90

```
git clone https://github.com/deepjavalibrary/djl-demo.git
cd djl-demo/canary
DJL_ENGINE=tokenizers PYTORCH_PRECXX11=true ./gradlew clean run
```

**Comment by junA2Z** [comment]
OK, let me do that. JFYI, when I tried `compile 'ai.djl:api:0.18.0'` and use WordPieceTokenizer, it works without error.

**Comment by frankfliu** [comment]
`WordPieceTokenizer` implemented in pure java, It doesn't need SentencePiece or Huggingface tokenizer

**Comment by junA2Z** [comment]
Is `1.9.0-SNAPSHOT` publicly available? I can't find it from gradle build.

**Comment by frankfliu** [comment]
0.19.0 has not publicly released yet. It's SNAPSHOT build, see: https://docs.djl.ai/docs/get.html#nightly-snapshots

**Comment by junA2Z** [comment]
Do you have a concrete timeline for 0.19.0? Is there any chance for it to be released in September? Our company doesn't allow to use `repositories` block in gradle file.

**Comment by frankfliu** [comment]
0.19.0 will be released in two weeks.
We don't have plan to make to support centos for sentencepiece. There are two way for you to use sentencepiece:
1. build sentencepiece jar from DJL's source on centos:7
2. contribute to DJL and add centos:7 support for sentencepiece, you can find current CI: https://github.com/deepjavalibrary/djl/blob/master/.github/workflows/native_s3_sentencepiece.yml#L37-L73
