### ISSUE TITLE
Is it possible to set number of CPU threads with code?

### ISSUE THREAD

**Issue by xuanqing94** [deepjavalibrary/djl#2019]
Through the document I found two ways to set number of cpu threads (assuming Pytorch backend is used):

1. set OMP_NUM_THREADS env variable
2. -Dai.djl.pytorch.num_interop_threads and -Dai.djl.pytorch.num_threads

But sometimes I just want to set this property during model initialization time. Something like `Criteria.builder().setNumThreads(32).build()`. Is it possible to do that at this moment?

**Comment by frankfliu** [comment]
1. `OMP_NUM_THREADS` has global impact, it not only affect PyTorch, it also affect other engines
2. -Dai.djl.pytorch.num_interop_threads affect PyTorch only and it can override `OMP_NUM_THREADS`

The setting works at PyTorch engine level, it doesn't make sense to be per model.
