### ISSUE TITLE
Caused by: java.lang.UnsatisfiedLinkError djl.ai/pytorch/1.12.1-Cu116-Linux-x86_64/Libtorch_cuda_cpp.so:Libcudnn.so.8:cannotopen:sharedobjectfile:Nosuchfileordirectory

### ISSUE THREAD

**Issue by Bill-zy** [deepjavalibrary/djl#2067]
[djl.ai/pytorch/1.12.1-Cu116-Linux-x86_64/Libtorch_cuda_cpp.so:Libcudnn.so.8:cannotopen:sharedobjectfile:Nosuchfileordirectory]

**Comment by frankfliu** [comment]
@Bill-zy 

1. Did you install cudnn8 on your system?
2. Can you try run your application using docker: nvidia/cuda:11.3.1-cudnn8-devel-ubuntu18.04
