### ISSUE TITLE
[HELP NEEDED] How to get a Java array with shape from NDArray?

### ISSUE THREAD

**Issue by codershenghai** [deepjavalibrary/djl#2068]
I can get a java array from ndArray.toDoubleArray() or ndArray.toFloatArray(), but they don't have shape, how can I get a java array with shape like [10, 20, 3]?

**Comment by lanking520** [comment]
We flatten them by default to achieve the best performance. You can reconstruct on your own if you need to get it in multiple dimensions

**Comment by KexinFeng** [comment]
Do you call `ndArray.toFloatArray()` or `ndArray.toDoubleArray()` during dubuging? If so, you can see the formatted array by calling `ndArray.toString()`. If you want to directly see the array in the IDE, just like in python IDE, you can comment out this: https://github.com/deepjavalibrary/djl/blob/22add9bf118e09cfc39001ff307c6dd40beb2b3d/api/src/main/java/ai/djl/ndarray/internal/NDFormat.java#L64

**Comment by KexinFeng** [comment]
Take a look at https://github.com/deepjavalibrary/djl/pull/2078
To see the array content in debugger, checkout the setting in the 
[development_guideline.md](https://github.com/deepjavalibrary/djl/pull/2078/files#diff-8671f4c905bd7532aa5de5428b34e2ef79cf5e5d3807f049da004f56b7944076)

**Comment by frankfliu** [comment]
Feel free to re-open the issue if you have further question
