### ISSUE TITLE
How to define the input data as point cloud data, such as pcd file

### ISSUE THREAD

**Issue by ruanhailiang** [deepjavalibrary/djl#2074]
How to define the input data as point cloud data, such as pcd file？

**Comment by frankfliu** [comment]
You have to choose a PCD library for Java to load your PCD file. Here is something I found:
1. https://www.robwork.org/apidoc/java/
2. https://docs.aspose.com/3d/java/

**Comment by frankfliu** [comment]
Feel free to reopen this issue if you still have question
