### ISSUE TITLE
Failed to run djl v0.19.0 on MAC (x86_64, macOS 10.15.7)

### ISSUE THREAD

**Issue by georgewei** [deepjavalibrary/djl#2094]
Python 3.9.6 & torch 1.12.1 are installed on my MAC:

> $ python3
> Python 3.9.6 (default, Jun 29 2021, 06:20:32) 
> [Clang 12.0.0 (clang-1200.0.32.29)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import torch
> >>> print(torch.__version__)
> 1.12.1
> >>> 

But it fails to load the library while calling ai.djl.pytorch.jni.PyTorchLibrary.torchSetGradMode:

> Caused by: java.lang.UnsatisfiedLinkError: ai.djl.pytorch.jni.PyTorchLibrary.torchSetGradMode(Z)V
> 	at ai.djl.pytorch.jni.PyTorchLibrary.torchSetGradMode(Native Method) ~[pytorch-engine-0.19.0.jar:na]
> 	at ai.djl.pytorch.jni.JniUtils.setGradMode(JniUtils.java:90) ~[pytorch-engine-0.19.0.jar:na]
> 	at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:54) ~[pytorch-engine-0.19.0.jar:na]
> 	... 46 common frames omitted
> 

After I downgraded djl to 0.18.0, it works OK.

I guess the newly added api torchIsGradMode & torchSetGradMode not implemented in torch 1.12.1 yet, at least on MAC.

**Comment by georgewei** [comment]
> @georgewei You might have a 0.19.0-SNAPSHOT version cache in your machine. Please clean your cache and try it again:
> 
> ```
> rm -rf ~/.djl.ai/pytorch/
> ```

I've checked the content of ~/.djl.ai/pytorch/, there isn't a 0.19.0-SNAPSHOT version cache:

> $cd ~/.djl.ai
> $ls
> cache   mxnet   paddle  pytorch
> $ ls pytorch/
> 1.12.1-cpu-osx-x86_64   1.12.1.txt              1.9.1-cpu-osx-x86_64

But I also tried to clean the cache:

> $ rm -rf pytorch/

Then I run the project again, the same error occured.

**Comment by frankfliu** [comment]
DJL is not depends on Python and external torch. And it should working with 1.12.1. Can you share your project on github?

Are you building DJL from source?
Can you enable debug log?
Can you do the following to troubleshoot your system:

```
git clone https://github.com/deepjavalibrary/djl-demo
cd djl-demo/canary
DJL_VERSION=0.19.0 ./gradlew run
```
Collect the log and see if can find any clue.

**Comment by georgewei** [comment]
> DJL is not depends on Python and external torch. And it should working with 1.12.1. Can you share your project on github?
> 
> Are you building DJL from source? Can you enable debug log? Can you do the following to troubleshoot your system:
> 
> ```
> git clone https://github.com/deepjavalibrary/djl-demo
> cd djl-demo/canary
> DJL_VERSION=0.19.0 ./gradlew run
> ```
> 
> Collect the log and see if can find any clue.

My project: https://github.com/georgewei/ai-service.git

I've tried to run djl-demo as you suggested, the last command "./gradlew run" keeps running but feeds NO messages back.

**Comment by frankfliu** [comment]
@georgewei 

You force your project to use PyTorch 1.9.1 which is not supported by DJL 0.19.0

Here is the issues that I found in your `pom.xml`:
1. `pytorch-native-auto` has deprecated, and no longer needed since DJL 0.15.0, see: https://docs.djl.ai/docs/development/dependency_management.html
2. For supported PyTorch version for each DJL version, see: https://docs.djl.ai/engines/pytorch/pytorch-engine/index.html#installation
3. Since you are using BOM, I you suggest you remove the following and let DJL to choose version for you:
```
        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-native-auto</artifactId>
            <version>${pytorch.version}</version>
        </dependency>
```
4. BOM applies to ONNXRuntime as well, do not include version in the following:
```
        <dependency>
            <groupId>ai.djl.onnxruntime</groupId>
            <artifactId>onnxruntime-engine</artifactId>
        </dependency>
```

**Comment by georgewei** [comment]
> @georgewei
> 
> You force your project to use PyTorch 1.9.1 which is not supported by DJL 0.19.0
> 
> Here is the issues that I found in your `pom.xml`:
> 
> 1. `pytorch-native-auto` has deprecated, and no longer needed since DJL 0.15.0, see: https://docs.djl.ai/docs/development/dependency_management.html
> 2. For supported PyTorch version for each DJL version, see: https://docs.djl.ai/engines/pytorch/pytorch-engine/index.html#installation
> 3. Since you are using BOM, I you suggest you remove the following and let DJL to choose version for you:
> 
> ```
>         <dependency>
>             <groupId>ai.djl.pytorch</groupId>
>             <artifactId>pytorch-native-auto</artifactId>
>             <version>${pytorch.version}</version>
>         </dependency>
> ```
> 
> 4. BOM applies to ONNXRuntime as well, do not include version in the following:
> 
> ```
>         <dependency>
>             <groupId>ai.djl.onnxruntime</groupId>
>             <artifactId>onnxruntime-engine</artifactId>
>         </dependency>
> ```

Yes, it works now. Thanks.
