### ISSUE TITLE
Training PyTorch on M1 Macs

### ISSUE THREAD

**Issue by carlosuc3m** [deepjavalibrary/djl#2103]
Hello again, with the new possibility of training PyTorch models in Macs with the M1 chip I was wondering if that feature will ever be added to DJL.
I have already seen dependencies with support for osx-arch:
https://mvnrepository.com/artifact/ai.djl.pytorch/pytorch-jni

Regards,
Carlos

**Comment by zachgk** [comment]
We do have support for [M1 PyTorch](http://docs.djl.ai/engines/pytorch/pytorch-engine/index.html#macos-m1) so you should be able to train on them now
