### ISSUE TITLE
paddleEngine init error

### ISSUE THREAD

**Issue by oswardlx** [deepjavalibrary/djl#2123]
paddleEngine init error

in this class ai.djl.paddlepaddle.engine.PpEngine#54

if (engine.getRank() < getRank()) {
                // alternativeEngine should not have the same rank as PaddlePaddle
                alternativeEngine = engine; 
}

PpEngine Override getRank() and return 10
Engine.getInstance also return PpEngine so engine.getRank() also return 10;
Then alternativeEngin is always null;

**Comment by frankfliu** [comment]
@oswardlx 
1. If you only have PaddlePaddle engine in your classpath, or PaddlePaddle is set to be the default engine, `alternativeEngine ` is expected to be null
2. Only PyTorch, Tensorflow or MXNet is qualified to be alternativeEngine

**Comment by oswardlx** [comment]
thanks

**Comment by oswardlx** [comment]
annother
