### ISSUE TITLE
Clarify fp16/32 use in benchmark & add g4dn/g5/g5g & multiple models

### ISSUE THREAD

**Issue by jxtps** [deepjavalibrary/djl#2125]
The benchmarks on https://docs.djl.ai/docs/demos/aws/inferentia/index.html show a dramatic difference in performance with & without Inferentia enabled, but it's not actually all that clear precisely what the difference between the two runs shown are? 

Right now it looks like it's fp16 on Inferentia vs fp32 on CPU, which is not really the benchmark I'd be looking for. 

Any chance for published numbers for fp16 on Inferentia, g4dn, g5, and g5g (if supported)? 

I realize performance will differ for different networks, so ideally this would be run across a couple of reference models. Thanks!

**Comment by frankfliu** [comment]
@jxtps 
The document is just show you how DJL can make it simple for you to run models on Inferentia.
The demo code just tries to show you how to run benchmark your model in DJL.
We are not intent to publish any benchmark results. You can check AWS Neuron team for official benchmark results.

Since the performance is model specific, it's better you run the benchmark for your own model. You might want to check out our benchmark tool that make it easy for you to benchmark your model on different platform: https://github.com/deepjavalibrary/djl-serving/tree/master/benchmark

**Comment by jxtps** [comment]
Ok, that's fine, but the absence of solid apples-to-apples benchmarks between DJL & Neuron and e.g. pytorch / tensorrt / triton alternatives makes for a very frustrating end user experience. 

On https://docs.djl.ai/docs/serving/index.html you make the bold claim "Performance - DJL serving running multithreading inference in a single JVM. Our benchmark shows DJL serving has higher throughput than most C++ model servers on the market" - that's great, but where are the numbers?

**Comment by lanking520** [comment]
@jxtps to answer on your first question for Inferentia benchmark:

We did the benchmark comparison between:
- DJL + our compiled PyTorch Java binding + LibTorch
- DJL + our compiled PyTorch Java binding + LibTorch (Inf)

I think this is apple2apple comparison. Just show how Inf could perform better than CPU. 

If you would like to see other benchmark across different hardware, please feel free to see the provider's site like AWS Neuron, NVIDIA TRT or other places.

**Comment by lanking520** [comment]
@jxtps If you would like to know DJLServing benchmark number, please feel free to send us an email at deepjavalibrary@gmail.com. We are happy to provide you the instruction and benchmark environment to reproduce these numbers.

**Comment by frankfliu** [comment]
@jxtps 
DJL is a library, DJLServing is a model server built on top of DJL.
DJL support all DL engines, and each engines has their strength. Comparing between inf1 vs GPU, ONNX vs pytorch is not apple2apple compare. We wont' provide numbers for those comparison. That's the reason we provide a command line tool to allow user run benchmark by themselves.

DJLServing is aiming for usability and minimize the model server layer overhead. Not like other model servers, DJLServing is optimized for throughput out of box, and still allows you to configure toward latency use case (can be tuned on-par with triton in most cases). If you are interested in the test result and test setting, send us an email.
