### ISSUE TITLE
resolved

### ISSUE THREAD

**Issue by brr53** [deepjavalibrary/djl#2138]

**Comment by frankfliu** [comment]
@brr53 
A `synset.txt` is text file contains class names for image classification/object detection. Each line represent a class name.

The number classes is purely depends the number of classes in your dataset that you trained on.
For example:
- [ImageNet](https://www.image-net.org/about.php) dataset contains 1000 classes, you can ImageNet synset file [here](https://github.com/deepjavalibrary/djl/blob/master/engines/mxnet/mxnet-model-zoo/src/test/resources/mlrepo/model/cv/image_classification/ai/djl/mxnet/synset.txt)
- [CIFAR10](https://www.cs.toronto.edu/~kriz/cifar.html) dataset contain 10 classes, you can find the synset file [here](https://github.com/deepjavalibrary/djl/blob/master/model-zoo/src/test/resources/mlrepo/model/cv/image_classification/ai/djl/zoo/synset_cifar10.txt)
- [coco](https://cocodataset.org/#home) dataset contain 80 object categories, you can find the synset file [here](https://github.com/deepjavalibrary/djl/blob/master/engines/mxnet/mxnet-model-zoo/src/test/resources/mlrepo/model/cv/object_detection/ai/djl/mxnet/classes_coco.txt)
- [PASCAL VOC](http://host.robots.ox.ac.uk/pascal/VOC/) dataset contains 20 object categories, you can find the synset file [here](https://github.com/deepjavalibrary/djl/blob/master/engines/mxnet/mxnet-model-zoo/src/test/resources/mlrepo/model/cv/object_detection/ai/djl/mxnet/classes_voc.txt)

Yolo model usually is trained on COCO or VOC dataset.
