### ISSUE TITLE
HuggingFaceTokenizer android load

### ISSUE THREAD

**Issue by soonguKwon** [deepjavalibrary/djl#2170]
## Description
I tried to load HuggingFaceTokenizer on android but failed.

HuggingFaceTokenizer tokenizer = HuggingFaceTokenizer.newInstance(assetFilePath(this, "tokenizer.json"), options);

### Error Message
ai.djl.engine.EngineException: Failed to load Huggingface native library.

**Comment by frankfliu** [comment]
Currently Huggingface Tokenizer extension is not available for Android. We only added PyTorch and OnnxRuntime to Android.

**Comment by soonguKwon** [comment]
Do you have any support plans?

> Currently Huggingface Tokenizer extension is not available for Android. We only added PyTorch and OnnxRuntime to Android.

**Comment by frankfliu** [comment]
We don't have bandwidth currently. It shouldn't be hard to add Android support. No java code change is needed. The most of work is setup CI to build android native library. We can work with you if you want to contribute.

**Comment by BigSquirrel2000** [comment]
@frankfliu do you know if someone is already working on this? I could help, but probably I have too low android/java skills to do it only by myself.

**Comment by BigSquirrel2000** [comment]
currently I managed to recompile rust with https://github.com/bbqsrc/cargo-ndk

but during System.loadLibrary("tokenizers") in android emulator, following error occurs:
`
java.lang.UnsatisfiedLinkError: dlopen failed: library "libc++_shared.so" not found: needed by /lib/x86_64/libtokenizers.so in namespace classloader-namespace
`

any clues what could be a reason?

**Comment by BigSquirrel2000** [comment]
update: it seems like gradle issue https://github.com/gradle/gradle/issues/23023
for that moment, quickfix described in above issue - seems to work.

**Comment by lanking520** [comment]
Thanks for your discovery @BigSquirrel2000. Are you willing to contribute your working solution to DJL repo? For Android NDK build

**Comment by naveen521kk** [comment]
Hey, I would like to contribute to this issue. I came across this library while looking for a way to run the tokenizer in my Android app project.

I've figured out how to build the rust library using [`cargo-ndk`](https://github.com/bbqsrc/cargo-ndk). However, I wasn't able to figure out how to build OpenSSL, so I've disabled the functions which will use Hugging Face API - that is only local paths would work on Android. I've also created a build native library for Android like [pytorch-native](https://github.com/deepjavalibrary/djl/tree/master/android/pytorch-native) to distribute the rust library.

See https://github.com/deepjavalibrary/djl/compare/master...naveen521kk:djl:tokenizer-android-support?expand=1 for the changes I made.

I've tested the resultant build output in my Android app and it works - made a small wrapper for it in [react native](https://github.com/naveen521kk/react-native-tokenizer) too.

I could make a PR out of that branch if someone could help me configure the CI.

Thanks!

**Comment by frankfliu** [comment]
@naveen521kk 

Really appreciate for your contribution. Your changes looks great, and I tried locally, it works. Please raise a PR, once it merged, we can add CI to publish it.

**Comment by naveen521kk** [comment]
> @naveen521kk
> 
> Really appreciate for your contribution. Your changes looks great, and I tried locally, it works. Please raise a PR, once it merged, we can add CI to publish it.

Hey, I've created https://github.com/deepjavalibrary/djl/pull/3531, have a look at it.
