### ISSUE TITLE
how to create RobustScaler ?

### ISSUE THREAD

**Issue by glorne** [deepjavalibrary/djl#2179]
with python some time ,that need RobustScaler to normal data. how to build RobustScaler on DJL?

```python
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
scaler.fit_transform(data)
```

**Comment by siddvenk** [comment]
You can use the [Featurizer](https://github.com/deepjavalibrary/djl/blob/master/basicdataset/src/main/java/ai/djl/basicdataset/tabular/utils/Featurizer.java) interface in the basicdataset module to implement the RobustScaler(). 

After implementing the RobustScaler as a Featurizer, you can use it to process Features in your dataset using the `addFeature()` method of TabularDataset class:
`addFeature(new Feature("feature-name", new RobustScalerFeaturizer())`

**Comment by glorne** [comment]
ok, that need self to implement? thanks.

**Comment by siddvenk** [comment]
Yes that's correct. We don't have this implemented in DJL right now so you would need to implement it yourself. We would welcome a contribution if you would like to raise a PR.

**Comment by glorne** [comment]
Of course, if i can done that. ☺
