### ISSUE TITLE
It seems hard to work in Centos7

### ISSUE THREAD

**Issue by yang162132** [deepjavalibrary/djl#2193]
when I use djl in Centos7 ,it says that: 
/root/.djl.ai/pytorch/1.10.0-20220111-cpu-linux-x86_64/libc10.so: /lib64/libstdc++.so.6: version `GLIBC_2.27' not found 
by use djl.ai 0.15
I had try to updata glibc but failed finally  and this nearly broke my system. Is there any way to use djl.ai without updata glibc?

**Comment by lanking520** [comment]
Use this: https://docs.djl.ai/engines/pytorch/pytorch-engine/index.html#for-pre-cxx11-build and would solve your issue.

**Comment by lanking520** [comment]
This is available since DJL 0.11.0

**Comment by frankfliu** [comment]
DJL 0.19.0 doesn't support pytorch 1.13.0, you need use 0.20.0 to use PyTorch 1.13.0. See: https://github.com/deepjavalibrary/djl/blob/master/engines/pytorch/pytorch-engine/README.md#installation

**Comment by frankfliu** [comment]
@yang162132 to avoid version mismatch, I strongly recommend you to use or [BOM](https://github.com/deepjavalibrary/djl/blob/master/bom/README.md)

**Comment by yang162132** [comment]
@frankfliu .Thanks for your answer.And by the way which file will the libdjl_torch.so down? It seem that there is not network in my centos.I want to download in my windows and copy to centos

**Comment by frankfliu** [comment]
There are a few ways to do it:
1. recommended: include pytorch-native-cpu-precxx11 and pytorch-jni into your maven pom.xml file: https://github.com/deepjavalibrary/djl-demo/blob/master/development/fatjar/pom.xml#L45-L56, or follow the package guide: https://github.com/deepjavalibrary/djl-demo/blob/master/development/fatjar
2. [pytorch-native-cpu-precxx11-1.13.0-linux-x86_64.jar](https://repo1.maven.org/maven2/ai/djl/pytorch/pytorch-native-cpu-precxx11/1.13.0/pytorch-native-cpu-precxx11-1.13.0-linux-x86_64.jar) and [pytorch-jni-1.13.0-0.20.0.jar](https://repo1.maven.org/maven2/ai/djl/pytorch/pytorch-jni/1.13.0-0.20.0/pytorch-jni-1.13.0-0.20.0.jar) in your classpath
3. distribute the ~/.djl.ai/pytorch cached folder to your target linux machine manually.

**Comment by frankfliu** [comment]
Feel free to reopen this issue if you have further questions.

**Comment by hfwanggh** [comment]
When I run djl on CentOS7 I get an error:
‘’ java.lang.UnsatisfiedLinkError: /root/.djl.ai/paddle/2.3.2-cpu-linux-x86_64/libonnxruntime.so: libstdc++.so.6: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at ai.djl.paddlepaddle.jni.LibUtils.lambda$loadLinuxDependencies$0(LibUtils.java:109)
	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
	at ai.djl.paddlepaddle.jni.LibUtils.loadLinuxDependencies(LibUtils.java:103)
	at ai.djl.paddlepaddle.jni.LibUtils.loadLibrary(LibUtils.java:70) ”

Before this, I have upgraded libstdc++.so.6.0.19 to 6.0.24, because 6.0.19 does not support CXXABI1.3.8, but after this error was solved, the above error occurred again, may I ask how to solve it？Thanks！

**Comment by yang162132** [comment]
I guess  you didn't add it to the environment variables

dalei ***@***.***> 于2023年10月26日周四 16:37写道：
