### ISSUE TITLE
Hello, does djl support NLP text generation? Is there a sample project?

### ISSUE THREAD

**Issue by kkangert** [deepjavalibrary/djl#2204]
At present, my project urgently needs to use java to complete voice recognition and NLP text generation.

**Comment by frankfliu** [comment]
Unfortunately, we don't have a built-in `Translator` for text-generation. You have to implement beam search in java.

**Comment by kangerts** [comment]
> Unfortunately, we don't have a built-in `Translator` for text-generation. You have to implement beam search in java.

OK, thank you. I don't know much about Translator. Is there any relevant information to help me complete the text generation of Translator?

**Comment by lanking520** [comment]
For voice recognition, you can use openai/whisper model and convert it to TorchScript or ONNX. Then DJL can run inference with that. Besides this, you need to build preprocessing and post processing for audio.

**Comment by kangerts** [comment]
> For voice recognition, you can use openai/whisper model and convert it to TorchScript or ONNX. Then DJL can run inference with that. Besides this, you need to build preprocessing and post processing for audio.

OK, thank you. You know about the text generation of djl, can you help me?

**Comment by frankfliu** [comment]
@kangerts 
Here is an example `Translator` class for NLP fill-mask task: https://github.com/deepjavalibrary/djl/blob/master/extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/FillMaskTranslator.java

text-generation is a bit more complicated. I usually need multiple forward pass. You have to implement that logic in Java.

**Comment by kangerts** [comment]
> @kangerts Here is an example `Translator` class for NLP fill-mask task: https://github.com/deepjavalibrary/djl/blob/master/extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/FillMaskTranslator.java
> 
> text-generation is a bit more complicated. I usually need multiple forward pass. You have to implement that logic in Java.

Thank you very much.

**Comment by frankfliu** [comment]
We added this example: 
https://github.com/deepjavalibrary/djl/blob/master/examples/src/main/java/ai/djl/examples/inference/nlp/TextGeneration.java
