### ISSUE TITLE
How to train a speech recognition model suitable for DJL?

### ISSUE THREAD

**Issue by kkangert** [deepjavalibrary/djl#2209]
How to train a speech recognition model suitable for DJL? I want to complete the voice recognition function module of the company through DJL.

**Comment by lanking520** [comment]
It's a bit hard to train with DJL, but if you would like to run inference, there could be a few options. You could port OpenAI/Whisper model to DJL for inference

**Comment by kangerts** [comment]
> It's a bit hard to train with DJL, but if you would like to run inference, there could be a few options. You could port OpenAI/Whisper model to DJL for inference

Hello, do you have specific use cases? How to use their model to run on DJL and reason.

**Comment by lanking520** [comment]
The original model is trained on PyTorch, you could just export it to TorchScript and run inference. Training not working due to missing toolkit to convert audio to tensor

**Comment by zachgk** [comment]
If you are specifically interested in training with DJL, you we do have an audio extension. I recommend using the [`SpeechRecognitionDataset`](https://javadoc.io/doc/ai.djl.audio/audio/latest/ai/djl/audio/dataset/SpeechRecognitionDataset.html) which can help implement the details for your training data. The only dataset we have available is [`Librispeech`](https://javadoc.io/doc/ai.djl.audio/audio/latest/ai/djl/audio/dataset/Librispeech.html), but you can also build your own with a different corpus as well. Once you use that, you should be able to reference some of our existing examples for the actual training.

But, like Qing said, it may be easier to train in Python PyTorch or find a pre-trained model in PyTorch and then just load it using DJL.
