### ISSUE TITLE
How to create multidimensional arrays using NDManager.create()

### ISSUE THREAD

**Issue by 285220927** [deepjavalibrary/djl#2219]
In python, we can use np.array([[[1, 2], [2, 3], [11, 22], [22, 33]], [[1, 2], [2, 3], [11, 22], [22, 33]]]) to create a three-dimensional array. The create method in djl can only support two-dimensional arrays. Is there a better way to create it besides reshape?

**Comment by frankfliu** [comment]
```
            int[] data = {1, 2, 2, 3, 11, 22, 22, 33, 1, 2, 2, 3, 11, 22, 22, 33};
            NDArray array = manager.create(data, new Shape(2, 3, 2));

```

**Comment by frankfliu** [comment]
Feel free to reopen the issue if you have further question
