### ISSUE TITLE
Whether support DeepLab-v3+ Model

### ISSUE THREAD

**Issue by yanchaoguo** [deepjavalibrary/djl#223]
这个项目非常赞；你们为java开发者提供了探索深度学习的途径、

请问有计划支持谷歌DeepLab-v3+模型的语义分隔吗；这个模型的支持对于我们项目的推广会有很大的帮组

**Comment by lanking520** [comment]
Hi @yanchaoguo Thanks for supporting DJL. As long as the model can be saved as Saved_model format in TF, we should be able to leverage the inference functionality of it. Currently TF Engine didn't support for training. 

You can also import the model from GluonCV: https://gluon-cv.mxnet.io/build/examples_segmentation/demo_deeplab.html#sphx-glr-build-examples-segmentation-demo-deeplab-py

Like this DeepLab pretrained model. Just follow this step: http://docs.djl.ai/docs/mxnet/how_to_convert_your_model_to_symbol.html

We have some similar models in our modelzoo, checkout this: http://docs.djl.ai/examples/docs/instance_segmentation.html

**Comment by lanking520** [comment]
@yanchaoguo Do you have any specific use case with this model? If there is one I guess we can add it to the model zoo.

**Comment by yanchaoguo** [comment]
> @yanchaoguo Do you have any specific use case with this model? If there is one I guess we can add it to the model zoo.

抠图 通过mask一键抠图

**Comment by yanchaoguo** [comment]
> @yanchaoguo Do you have any specific use case with this model? If there is one I guess we can add it to the model zoo.

通过mark一键抠图

**Comment by frankfliu** [comment]
We have deeplab v3 model in our PyTorch model zoo now.
