### ISSUE TITLE
djl is picking the wrong PyTorch native library when PyTorch is installed on the system

### ISSUE THREAD

**Issue by s-bernard** [deepjavalibrary/djl#2233]
## Description
When PyTorch is installed on my system (an up-to-date ArchLinux), djl is trying to load the library `pytorch/1.13.0-cpu-precxx11-linux-x86_64` which does not work. But if I uninstall PyTorch, it is picking the correct one: `pytorch/1.13.0-cpu-linux-x86_64`.

### Expected Behavior
It should pick the normal cpu version in both cases.

### Error Message
````
----------------- Engines ---------------
DJL version: 0.20.0
[DEBUG] - Loading native library: /usr/lib64/libtorch_cpu.so
[DEBUG] - Loading native library: /usr/lib64/libtorch.so
[DEBUG] - Loading native library: /home/samuel/.djl.ai/pytorch/1.13.0-cpu-precxx11-linux-x86_64/0.20.0-libdjl_torch.so
Exception in thread "main" ai.djl.engine.EngineException: Failed to load PyTorch native library
        at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:85)
        at ai.djl.pytorch.engine.PtEngineProvider.getEngine(PtEngineProvider.java:40)
        at ai.djl.engine.Engine.getEngine(Engine.java:186)
        at ai.djl.engine.Engine.getInstance(Engine.java:141)
        at ai.djl.engine.Engine.debugEnvironment(Engine.java:413)
        at ai.djl.canary.CanaryTest.main(CanaryTest.java:81)
Caused by: java.lang.UnsatisfiedLinkError: /home/samuel/.djl.ai/pytorch/1.13.0-cpu-precxx11-linux-x86_64/0.20.0-libdjl_torch.so: /home/samuel/.djl.ai/pytorch/1.13.0-cpu-precxx11-linux-x86_64/0.20.0-libdjl_torch.so: undefined symbol: _ZNK5torch3jit6MethodclESt6vectorIN3c106IValueESaIS4_EERKSt13unordered_mapISsS4_St4hashISsESt8equal_toISsESaISt4pairIKSsS4_EEE
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1953)
        at ai.djl.pytorch.jni.LibUtils.loadNativeLibrary(LibUtils.java:368)
        at ai.djl.pytorch.jni.LibUtils.loadLibrary(LibUtils.java:81)
        at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:54)
        ... 5 more
````
## How to Reproduce?
Just run djl-demo canary with PyTorch installed.

### Steps to reproduce

1. `pacman -S python-pytorch`
2. `git clone https://github.com/deepjavalibrary/djl-demo`
3. `cd djl-demo/canary`
4. `./gradlew run`

## What have you tried to solve it?

1. `pacman -R python-pytorch` works
2. changing jvm -> openjdk-11 or graalvm-17 or openjdk-19, does not work

## Environment Info

Arch Linux, x86_64, up-to-date

```
java.runtime.version: 17.0.5+8-jvmci-22.3-b08
java.vendor.version: GraalVM CE 22.3.0
java.version: 17.0.5
os.version: 6.0.12-arch1-1
------------------ CUDA -----------------
[DEBUG] - cudart library not found.
GPU Count: 0

----------------- Engines ---------------
DJL version: 0.21.0-SNAPSHOT
[DEBUG] - Using cache dir: /home/samuel/.djl.ai/mxnet/1.9.1-mkl-linux-x86_64
[DEBUG] - Loading mxnet library from: /home/samuel/.djl.ai/mxnet/1.9.1-mkl-linux-x86_64/libmxnet.so
[DEBUG] - Using cache dir: /home/samuel/.djl.ai/mxnet/1.9.1-mkl-linux-x86_64
Default Engine: MXNet:1.9.0, capabilities: [
        CPU_SSE,
        SIGNAL_HANDLER,
        LAPACK,
        BLAS_OPEN,
        CPU_SSE2,
        DIST_KVSTORE,
        CPU_SSE3,
        OPENMP,
        OPENCV,
        MKLDNN,
]
MXNet Library: /home/samuel/.djl.ai/mxnet/1.9.1-mkl-linux-x86_64/libmxnet.so
Default Device: cpu()
PyTorch: 2
MXNet: 0
XGBoost: 10
LightGBM: 10
TensorFlow: 3
--------------- Hardware --------------
gcc (GCC) 12.2.0
```

**Comment by frankfliu** [comment]
I noticed that you installed python in: `/usr/lib64/libtorch_cpu.so`, which is a system library path. Any reason you install your pytorch there?

We treat system library path as higher priority, we assume you want to override default DJL distribution.

However, DJL JNI is linked with libtorch, the default python pytorch is different from libtorch. It doesn't work with DJL.

You want DJL to load libtorch from pytorch distribution, you have to install cpu version of pytorch:

```
pip install  torch==1.13.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
```

**Comment by s-bernard** [comment]
Yes, I installed PyTorch with the official package of my distribution (ArchLinux) so it’s installed system-wide. The main reason is then it will be kept up-to-date and I don’t have to bother about dependencies.

If I understand well, the `libtorch_cpu.so` DJL provides is compiled differently from the one of my distribution so it may not link with the later?

It there a way to tell DJL to not try to link with the system libtorch but always link with the one dowloaded in the cache?

BTW, why DJL is defaulting to the **precxx11** version? If I replace the content of `1.13.0-cpu-precxx11-linux-x86_64/0.20.0-libdjl_torch.so` by the one of `1.13.0-cpu-linux-x86_64/0.20.0-libdjl_torch.so`, the load works. It fails later because it can’t find one of the mkl symbol but it may work.

**Comment by s-bernard** [comment]
Also, if I rebuild `0.20.0-libdjl_torch.so` to match my local `libtorch.so` and I install it in `/usr/lib`, it should work, right?

**Comment by frankfliu** [comment]
I'm not familiar with ArchLinux, on ubuntu, PyTorch is installed under `python3.9/site-packages` folder.

`/usr/lib64/` folder is automatically added to `java.library.path`, when calling `System.load()` Java will search in `java.library.path` first. If you don't want DJL to use pytorch in `/usr/lib64` folder, you set `java.library.path` to empty:

```
java -Djava.library.path=  ...
```

DJL use standard PyTorch libtorch distribution, however the python distribution has multiple flavors (cpu, gpu, and both). Only CPU distribution is the same as libtorch. 

DJL actually default use non-precxx11 version. The reason it use PRECXX11 is because by default python cpu installation use precxx11 version of libtorch. I guess ArchLinux are special. You can set env var `export PYTORCH_FLAVOR=cpu` for tell DJL that your installed PyTorch is not precxx11 version.

**Comment by s-bernard** [comment]
I have fixed my issue with mkl and now it’s working perfectly when I’m replacing the content of `1.13.0-cpu-precxx11-linux-x86_64/0.20.0-libdjl_torch.so` by the one of `1.13.0-cpu-linux-x86_64/0.20.0-libdjl_torch.so`.

So I can confirm the issue, precxx11 version is used when it should not. I guess, it’s because the second rule & third rule. If I set `PYTORCH_FLAVOR=cpu` then it works as expected.

Is it possible to improve the rules on when the precxx11 version is used? Like checking for an old libstdc++ or gcc?

**Comment by frankfliu** [comment]
We are considering detecting precxx11 for some time. But there isn't an easy and clean way to detect glibc version. Let us know if you have a good idea to detect glibc version.

**Comment by s-bernard** [comment]
Just an idea, but maybe you can try to execute a small piece of code linked against recent glibc and if it fails, you fallback to precxx11.

At least, with `PYTORCH_FLAVOR=cpu`, it’s not blocking for me anymore.

**Comment by frankfliu** [comment]
I created a PR, in future, we are no longer search `java.library.path`: https://github.com/deepjavalibrary/djl/pull/2235
