### ISSUE TITLE
Can user create custom NLP Dataset by extending from ai.djl.basicdataset.nlp.TextDataset?

### ISSUE THREAD

**Issue by SuperMaskv** [deepjavalibrary/djl#2269]
I'm trying to create custom dataset class from ai.djl.basicdataset.nlp.TextDataset, but the Builder inside TextDataset has a package-level constructor which I can't extends from other package. Is that a bug? Should the constructor be public?
I' m using dependency below:
```xml
<dependency>
    <groupId>ai.djl</groupId>
    <artifactId>basicdataset</artifactId>
    <version>0.20.0</version>
</dependency>
```

**Comment by frankfliu** [comment]
Thanks for reporting this issue. Will create a PR to fix this bug.
