### ISSUE TITLE
Modularize Maven ai.djl dependency by adding module-info.java

### ISSUE THREAD

**Issue by davpapp** [deepjavalibrary/djl#2277]
## Description

I'm trying to package my code into an executable with Maven via jpackage. However, I get an error during the jlink step of the process:
`Error: automatic module cannot be used with jlink: ai.djl.api from file`
ai.djl.api is an automatic module, meaning it cannot be linked. I know I can work around this by manually generating the module-info file, but doing so isn't easy.

Will this change the current api? How?
No

Who will benefit from this enhancement?
Anyone looking to package a Java application that uses the DJL API.

## References

[Stackover flow instructions on generating module-info.java from automatic module](https://stackoverflow.com/questions/47727869/creating-module-info-for-automatic-modules-with-jdeps-in-java-9)

**Comment by frankfliu** [comment]
@davpapp 

It's not straight-forward to make DJL a fully modularized library. Many of our dependencies are not support module.

We have a [demo application](https://github.com/deepjavalibrary/djl-demo/tree/master/development/module) that shows you how to create a module application that depends on DJL.

I created a [PR](https://github.com/deepjavalibrary/djl-demo/pull/296) that support jlink/jpackage. The PR leverage https://github.com/beryx/badass-jlink-plugin plugin:

```
cd djl-demo/development/module
./gradlew jlink
build/image/bin/djl-module-demo

./gradlew jpackage
```
