### ISSUE TITLE
predictor.batchPredict result with PaddingStackBatchifier does not match result of running predictor.predict one by one

### ISSUE THREAD

**Issue by DobryninVyacheslav** [deepjavalibrary/djl#2291]
Hello!

I am using the library to work with BERT. To improve performance I want to use `batchPredict`. By default, translator uses `Batchifier.STACK`. It works fine, but if inputs of different dimensions are passed, error occurs. As I understand it, `PaddingStackBatchifier` exists to solve this problem. However, when using it, the results are different from those obtained for the same inputs when passed to `predict` one by one.

My test class:
```kotlin
class PaddingStackBatchifierTest {

    private inline fun <reified I, reified O> loadModel(translator: Translator<I, O>): ZooModel<I, O> =
        Criteria.builder()
            .optApplication(Application.NLP.TEXT_EMBEDDING)
            .setTypes(I::class.java, O::class.java)
            .optModelUrls("./models/distilbert.pt")
            .optTranslator(translator)
            .optProgress(ProgressBar())
            .build()
            .loadModel()

    private val model = loadModel(BertTranslator())
    private val predictorWithStackBatchifier = model.newPredictor()
    private val predictorWithPaddingStackBatchifier = model.newPredictor(
        object : BertTranslator() {
            override fun getBatchifier(): Batchifier = PaddingStackBatchifier.builder()
                .optIncludeValidLengths(false)
                .addPad(0, 0) { m -> m.ones(Shape(1)).mul(vocabulary.getIndex("[PAD]")) }
                .addPad(1, 0) { m -> m.zeros(Shape(1)) }
                .build()
        }
    )

    @Test
    fun `should return same result for batch mode (stack batchifier)`() {
        val content1 = listOf("test", "1")
        val content2 = listOf("test", "2")
        val content3 = listOf("test", "3")
        val vector1 = predictorWithStackBatchifier.predict(content1)
        val vector2 = predictorWithStackBatchifier.predict(content2)
        val vector3 = predictorWithStackBatchifier.predict(content3)

        val embeddingsBatch = predictorWithStackBatchifier.batchPredict(listOf(content1, content2, content3))

        Assertions.assertThat(embeddingsBatch)
            .usingRecursiveComparison()
            .isEqualTo(listOf(vector1, vector2, vector3))
    }

    @Test
    fun `should return same result for batch mode (padding stack batchifier)`() {
        val content1 = listOf("test", "1")
        val content2 = listOf("test", "2", "3")
        val content3 = listOf("test", "3", "4", "5")
        val vector1 = predictorWithPaddingStackBatchifier.predict(content1)
        val vector2 = predictorWithPaddingStackBatchifier.predict(content2)
        val vector3 = predictorWithPaddingStackBatchifier.predict(content3)

        val embeddingsBatch = predictorWithPaddingStackBatchifier.batchPredict(listOf(content1, content2, content3))

        Assertions.assertThat(embeddingsBatch)
            .usingRecursiveComparison()
            .isEqualTo(listOf(vector1, vector2, vector3))
    }
}
```
After executing the following results were obtained:

<img width="506" alt="image" src="https://user-images.githubusercontent.com/49430239/210623918-0923178f-e146-4d05-9a33-26ea90283d04.png">

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/49430239/210624094-67b21c88-b191-40f6-8550-fc0a29094953.png">

I tried different options for setting up the `PaddingStackBatchifier`, but it did not help.
Could you please suggest what I am doing wrong?
Thank you in advance!

**Comment by zachgk** [comment]
Can you test whether the same thing happens if you run the model in Python? If Python works fine, then try to print out the batchified input and see if it is different from the batchified input in Java. The big thing is that in order to run the model, you need to give inputs the same as how it was trained. So, the Java translator and batchifier doesn't have some global behavior but must match whatever behavior the python is doing

**Comment by DobryninVyacheslav** [comment]
I did the same in Python and it works correctly there.
<img width="1258" alt="output" src="https://user-images.githubusercontent.com/49430239/211191798-b0a21ed2-6bc3-4531-908e-47b442b1107e.png">

Then I compared the batchified inputs, it seems like the Python example is using an array of arrays as batchified input, while the Java example is just an array of numbers.
<img width="1366" alt="input" src="https://user-images.githubusercontent.com/49430239/211191706-8d380c4b-8025-435d-ada1-b510842c1bf6.png">

Tell me, please, what am I doing wrong in setting up my batchfirer?

**Comment by frankfliu** [comment]
Tokenizer has its own paddingStrategy and truncationStrategy. If you set padding to max_length on both Python and Java side, you should get the same result. 

I suggest you create your own `NoBatchifierTranslator` that take String[] as input, you can use tokenizer.batchEncoding() to get the same result as python.

**Comment by frankfliu** [comment]
I created a PR to add batch encode support for text embedding: https://github.com/deepjavalibrary/djl/pull/2310

Now you can take String[] as input:

```
Criteria<String[], float[][]> criteria =
        Criteria.builder()
                .setTypes(String[].class, float[][].class)
                .optModelUrls("djl://ai.djl.huggingface.pytorch/sentence-transformers/all-MiniLM-L12-v2")
                .optEngine("PyTorch")
                // .optArgument("tokenizer", "bert-base-uncased")
                .optArgument("padding", "true")
                .optTranslatorFactory(new TextEmbeddingTranslatorFactory())
                .build();

try (ZooModel<String[], float[][]> model = criteria.loadModel();
        Predictor<String[], float[][]> predictor = model.newPredictor()) {
    float[][] res = predictor.predict(text);
}
```

**Comment by DobryninVyacheslav** [comment]
Thanks!
Unfortunately your example doesn't work for me:
![image](https://user-images.githubusercontent.com/49430239/211384514-c88695e5-925b-4fd9-b3b8-7b83afd7796b.png)
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/49430239/211384802-e6de5539-3bb7-4ed0-b0ff-3290dc94f9b3.png">

It seems that I need to wait until the [PR](https://github.com/deepjavalibrary/djl/pull/2310) is merged?

**Comment by frankfliu** [comment]
@DobryninVyacheslav 
The PR has been merged, and you can try our nightly snapshot build.

**Comment by DobryninVyacheslav** [comment]
Thank you!
Could you please add [sentence-transformers/msmarco-distilbert-dot-v5](https://huggingface.co/sentence-transformers/msmarco-distilbert-dot-v5) to DJL model zoo?

**Comment by frankfliu** [comment]
@DobryninVyacheslav 
I imported the model into DJL model zoo, you should be able to use it directly now.

`batchPredict()` won't work together with HuggingfaceTokenizer, you need to use the code I post earlier to run batch inference.

By the way, you need to set `padding` to true in your tokenizer.

**Comment by DobryninVyacheslav** [comment]
Understood, thanks!
Everything works now.
I close the issue.
