### ISSUE TITLE
When will the 0.21.0 version be released？

### ISSUE THREAD

**Issue by oswardlx** [deepjavalibrary/djl#2307]
In my case，PR 2214 fix a bug that local model in djl-serving workflow can't read the serving.properties's engine argument。

this code fix it:
`modelDir = Utils.getNestedModelDir(modelDir);`

so  When will the 0.21.0 version be released？Otherwise, I have to compile and make the Docker image myself. This will take some time。

**Comment by frankfliu** [comment]
Can you use nightly docker image we published on dockerhub?

**Comment by oswardlx** [comment]
I thought you hadn't released it. 
I'll try it.thanks

**Comment by oswardlx** [comment]
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/33048303/211233491-4c60a680-a12f-41d6-a358-73015aaf0d88.png">


@frankfliu this one? 

This doesn't look like

**Comment by oswardlx** [comment]
Do I need permission？

**Comment by frankfliu** [comment]
There are several nightly docker images, all of them are public, they are based master branch of djl-serving repo:

- [cpu-full-nightly](https://hub.docker.com/layers/deepjavalibrary/djl-serving/cpu-full-nightly/images/sha256-f7353b0435a6aa730535b15c50613122c4521b5359fa541c5ce833209a922267?context=explore)
- [cpu-nightly](https://hub.docker.com/layers/deepjavalibrary/djl-serving/cpu-nightly/images/sha256-8902aa3c3cfb0083a9168126610c829b8bcbd48536e269ef08e74ab12a15a6f7?context=explore)
- [aarch64-nightly](https://hub.docker.com/layers/deepjavalibrary/djl-serving/aarch64-nightly/images/sha256-8ca820018b073a82801a608e8fa1d99a1e06d855cb55edc5539ee4dead77b589?context=explore)
- [pytorch-cu117-nightly](https://hub.docker.com/layers/deepjavalibrary/djl-serving/pytorch-cu117-nightly/images/sha256-cfa6cd7fe60c5710513898e2231247d6459738dd886ec985d711b22277fce79f?context=explore)
- [pytorch-inf1-nightly](https://hub.docker.com/layers/deepjavalibrary/djl-serving/pytorch-inf1-nightly/images/sha256-08e6ea6fff3a0ea4721e5eccb67b77c976a1cb25d327fff49bad9b82c7f4184e?context=explore)
- [paddle-cu112-nightly](https://hub.docker.com/layers/deepjavalibrary/djl-serving/paddle-cu112-nightly/images/sha256-1dcf1ec6c98fca6d45b95ebd175870b1d9da9766a4c89379d87feb17762d9091?context=explore)
- [deepspeed-nightly](https://hub.docker.com/layers/deepjavalibrary/djl-serving/deepspeed-nightly/images/sha256-4f7d0d9d8a13fe7fe6231ce8173ded652be69919101c4f2d03491b6e6a3fcacd?context=explore)
- [transformers-nightly](https://hub.docker.com/layers/deepjavalibrary/djl-serving/transformers-nightly/images/sha256-e35e60bcb372069a976adf78aec45f35f8c69c39c7c02a30d3b7b80f8faf78ca?context=explore)

deepspeed and paddle are for large model inference.

**Comment by oswardlx** [comment]
thanks
