### ISSUE TITLE
Can DJL get ACCURACY,precision,Recall, F1_score,ROC and AOC?

### ISSUE THREAD

**Issue by Bill-zy** [deepjavalibrary/djl#2308]
Can DJL get Accuracy,precision,Recall, F1_score,ROC and AOC?
If so, how can I get these indicators.
thanks.

**Comment by KexinFeng** [comment]
The evaluators in DJL are in the directory `api/src/main/java/ai/djl/training/evaluator`. Currently we only have `Accuracy`. It should not be hard to add precision, recall, f1_score, ROC and AOC. But could you provide a use case, so that we could convert them to unit tests for these new evaluators?
