### ISSUE TITLE
ai.djl.sentencepiece doesn't work on M1 Mac

### ISSUE THREAD

**Issue by zerogerc** [deepjavalibrary/djl#2323]
## Description

Hi, we noticed that the sentencepiece library doesn't work on mac m1. It seems like it is supported by the latest c++ sentencepiece https://github.com/google/sentencepiece/issues/608. Could you add the support to djl?

## Error 

```
Caused by: java.io.IOException: Resource not found in classpath: native/lib/osx-aarch64/libsentencepiece_native.dylib
```

**Comment by frankfliu** [comment]
@zerogerc 
I created a PR: https://github.com/deepjavalibrary/djl/pull/2324 to build sentencepiece from M1 and aarch64.

**Comment by TanVD** [comment]
@frankfliu Thank you very much! When should we expect it to be released?

**Comment by lanking520** [comment]
@TanVD DJL release on a 45-60 days cycle, we try to keep this pace.

**Comment by katysav** [comment]
@lanking520 I just tried 0.21.0-SNAPSHOT and it still doesn't work on Mac M1. As you see there is no ARM in the native libs, could you please check that? Thanks!
<img width="340" alt="Screenshot 2023-01-19 at 11 40 17" src="https://user-images.githubusercontent.com/33637983/213422490-d325cba1-7489-4795-b56a-6ce5cfb3c444.png">

**Comment by frankfliu** [comment]
@katysav 
For some reason the previous PR missed some changes. I created a [PR](https://github.com/deepjavalibrary/djl/pull/2327) to fix the build.

**Comment by katysav** [comment]
@frankfliu thanks, the new snapshot works like a charm!
