### ISSUE TITLE
Can't instantiate a Tokenizer when folder is read-only.

### ISSUE THREAD

**Issue by carlos-aguayo** [deepjavalibrary/djl#2333]
## Description
I'm instantiating a Tokenizer, the folder is read-only and thus I get a RuntimeException. 

However, I already defined the `DJL_CACHE_DIR` and `ENGINE_CACHE_DIR` as described [here](https://djl.ai/docs/development/cache_management.html) but I have the impression that the [Rust implementation](https://github.com/deepjavalibrary/djl/blob/master/extensions/tokenizers/rust/src/lib.rs#L29) is not using it.

I'm instantiating a new tokenizer like this:
`HuggingFaceTokenizer.newInstance("sentence-transformers/all-distilroberta-v1");`

And I'm setting the cache properties as described [here](https://djl.ai/docs/development/cache_management.html).
```
System.getProperties().setProperty("DJL_CACHE_DIR", "/usr/local/somefolder");
System.getProperties().setProperty("ENGINE_CACHE_DIR", "/usr/local/somefolder");
```

### Error Message
```
Caused by: java.lang.RuntimeException: Read-only file system (os error 30)
	at ai.djl.huggingface.tokenizers.jni.TokenizersLibrary.createTokenizer(Native Method)
	at ai.djl.huggingface.tokenizers.HuggingFaceTokenizer.newInstance(HuggingFaceTokenizer.java:103)
	at ai.djl.huggingface.tokenizers.HuggingFaceTokenizer.newInstance(HuggingFaceTokenizer.java:90)
```

**Comment by frankfliu** [comment]
@carlos-aguayo 
HuggingTokenizer uses a different environment variable: `TOKENIZERS_CACHE`, will update the document to reflect this behavior.

Usually, this won't be a problem, HuggingfaceTokenizer will fallback to temp directory, unless your temp directory is also readonly

**Comment by frankfliu** [comment]
Created a PR to document this: #2334

**Comment by carlos-aguayo** [comment]
Thank you!
