### ISSUE TITLE
Unable to create NDList from NDArray inside Mutable Map

### ISSUE THREAD

**Issue by AbhishekBose** [deepjavalibrary/djl#2346]
Hello Team,
As seen in the picture below 
![Screenshot 2023-01-26 at 2 36 38 AM](https://user-images.githubusercontent.com/15029917/214691463-4d87d053-3f19-4165-bbed-b09ad384e14e.png)

I have the variable called `resultMap` which contains a key called `resized_img` with the value being a resized NDArray.
Now in my `processInput` I am trying to take this array and put in an NDList for the inference to happen, in this manner

```
override def processInput(ctx: TranslatorContext, input: Map[String,Any]): NDList = {
    val resultMap: Map[String,Any] = preProcessor.apply(input, ctx, false);
    val result = new NDList(resultMap.get("resized_img").asInstanceOf[NDArray])
    result
  }
```

But I am constantly getting the following error
`java.lang.ClassCastException: scala.Some cannot be cast to ai.djl.ndarray.NDArray
`

And If I don't put an explicit `asInstanceOf` the `new NDList()` call doesn't except the value.

How do you recommend we do this?

The idea is to always have a map containing `String, [Different types]` and then create the NDList dynamically before moving in for the inference.

@frankfliu Please help

**Comment by frankfliu** [comment]
Looks like you passed in a Tuple (Not NDArray), which is causing the cast failure.
