### ISSUE TITLE
How do we update slices with DJL NDArray?

### ISSUE THREAD

**Issue by brr53** [deepjavalibrary/djl#2367]
In python we have the following:
    y[:, 0] = x[:, 0] - x[:, 2] / 2

In Java how can I do this? My attempt below gives error:
    y.get(":,0") = x.get(":,0").sub(x.get(":,2").div(2));

I think we are supposed to do it with set() using NDIndex.sliceAxis() but it doesnt support :,0 type slice.

**Comment by brr53** [comment]
I came up with the following, I don't know if this is the optimal way:

    y.set(new NDIndex(":,0"), x.get(":,0").sub(x.get(":,2").div(2)));

**Comment by KexinFeng** [comment]
Yes, in DJL, setting needs to be explicitly called. We haven't overloaded the `=` operation on NDArray to be setting yet, for the similar reason that we haven't overloaded `+-*/` to be add, sub, mul, div etc.

**Comment by brr53** [comment]
Thank you! If the way I mentioned is the optimal way for now, please feel free to close this ticket.

**Comment by KexinFeng** [comment]
That we didn't implement operator overloading is mainly due to java language restriction.
