### ISSUE TITLE
使用DataType.STRING类型的NDArray报空指针(java.lang.NullPointerException)

### ISSUE THREAD

**Issue by dingjun84** [deepjavalibrary/djl#2379]
## Description
测试代码如下：
`public class TestStringNDArray {
    public static void main(String[] args){
        try(NDManager manager = NDManager.newBaseManager()){
            String[][] str = new String[3][3];
            str[0] = new String[]{"a1","b1","c1"};
            str[1] = new String[]{"a2","b2","c2"};
            str[2] = new String[]{"a3","b3","c3"};
            NDArray arr = manager.create(str[0]);
            NDArray values = arr.get(new long[]{1,2});
            System.out.println(values);
        }

    }
}`

使用的
### Expected Behavior
出现了空指针异常

### Error Message
Exception in thread "main" java.lang.NullPointerException
	at ai.djl.ndarray.NDArray.get(NDArray.java:525)
	at ai.djl.ndarray.NDArray.get(NDArray.java:514)
	at ai.djl.ndarray.NDArray.get(NDArray.java:559)
	at com.test.djl.TestStringNDArray.main(TestStringNDArray.java:14)
依赖包：
<dependency>
      <groupId>ai.djl.pytorch</groupId>
      <artifactId>pytorch-engine</artifactId>
      <version>0.20.0</version>
      <scope>runtime</scope>
    </dependency>

目前排查到是：

ai.djl.pytorch.engine.PtNDArray.java
`public PtNDArray(PtNDManager manager, String[] strs, Shape shape) {
        super(-1L);
        this.manager = manager;
        this.strs = strs;
        this.shape = shape;
        this.dataType = DataType.STRING;
    }`

没有对this.ptNDArrayEx进行初始化，导致NDArray.getNDArrayInternal()出现空指针

**Comment by frankfliu** [comment]
@dingjun84 
PyTorch doesn't really support String tensor. libtorch internally use `IValue` instead.

We add String tensor support is mainly to have a generic way to pass parameters to the model. In DJL we don't support any NDArray operations on String tensor in PyTorch.

TensorFlow support String tensor, you can use TensorFlow to do NDArray operations.

**Comment by frankfliu** [comment]
I created a PR to better handle String tensor.
