### ISSUE TITLE
pytorch and djl

### ISSUE THREAD

**Issue by yufengsjtu** [deepjavalibrary/djl#2389]
if the return value of forwards function in pytorch is a tuple of some tensors with different dimensions,what should i do to deal with such a problem in DJL lib in java

**Comment by frankfliu** [comment]
@yufengsjtu 

If the output is complicated data type that DJL is not able to automatically map it to `NDList`, you have to use `IValue` directly. see: https://github.com/deepjavalibrary/djl/blob/master/engines/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/IValueTest.java#L201
