### ISSUE TITLE
ModelZoo doesn't support specified engine: PaddlePaddle

### ISSUE THREAD

**Issue by 385589640** [deepjavalibrary/djl#2401]
ubuntu 20.04 throw ModelZoo doesn't support specified engine: PaddlePaddle

**Comment by frankfliu** [comment]
Can you share your `build.gradle` (or `pom.xml`) file and your code snippet?

**Comment by 385589640** [comment]
> Can you share your `build.gradle` (or `pom.xml`) file and your code snippet?

Thank you. I found a solution for https://github.com/deepjavalibrary/djl/issues/940
