### ISSUE TITLE
Add support for Tensor.unique

### ISSUE THREAD

**Issue by tipame** [deepjavalibrary/djl#2407]
## Description

Hello, i't trying to add Tensor.unique function implementation for pytorch engine but fail to call native implementation.
There are two reloaded implementations. Python impl looks like:
```
    if dim is not None:
        output, inverse_indices, counts = _VF.unique_dim(input, dim, sorted=sorted, return_inverse=return_inverse, return_counts=return_counts,)
    else:
        output, inverse_indices, counts = torch._unique2(input, sorted=sorted, return_inverse=return_inverse, return_counts=return_counts)
```
where _VF is defined as:
```
self.vf = torch._C._VariableFunctions
```
I successfuly implement call for **_unique2**:
```
JNIEXPORT jlongArray JNICALL Java_ai_djl_pytorch_jni_PyTorchLibrary_torchUnique(
    JNIEnv* env, jobject jthis, jlong jself, jboolean jsorted, jboolean jreturn_inverse, jboolean jreturn_counts) {
  API_BEGIN()
  const auto* tensor_ptr = reinterpret_cast<torch::Tensor*>(jself);
  std::tuple<torch::Tensor, torch::Tensor, torch::Tensor> outputs = torch::_unique2(*tensor_ptr, jsorted, jreturn_inverse, jreturn_counts);
  // process output
}
```
but i can't find out way to call **unique_dim** implementation:
```
JNIEXPORT jlongArray JNICALL Java_ai_djl_pytorch_jni_PyTorchLibrary_torchUnique(
    JNIEnv* env, jobject jthis, jlong jself, jboolean jsorted, jboolean jreturn_inverse, jboolean jreturn_counts, jint jdim) {
  API_BEGIN()
  const auto* tensor_ptr = reinterpret_cast<torch::Tensor*>(jself);
  std::tuple<torch::Tensor, torch::Tensor, torch::Tensor> outputs = torch::???::_unique2(*tensor_ptr, jdim, jsorted, jreturn_inverse, jreturn_counts);
  // process output
}
```` 
Please help me resolve how to call torch._C._VariableFunctions 

## References
https://pytorch.org/docs/stable/generated/torch.unique.html#torch.unique

**Comment by KexinFeng** [comment]
It looks like it is relavant to `aten::unique_dim`, which is generated cpp code. See `build/aten/src/ATen/core/ATenOpList.cpp`. 
Maybe you can just implement the `unique` without dim.

Another issue is that, if the dim of unique is specified for example dim=1, is it possible that the output tensor's row will have different lengths?

**Comment by tipame** [comment]
Hello, i can't see no ATenOpList.cpp, only ATenOpList.h, and have no idea how to declare/import required function (i have no experience in c++).
Actualy i need exactly unique for dimention = 1.
For any rank tensor - desired dimension will include only unique values (unique tensors).
So if tensor A has a shape [3, 4, 2],  A.unique(dim=1) may have a shape [3, 2, 2].

**Comment by KexinFeng** [comment]
Could you open a PR, so that we can directly experiment on top of your code?

**Comment by tipame** [comment]
https://github.com/deepjavalibrary/djl/pull/2415
I create 2 implementations (as describe erlier).
There are some other changes in PR (bmm and xlogy functions - pytorch implementations only).

**Comment by KexinFeng** [comment]
Cool. Thank you for your very nice contribution! I'll review it. 

Also, I have implemented the `unique_dim` too. It turns out that, even though `aten::unique_dim` is generated code (by torchgen/gen.py from Function.h), in JNI, there is no problem in just including this library by `#include <ATen/ops/unique_dim.h>`.

I will merge my implementation first and then your PR2415 can overwrite my mine.
