### ISSUE TITLE
add support for pytorch cudaStream

### ISSUE THREAD

**Issue by jestiny0** [deepjavalibrary/djl#2420]
## Description

I noticed that my current TorchScript model, which includes feature processing (using CPU) and model computation (using GPU), has low GPU utilization (30-40%). I found that PyTorch provides an API similar to cpu multi-threaded called "cudaStream". Is DJL considering introducing this feature?

**Will this change the current api? How?**
add paramaters like `ai.djl.pytorch.num_threads`

**Who will benefit from this enhancement?**
Increase GPU utilization.
## References

- list reference and related literature
 https://github.com/pytorch/pytorch/issues/16614
- list known implementations
The following code is a demo generated by ChatGPT
```
#include <torch/torch.h>
#include <iostream>
#include <thread>

// define a function to run inference on a CUDA stream
void runInference(torch::jit::script::Module& module,
                  torch::Tensor input,
                  at::cuda::CUDAStream& stream) {
    at::cuda::CUDAGuard guard(input.device());
    input = input.to(at::kCUDA, true, stream);
    auto output = module.forward({input}).toTensor();
    // synchronize stream before exiting
    at::cuda::CUDAStreamGuard syncGuard(stream);
    syncGuard.synchronize();
}

// define a function to create a new CUDA stream
at::cuda::CUDAStream newStream() {
    at::cuda::CUDAStream stream = at::cuda::getStreamFromPool();
    return stream;
}

int main() {
    // load model and move to GPU
    torch::jit::script::Module module = torch::jit::load("model.pt");
    module.to(at::kCUDA);
    // create two input tensors and move to GPU
    torch::Tensor input1 = torch::randn({1, 3, 224, 224});
    torch::Tensor input2 = torch::randn({1, 3, 224, 224});
    input1 = input1.to(at::kCUDA);
    input2 = input2.to(at::kCUDA);
    // create two CUDA streams
    at::cuda::CUDAStream stream1 = newStream();
    at::cuda::CUDAStream stream2 = newStream();
    // create two threads and run inference on different streams
    std::thread thread1(runInference, std::ref(module), std::ref(input1), std::ref(stream1));
    std::thread thread2(runInference, std::ref(module), std::ref(input2), std::ref(stream2));
    // wait for threads to finish
    thread1.join();
    thread2.join();
    return 0;
}
```

**Comment by frankfliu** [comment]
@jestiny0 

Thanks for reporting this issue. We are aware of this optimization, but never get chance to work on it. Are you interested in contributing this feature?

**Comment by jestiny0** [comment]
@frankfliu 
Well, I can try to add it in my spare time if you don't have time to do this optimization right now.

**Comment by jestiny0** [comment]
My team has already submitted the relevant changes and merged them, and I can close this issue~
