### ISSUE TITLE
NDArray.getInt(index), .getDouble(index), etc cause memory leak

### ISSUE THREAD

**Issue by ptrxwsmitt** [deepjavalibrary/djl#2426]
## Description
Methods of NDArray, which use the getScalar()-method internally are causing a memory leak (of native memory), because getScalar() creates an NDResource, which is not closed internally and cannot be closed from the outside. 

### Expected Behavior
No Memory leak

### Error Message
No message - JVM crash because out of memory error

## How to Reproduce?
Run Microbenchmark on a VM with limited RAM on a big NDArray with a lot of NDArray.getInt(index) calls (or similar getter method). This will cause native memory (not java managed memory) to stack up and not returning the memory to the system.

### Steps to reproduce
see above

## What have you tried to solve it?
Our Workaround is to reimplemented the getters via a Utils Class. It works this way so far, but this might also affect other projects as well.

## Environment Info

mxnet-native-mkl but it might also affect other native implementations, because java resource pointer is not closed properly.

**Comment by KexinFeng** [comment]
Could you specify on which engine you saw this memory leak? You mentioned `mxnet-native-mkl`. So if I assume the issue is on MXNet engine. But actually the getter on MXNet engine is not touched since very old version, for example, DJL 0.17.0. 

You mentioned 

> causing a memory leak (of native memory), because getScalar() creates an NDResource, which is not closed internally

it looks like you've found the root cause. Could you point out a litte more specifically about which part of the code creates an NDResources that is not closed?

**Comment by ptrxwsmitt** [comment]
Thanks for looking into it. Yes we are using the MXNet Engine. We are currently using DJL 0.17 because of another issue we are currently facing with later versions.
But I think it is mainly Java-Related, because an AutoCloseable is not closed and cannot be closed from outside the method call.

I'll try to show what I mean:

Within the [NDArray](https://github.com/deepjavalibrary/djl/blob/04cf34659d9977d1712b1d33a0917062f943f983/api/src/main/java/ai/djl/ndarray/NDArray.java) we have the following method.
```
    default long getLong(long... indices) {
        return getScalar(indices).toLongArray()[0];
    }
```

`getScalar(indices)` creates and returns an NDArray, which is AutoCloseable and which is not closed but also not returned, because it is directly converted into java long[]. The NDArray created by `getScalar(indices)` will be kept open internally as a resource pointer and cannot be closed because it is de-referenced after the conversion. 

Possible Solution, which closes the created NDArray :
```
    default long getLong(long... indices) {
        try (NDArray scalar = getScalar(indices)) {
            return scalar.toLongArray()[0];
        }
    }
```

Our workaround, which solved the memory leak for us, was to write an alternative getLong() Method:

```
    public long getLong(final NDArray ndArray, long... indices) {
        try (NDArray scalar = ndArray.getScalar(indices)) {
            return scalar.toLongArray()[0];
        }
    }
```

The same applies to getDouble(long... indices), getFloat(long... indices), ....

**Comment by KexinFeng** [comment]
Thanks for spotting this issue. It is solved now.
