### ISSUE TITLE
有没有使用python model进行前后处理的详细文档

### ISSUE THREAD

**Issue by yingchen066** [deepjavalibrary/djl#2435]
最近正在尝试把公司里python的推理代码 通过djl移植到java平台，但是其中遇到的最大的阻力就是前后处理的相关代码，python中很多音视频相关的处理库以及其他的一些api在java中并没有完全一致或相近的实现库，因为我们希望通过将前后处理放到python中执行的方式解决这个问题，但是djl中关于python model的部分代码并没有上传到github，同时文档写的也比较简单，希望有大佬可以提供更加详细的python model使用文档，或者带有一定说明的case，获取有更好的方式来进行前后处理也欢迎提供

**Comment by lanking520** [comment]
@zachgk I believe Esemble model will help in this case. User would like to use
- python preprocess
- Java inference
- Python post process

**Comment by zachgk** [comment]
Yeah. One option is to look into [DJL Serving](http://docs.djl.ai/docs/serving/index.html) for a full model-server or the [WorkLoadManager](http://docs.djl.ai/docs/serving/wlm/index.html) of it. From the WLM, you can use it to run the DJL Python Engine to run preProcess and postProcess code

**Comment by frankfliu** [comment]
@yingchen066 

I created a demo: https://github.com/deepjavalibrary/djl-demo/tree/master/development/python

We will create Esmeble model (workflow) demo soon.

**Comment by frankfliu** [comment]
Feel free to reopen this issue if you have further questions.
