### ISSUE TITLE
Running on Arm CPU

### ISSUE THREAD

**Issue by LobsterMan123** [deepjavalibrary/djl#2463]
I've noticed that using DJL requires more than simply altering a Maven pom file and since I wish to do development on a machine that uses an Arm pricessor, I would like to know if DJL is currently able to compile and execute on an Android tablet running on Arm so that actual Java coding can be done on an Android tablet?

For additional info, I would like to use DJL on the Termux app which is a popular Linux emulator for Android (but some of its internal setup differs slightly from an actual Linux OS).  Thanks for any help you can provide.

LM

**Comment by frankfliu** [comment]
@LobsterMan123 

We do support Android: https://docs.djl.ai/android/index.html

You can find android examples here:
1. [PyTorch examples](https://github.com/deepjavalibrary/djl-demo/tree/master/android/pytorch_android)
2. [OnnxRuntime examples](https://github.com/deepjavalibrary/djl-demo/tree/master/android/onnxruntime_android)

**Comment by LobsterMan123** [comment]
Thank you for this.  Now what I'd like to do is to be able to load a data file with data where each line in the file has 3 predictor variables and one response variable (a binary 0 or 1) and I'd like the AI to train on such a data file so that I can then feed the trained model another data file containing new data (but missing the response variable) and have the code provide me with binary predictions for this new data file.

Can DJL do the above for the Android system?  I noticed the provided examples appear to consist of trained models that look at other tasks apart from the described above task.  Thanks.

LM
