### ISSUE TITLE
Add Profiling tools for Onnx Engine

### ISSUE THREAD

**Issue by dhrubo-os** [deepjavalibrary/djl#2471]
## Description

DJL has profiler support for `MXNet` and `PyTorch` [[REF](https://djl.ai/docs/development/profiler.html)]. I would like to request to extend this profiler support for `ONNX` engine also.

## References

- https://djl.ai/docs/development/profiler.html
- https://onnxruntime.ai/docs/performance/tune-performance/profiling-tools.html#in-code-performance-profiling

**Comment by frankfliu** [comment]
You can enable onnxruntime profiler using the following code:

```
            Path modelDir = Paths.get("YOUR_MODEL_DIR");
            Model model = Model.newInstance("my_model");
            OrtSession.SessionOptions ortOptions = new OrtSession.SessionOptions();
            ortOptions.enableProfiling("out.txt");
            Map<String, Object> options = new ConcurrentHashMap<>();
            options.put("sessionOptions", ortOptions);
            model.load(modelDir, "mymodel.onnx", options);

```

**Comment by frankfliu** [comment]
See: https://github.com/deepjavalibrary/djl/pull/2472

With this PR, you can enable profiler in a more elegant way:

```
Criteria<Image, Classifications> criteria =
        Criteria.builder()
            .optOption("profilerOutput", "build/testOrtProfiling")
            ...
            .build()
```
