### ISSUE TITLE
DJL load model in cpu throw error: Could not run `aten::empty_strided` with arguments from the `CUDA` backend

### ISSUE THREAD

**Issue by RidiculousDoge** [deepjavalibrary/djl#2474]
I got an error message as the issue: https://github.com/deepjavalibrary/djl/issues/1618. In DJL, I used cpu to load the model, and the djl has successfully recognized the `libtorch_cpu.so`. However the djl raises error when I try to load the model, indicating that it used CUDA backend instead of CPU.

I wonder if this could be a problem of my pytorch model. The `model` was trained in GPU. After that, I used the following:
```python
scripted_model = torch.jit.script(model)
scripted_model.eval()
scripted_model = scripted_model.to("cpu")
with open(filepath,"wb") as f:
    torch.jit.save(scripted_model,f)
```

The model has been successfully saved, and then I load the model in djl but encountered this error. 

---
I tried to train the model using cpu from scratch, and the load procedure succeeded. Seems like a model trained in gpu cannot be used in djl cpu mode even if it has been transferred to cpu and properly saved using `torch.jit.script`.

_Originally posted by @RidiculousDoge in https://github.com/deepjavalibrary/djl/issues/1618#issuecomment-1477374527_

**Comment by frankfliu** [comment]
@RidiculousDoge 

Can you can to use `jit.trace()` instead of `jit.script()`, the error may related to your model code. `model.to("cpu")` only convert weight to cpu, the code may still remember the device information.

**Comment by RidiculousDoge** [comment]
> @RidiculousDoge
> 
> Can you try to use `jit.trace()` instead of `jit.script()`, the error may related to your model code. `model.to("cpu")` only convert weight to cpu, the code may still remember the device information.

It works fine to use `torch.jit.trace` for me. But I still hope to use `script` to fully serialize the model. Tks for the answer.
