### ISSUE TITLE
the predict time is slower than the onnx runtime 

### ISSUE THREAD

**Issue by linlihuiyang** [deepjavalibrary/djl#2483]
## Description

when I am using the djl with the onnx runtime and hybrid engine (pytorch,tensorflow,mxnet), i found that the
model predict takes more time than the way of direct using the OnnxRuntime
I think it's caused by multiple engines
and i want to know how to fix it  

thank you

**Comment by frankfliu** [comment]
You can disable hybrid engine by set system properties:

```
System.setProperty("ai.djl.onnxruntime.disable_alternative", "true");
```

However, once you disable hybrid engine, you have to do all pre/post processing in pure java. Means you have to manually prepare NDList in your Translator without NDArray operations.

**Comment by linlihuiyang** [comment]
Thanks for the apply，I added the system properties, And when I performed model predict, I found an error, and then I looked at the source code 
 The 52th  line of StackBatchifier.java 
NDArray stacked = NDArrays.stack(new NDList(inputsOfKind));  there have a problem , the onnxRuntime do not support stack method, so what should I do

**Comment by linlihuiyang** [comment]
I found  NoBatchifyTranslator can fix it,  thank you
