### ISSUE TITLE
OPT_OUT_TRACKING system property is ignored 

### ISSUE THREAD

**Issue by gravitation1** [deepjavalibrary/djl#2489]
## Description
[The documentation on telemetry](https://docs.djl.ai/docs/telemetry.html) specifies that if the `OPT_OUT_TRACKING` system property is set then telemetry will be disabled. However, [the underlying code](https://github.com/deepjavalibrary/djl/blob/8392ab1bce343ecbd9d054b2f4295591f41b08fa/api/src/main/java/ai/djl/util/Ec2Utils.java#L95-L99) only checks for `OPT_OUT_TRACKING` as an environment variable.

### Expected Behavior
Telemetry is disabled when the OPT_OUT_TRACKING system property is set to a value of `true`.

### Error Message
N/A - The system property is ignored and telemetry is reported home.

## How to Reproduce?
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)

### Steps to reproduce
1. In the Java program, execute `System.setProperty("OPT_OUT_TRACKING", "true");`
2. Instantiate of a `HuggingFaceTokenizer`.
3. Break in [Ec2Utils#callHome](https://github.com/deepjavalibrary/djl/blob/8392ab1bce343ecbd9d054b2f4295591f41b08fa/api/src/main/java/ai/djl/util/Ec2Utils.java#L100), after the telemetry checks have executed.

## What have you tried to solve it?
Working around the issue by setting `System.setProperty("offline", "true")`.

**Comment by frankfliu** [comment]
@gravitation1 
Thanks for reporting this issue. I created a PR to fix the issue.
