### ISSUE TITLE
drawBoundingBoxes

### ISSUE THREAD

**Issue by kameronren** [deepjavalibrary/djl#2497]
## Description
(A clear and concise description of what the bug is.)

### Expected Behavior
(what's the expected behavior?)

### Error Message
(Paste the complete error message, including stack trace.)

## How to Reproduce?
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

## Environment Info

Please run the command `./gradlew debugEnv` from the root directory of DJL (if necessary, clone DJL first). It will output information about your system, environment, and installation that can help us debug your issue. Paste the output of the command below:

```
PASTE OUTPUT HERE
```

**Comment by kameronren** [comment]
more-infomation is in below:
1. the code "img.drawBoundingBoxes(detectedObjects);" is not work!  when I perform the code, there is no any boundingBoxes in the img。

**Comment by frankfliu** [comment]
Can you print out your `detectedObjects`?

**Comment by kameronren** [comment]
yes， i can。

[
	class: "s=0.75, r=1", probability: 1.00000, bounds: [x=40.000, y=40.000, width=421.000, height=421.000]
	class: "s=0.5, r=1", probability: 1.00000, bounds: [x=110.000, y=110.000, width=280.000, height=280.000]
	class: "s=0.25, r=1", probability: 1.00000, bounds: [x=180.000, y=180.000, width=140.000, height=140.000]
	class: "s=0.75, r=2", probability: 1.00000, bounds: [x=-47.000, y=102.000, width=595.000, height=298.000]
	class: "s=0.75, r=0.5", probability: 1.00000, bounds: [x=102.000, y=-47.000, width=298.000, height=595.000]
]

**Comment by kameronren** [comment]
[
class: "s=0.75, r=1", probability: 1.00000, bounds: [x=40.000, y=40.000, width=421.000, height=421.000]
class: "s=0.5, r=1", probability: 1.00000, bounds: [x=110.000, y=110.000, width=280.000, height=280.000]
class: "s=0.25, r=1", probability: 1.00000, bounds: [x=180.000, y=180.000, width=140.000, height=140.000]
class: "s=0.75, r=2", probability: 1.00000, bounds: [x=-47.000, y=102.000, width=595.000, height=298.000]
class: "s=0.75, r=0.5", probability: 1.00000, bounds: [x=102.000, y=-47.000, width=298.000, height=595.000]
]




65340364
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "deepjavalibrary/djl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月3日(星期一) 凌晨0:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [deepjavalibrary/djl] drawBoundingBoxes (Issue #2497)





 
Can you print out your detectedObjects?

**Comment by frankfliu** [comment]
@kameronren 
Our BoundingBox value is not absolute pixel position. It's the percentile to the image width and height. the value should between 0 - 1. Greater than 1 means the box is out side of the image.

And I also noticed you have negative values, the result doesn't seems correct to me.

**Comment by kameronren** [comment]
thanks
