### ISSUE TITLE
support torch 2.0?

### ISSUE THREAD

**Issue by jestiny0** [deepjavalibrary/djl#2503]
Do you have plans to support torch 2.0? Or are you just looking for forward compatibility with previous versions, so that it can load model and be served normally without supporting new features in torch 2.0?

**Comment by lanking520** [comment]
PyTorch 2.0 doesn't introduce many breaking changes, we are still evaluating this. Will come up with a date soon

**Comment by jestiny0** [comment]
@frankfliu @lanking520 
I see that you have prepared the latest version, [PR](https://github.com/deepjavalibrary/djl/pull/2532) is there a specific release date? within a week or within a month?

**Comment by frankfliu** [comment]
It's on maven already: https://search.maven.org/search?q=g:ai.djl.pytorch

We are still preparing the document. Release notes will come a bit late.

**Comment by jestiny0** [comment]
Great job! I'm going to test it now and if there are any issues, I'll provide feedback as soon as possible. You can close this issue now.
