### ISSUE TITLE
about tensorflow-native-cu113 probably not  using gpu to inference

### ISSUE THREAD

**Issue by guojian0614** [deepjavalibrary/djl#2573]
## Description

(A clear and concise description of what the feature is.)

Will this change the current api? How?

Who will benefit from this enhancement?

## References

- list reference and related literature
- list known implementations

        <dependency>
            <groupId>ai.djl.tensorflow</groupId>
            <artifactId>tensorflow-native-cu113</artifactId>
            <classifier>linux-x86_64</classifier>
          <version>2.7.1</version>
        </dependency>

![image](https://user-images.githubusercontent.com/29422500/235093305-09b95f36-2bf6-4209-b8bf-c81b5c4f49b9.png)

if i set predict device is gpu ，the preprocess output ndList's device indeed gpu 。
but continues inference output ndList‘s device is always cpu.
and i compare DJL inference speed to the docker iamge of tensorflow/serving  , DJL  spend time is double for tensorflow/serving 
i want to asking what do i do  can help me certain i indeed used gpu to inference?

**Comment by frankfliu** [comment]
DJL by default will use GPU if it detected the cuda version is compatible with the engine.

Can you try run djl-bench on your system and see if DJL can pick up GPU: https://github.com/deepjavalibrary/djl-serving/tree/master/benchmark

**Comment by guojian0614** [comment]
> DJL by default will use GPU if it detected the cuda version is compatible with the engine.
> 
> Can you try run djl-bench on your system and see if DJL can pick up GPU: https://github.com/deepjavalibrary/djl-serving/tree/master/benchmark

![image](https://user-images.githubusercontent.com/29422500/236097146-8002130b-b6a1-403a-bada-577e79e57691.png)

unfortunatelly，the link of you gave me have nothing.

**Comment by guojian0614** [comment]
> DJL by default will use GPU if it detected the cuda version is compatible with the engine.
> 
> Can you try run djl-bench on your system and see if DJL can pick up GPU: https://github.com/deepjavalibrary/djl-serving/tree/master/benchmark

![image](https://user-images.githubusercontent.com/29422500/236098318-a477660e-b1de-4a10-bd6e-736a2fd3aa81.png)
![image](https://user-images.githubusercontent.com/29422500/236098348-06cdc94a-f619-4640-bd62-0f0d53872ab7.png)
@frankfliu 
unfortunatelly，the link of you gave me has nothing.

**Comment by frankfliu** [comment]
@guojian0614 
The link works find for me. Are able to see anything in djl-serving github repo?

**Comment by guojian0614** [comment]
> 

@frankfliu thank you , it is github official problem

**Comment by guojian0614** [comment]
@frankfliu 
now ,i already download djl-serving project and run it accord to you suggest 
the example used engine is PyTorch ， the dependencies is 
runtimeOnly("ai.djl.onnxruntime:onnxruntime-engine") { 
exclude group: "com.microsoft.onnxruntime", module: "onnxruntime" 
} 
runtimeOnly "com.microsoft.onnxruntime:onnxruntime_gpu:${onnxruntime_version}" 
 
the following code don't detected gpu 
“ Device device = Engine.getEngine(arguments.getEngine()).defaultDevice();” 
![image](https://user-images.githubusercontent.com/29422500/236418523-19c3d1fd-7917-44d6-8381-54147810474d.png) 
 
if i force used gpu ，it will alert "No matching cuda flavor for win-x86_64 found: cu113"

What should I do on next？

**Comment by frankfliu** [comment]
I'm confused:
1. Are you running on Windows or Linux? in your earlier dependency, you use `linux-x86_64`
2. Which engine are you using? you add `onnxruntime` to your dependency
3. Which CUDA version is installed on your system?
4. How you force to use GPU?

**Comment by guojian0614** [comment]
> 2\. using
@frankfliu 
1. i run it on the win10-x86_64 system 
2. we runed code is your serving project benchmark module provide
![image](https://user-images.githubusercontent.com/29422500/236591848-8038a625-4c53-4375-bed8-ad616f092a2b.png)
3.
![image](https://user-images.githubusercontent.com/29422500/236591891-2cf9dfcb-b713-4a59-a0be-62c24d29ddc2.png)
the gpu environment sure no problem，that's adjusted according to you before suggest ，in my custom DJL code preprocess indeed used gpu。
4.
![image](https://user-images.githubusercontent.com/29422500/236592058-f4c4e833-f4ce-42b2-b900-7d428c4235d0.png)
just replace read line point code line to “  Device devic= Device.gpu();”

**Comment by frankfliu** [comment]
A few things you can try:
1. get latest djl-serving source code (using DJL 0.23.0-SANPSHOT), 0.21.0 doesn't recognize CUDA 12.1
2. or set env var: `export PYTORCH_FLAVOR=cu117` and `export PYTORCH_VERSION=1.13.1`

**Comment by guojian0614** [comment]
@frankfliu 
hello，Sorry to trouble you again！
I run it according to your suggest ,threw new exception follow 

Caused by: java.lang.UnsatisfiedLinkError: C:\Users\lenovo\.djl.ai\pytorch\1.13.1-cu117-win-x86_64\torch_cuda_cpp.dll: Caused by: java.lang.UnsatisfiedLinkError: C:\Users\lenovo\.djl.ai\pytorch\1.13.1-cu117-win-x86_64\torch_cuda_cpp.dll: �Ҳ���ָ���ĳ���
	at java.lang.ClassLoader$NativeLibrary.load0(Native Method) ~[?:?]
	at java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442) ~[?:?]
	at java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498) ~[?:?]
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627) ~[?:?]
	at java.lang.Runtime.load0(Runtime.java:768) ~[?:?]
	at java.lang.System.load(System.java:1837) ~[?:?]
	at ai.djl.pytorch.jni.LibUtils.loadNativeLibrary(LibUtils.java:347) ~[pytorch-engine-0.22.1-SNAPSHOT.jar:?]
	at ai.djl.pytorch.jni.LibUtils.loadLibTorch(LibUtils.java:174) ~[pytorch-engine-0.22.1-SNAPSHOT.jar:?]
	at ai.djl.pytorch.jni.LibUtils.loadLibrary(LibUtils.java:78) ~[pytorch-engine-0.22.1-SNAPSHOT.jar:?]
	at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:53) ~[pytorch-engine-0.22.1-SNAPSHOT.jar:?]
	... 5 more
![image](https://user-images.githubusercontent.com/29422500/236740851-7f4a0289-5400-4268-994c-431e440a3000.png)

**Comment by frankfliu** [comment]
If you see UnsatisfiedLinkError, most like you you are missing some dependencies in your system (or not in PATH).

See: https://docs.djl.ai/docs/development/troubleshooting.html#unsatisfiedlinkerror-issue

**Comment by guojian0614** [comment]
> If you see UnsatisfiedLinkError, most like you you are missing some dependencies in your system (or not in PATH).
> 
> See: https://docs.djl.ai/docs/development/troubleshooting.html#unsatisfiedlinkerror-issue

![image](https://user-images.githubusercontent.com/29422500/236985481-3b066c28-5695-470a-8fc8-06c08abb9c20.png)

thanks，indeed torch_cuda.cpp.dll lack dependency

**Comment by codeMan2018** [comment]
> 您可以尝试以下几件事：
> 
> 1. 获取最新的 djl-serving 源代码（使用 DJL 0.23.0-SANPSHOT），0.21.0 无法识别 CUDA 12.1
> 2. 或设置环境变量：`export PYTORCH_FLAVOR=cu117`和`export PYTORCH_VERSION=1.13.1`

I have similar problem，my environment is as follows：
linux,gpu t4,tensorflow
CUDA: 113
ARCH: 75
DJL version: 0.23.0
ai.djl.util.Platform - Found placeholder platform from: cu113-linux-x86_64:2.10.1
Default Engine: TensorFlow:2.10.1, capabilities: [
        MKL,
]
TensorFlow Library: /usr/local/app/.djl.ai/tensorflow/2.10.1-cu113-linux-x86_64/libjnitensorflow.so

engine.hasCapability(StandardCapabilities.CUDA) is always false
 
![image](https://github.com/deepjavalibrary/djl/assets/38805586/8583d7ab-5d9a-44b8-b15b-df08fca5be36)
![image](https://github.com/deepjavalibrary/djl/assets/38805586/073484ff-adcd-46f7-b843-7bb484875a60)
