### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by 503612012** [deepjavalibrary/djl#2577]
想问一下，使用ubuntu:20.04镜像启动的docker容器，在使用djl的时候，起不来，但是在其他机器上就可以正常运行，报错的机器有这样的信息：
Register to memory mapping:

RAX=0xfffffffffc99d016 is an unknown value
RBX=0x00007f9118c46710 is pointing into the stack for thread: 0x00007f911400a800
RCX=0x00007f90abd4028a: <offset 0xebf28a> in /root/.djl.ai/paddle/2.2.2-cpu-linux-x86_64/libpaddle_inference.so at 0x00007f90aae81000
RDX=0x0000000000000000 is an unknown value
RSP=0x00007f9118c466c0 is pointing into the stack for thread: 0x00007f911400a800
RBP=0x00007f9118c46760 is pointing into the stack for thread: 0x00007f911400a800
RSI=0x00007f90af3a2cc3: <offset 0x4521cc3> in /root/.djl.ai/paddle/2.2.2-cpu-linux-x86_64/libpaddle_inference.so at 0x00007f90aae81000
RDI=0x00007f91149c51b0 is an unknown value
R8 =0x00007f91149c5220 is an unknown value
R9 =0x00007f9119f06450: <offset 0x168450> in /lib/x86_64-linux-gnu/libc.so.6 at 0x00007f9119d9e000
R10=0x00007f91140008d0 is an unknown value
R11=0x65645f7265676165 is an unknown value
R12=0x00007f9118c46710 is pointing into the stack for thread: 0x00007f911400a800
R13=0x0000000000000016 is an unknown value

**Comment by frankfliu** [comment]
We have ubuntu 20.04 nightly build, it's work fine: https://github.com/deepjavalibrary/djl-demo/actions/runs/4849936306/jobs/8642389889

Not sure what cause this error.
