### ISSUE TITLE
The latest version released on the official website is 0.22.1 instead of 0.22.0?

### ISSUE THREAD

**Issue by jestiny0** [deepjavalibrary/djl#2580]
I previously raised an [issue](https://github.com/deepjavalibrary/djl/issues/2503) about upgrading DJL to the latest version and upgrading PyTorch to 2.0.0. At that time, the version I received from the Maven repository was 0.22.0, and I also tested and upgraded all my production services to 0.22.0. 
However, I found that the latest version released on the DJL official website is 0.22.1 instead of 0.22.0. 

My key questions are:

1. What are the key changes made in 0.22.1 compared to 0.22.0?
2. Is it necessary for me to upgrade to 0.22.1?

**Comment by frankfliu** [comment]
0.22.0 default use PyTorch 2.0.0, which we found quite a few issues. in 0.22.1 there are two critical updates:
1. downgrade default PyTorch version to 1.13.1 in DJL's BOM
2. Fixed bug in NeuronUtils which doesn't detect neuron core correctly.

If you are not using PyTorch 2.0.0, you should be fine.

**Comment by jestiny0** [comment]
We upgraded to DJL 0.22.0-2.0.0 solely for the purpose of preparing for training models with PyTorch 2.0.0. We are currently planning to upgrade our training PyTorch version from 1.12.1 to 2.0.0. Are there any concerns with this upgrade?

**Comment by frankfliu** [comment]
We observed cuda error when running multi-threading inference on GPU: https://github.com/pytorch/pytorch/issues/99372

If you are using mpi in training/inference in python, it will crash as well.

PyTorch 2.0.1 is right at the corner, we test 2.0.1 and see if it's stable.

**Comment by jestiny0** [comment]
@frankfliu 
I saw that pytorch 2.0.1 has been officially released. Do you have a specific plan for when to release DJL that supports version 2.0.1?
