### ISSUE TITLE
about  speed slowly for  image buid from byte array!!!

### ISSUE THREAD

**Issue by guojian0614** [deepjavalibrary/djl#2584]
## Description

(A clear and concise description of what the feature is.)

Will this change the current api? How?

Who will benefit from this enhancement?

## References

- list reference and related literature
- list known implementations
- 
![image](https://user-images.githubusercontent.com/29422500/236432432-c6508e9e-65c6-4e7a-a57b-c49d7c7e91d1.png)

i used imageIO build image from byte array before , it is very slowly.
so ,i replace it to openCV , it's indeed faster than before ,but still takes 20ms.
that's only build image!!!  wether  is too slowly? 
Doesn't make it faster to build images?The python do same thing just takes less than 10ms. at fastest time, maybe less than 5ms.

**Comment by guojian0614** [comment]
![Uploading image.png…]()  the most time was taken by this native method

**Comment by guojian0614** [comment]
the most time was taken by this native method

![image](https://user-images.githubusercontent.com/29422500/236443498-aa260c89-e515-4cbd-a863-5b449e4e3f36.png)

**Comment by frankfliu** [comment]
Many python library also use opencv underneath. Do you have benchmark showing python is faster?

**Comment by guojian0614** [comment]
> Many python library also use opencv underneath. Do you have benchmark showing python is faster?

@frankfliu 
first，thank you for you reply  in time。

hitherto ad, i didn't used your serving benchmark module showing python ，but before used DJL ,i used python tool pillow in python project ，indeed faster more。 

now,we just want transfor predict runtime project to java，then found it slowly than python。
 
this code line just a one step in predict ，but time proportion reach whole process 1/6 or even more.

conceivable ， the interface qps is lowly  and tps should be lower more 。

**now ， pressure test whole process for both projects（python and java ），result python tps 23 ，qps 26。DJL  tps 11 ，qps 25（that cause by used reactive framwork）**

anyway ，just one codeline handle a image byte array take time reached 20-25ms，indeed slowly。

both projects has apparent gap of performance.
