### ISSUE TITLE
where could get "ai.djl:bom" and tensorflow version relation ?

### ISSUE THREAD

**Issue by guojian0614** [deepjavalibrary/djl#2592]
## Description

(A clear and concise description of what the feature is.)

Will this change the current api? How?

Who will benefit from this enhancement?

## References

- list reference and related literature
- list known implementations

title is question。

**Comment by frankfliu** [comment]
See: https://docs.djl.ai/bom/index.html

**Comment by guojian0614** [comment]
@frankfliu thanks
