### ISSUE TITLE
eclipse  debug 过程中看不到ndarry 的元素内容 ，只能看到 ”ND: (30, 6) cpu() float32“，写前后处理的时候非常不方便，有没有什么办法

### ISSUE THREAD

**Issue by lymgithub** [deepjavalibrary/djl#2602]
eclipse  debug 过程中看不到ndarry 的元素内容 ，只能看到 ”ND: (30, 6) cpu() float32“，写前后处理的时候非常不方便，有没有什么办法

**Comment by frankfliu** [comment]
See: https://docs.djl.ai/docs/development/development_guideline.html#debug

**Comment by frankfliu** [comment]
You set Eclipse system properties to change the default NDArray.toString() behavior:

```
-Djshell=true
```
