### ISSUE TITLE
Huggingface Tokenizer not working as expected for basic_tokenize=false

### ISSUE THREAD

**Issue by balachandarsv** [deepjavalibrary/djl#2621]
## Description
When trying to tokenize code and decode the response is different in python and java.
In python we set
tokenizer.do_basic_tokenize = false

But when tried setting the same in java didn't work.

Example:
Input string
```
import ai.djl.huggingface.tokenizers.Encoding;\n\npublic class Test {\n	public static void main(String[] args) {\n
```
Output String:
```
[CLS] import ai. djl. huggingface. tokenizers. Encoding ; \ n \ npublic class Test { \ n public static void main ( String [ ] args ) { \ n [SEP]

```
### Expected Behavior

Expected output
```
[CLS] import ai.djl.huggingface.tokenizers.Encoding;\n\npublic class Test {\n	public static void main(String[] args) {\n [SEP]


```

## How to Reproduce?
Use any tokenizer and try to tokenize and decode the above string.

## What have you tried to solve it?

1. Tried setting options 
map.put("do_basic_tokenize", "false");
map.put("addSpecialTokens", "true");

No changes in response

**Comment by frankfliu** [comment]
Can you provide your python code and model?

**Comment by balachandarsv** [comment]
[test.zip](https://github.com/deepjavalibrary/djl/files/11572162/test.zip)

I have attached a sample python code and tokenizer json. @frankfliu

**Comment by frankfliu** [comment]
@balachandarsv 

For your original question, you need set `addSpecialTokens` for false:

```
        Map<String, String> options = new ConcurrentHashMap<>();
        options.put("addSpecialTokens", "false");
```

In python code, `do_basic_tokenize` actually not using FastTokenizer, you can use `WordpieceTokenizer` in DJL if you only want to do basic tokenize.

**Comment by balachandarsv** [comment]
Thanks for the solution. @frankfliu But how to load an existing tokenizer.json using the WordpieceTokenizer. I couldn't find any docs. Also is there any way to import the tokenizer.json as Vocabulary

**Comment by frankfliu** [comment]
You can download `vocab.txt` file from huggingface hub, or when you use python `tokenizer.save_pretrained()` function, it usually save both `vocab.txt` file and `tokenizer.json` file.

```
        Path file = Paths.get("vocab.txt");
        DefaultVocabulary vocab =
                DefaultVocabulary.builder()
                        .addFromTextFile(file))
                        .optUnknownToken("[UNK]")
                        .build();

        BertFullTokenizer tokenizer = new BertFullTokenizer(vocab, false);
```
