### ISSUE TITLE
Is DJL support feature of tokenizer like "return offset mappings" in huggingface tokenizers?

### ISSUE THREAD

**Issue by Howardqlz** [deepjavalibrary/djl#2624]
## Description

Is DJL support feature of tokenizer like "return offset mappings" in huggingface tokenizers?
Actually in tasks like ner,pos tagging this offset_mapping is necessary.

## References
https://huggingface.co/docs/transformers/v4.29.1/en/main_classes/tokenizer#transformers.PreTrainedTokenizerFast.__call__.return_offsets_mapping

**Comment by frankfliu** [comment]
You can get `Encoding` from `HuggingFaceTokenizer`, and call `Encoding.charTokenSpans()`

**Comment by Howardqlz** [comment]
> You can get `Encoding` from `HuggingFaceTokenizer`, and call `Encoding.charTokenSpans()`

Thank you, but i'm not sure, you mean `Encoding.getCharTokenSpans()`？

**Comment by frankfliu** [comment]
Yes, it returns `CharSpan[]`, each `CharSpan` contains each tokens start and end offset.

**Comment by Howardqlz** [comment]
> Yes, it returns `CharSpan[]`, each `CharSpan` contains each tokens start and end offset.

I got it, it works, thanks!
