### ISSUE TITLE
ai.djl.fasttext doesn't work on Apple M1

### ISSUE THREAD

**Issue by MartinoKhuanggaDH** [deepjavalibrary/djl#2638]
## Description

HI it seems like djl.fasttext is not working with Apple M1, can we add support for fasttext in Apple M1? Many Thanks!

## References
- Similar to sentencepiece [issue](https://github.com/deepjavalibrary/djl/issues/2323)

## Error message
```
java.io.IOException: Resource not found in classpath: native/lib/osx-aarch64/libjni_fasttext.dylib
```

**Comment by frankfliu** [comment]
@MartinoKhuanggaDH You can try our snapshot build tomorrow once nightly build is finished.
