### ISSUE TITLE
May I ask if DJL can use ChatGLM-6B（ https://github.com/THUDM/ChatGLM-6B ）Are you unfamiliar with DJL and would like to use it in company projects? Can you give me some examples?

### ISSUE THREAD

**Issue by kangerts** [deepjavalibrary/djl#2664]
May I ask if DJL can use ChatGLM-6B（ https://github.com/THUDM/ChatGLM-6B ）Are you unfamiliar with DJL and would like to use it in company projects? Can you give me some examples?

**Comment by frankfliu** [comment]
@kangerts 
We didn't try this model. But you should be able to try it out with our DJLServing: https://github.com/deepjavalibrary/djl-serving

Here is a few deploy python model examples: https://github.com/deepjavalibrary/djl-demo/tree/master/djl-serving/python-mode

And Large language model deployment blogpost:
- [Deploy Falcon-40B with large model inference DLCs on Amazon SageMaker](https://aws.amazon.com/blogs/machine-learning/deploy-falcon-40b-with-large-model-inference-dlcs-on-amazon-sagemaker/)
- [Build custom chatbot applications using OpenChatkit models on Amazon SageMaker](https://aws.amazon.com/blogs/machine-learning/build-custom-chatbot-applications-using-openchatkit-models-on-amazon-sagemaker/)
- [Deploying LLMs On Amazon SageMaker With DJL Serving](https://towardsdatascience.com/deploying-llms-on-amazon-sagemaker-with-djl-serving-8220e3cfad0c)
- [Achieve high performance with lowest cost for generative AI inference using AWS Inferentia2 and AWS Trainium on Amazon SageMaker](https://aws.amazon.com/blogs/machine-learning/achieve-high-performance-with-lowest-cost-for-generative-ai-inference-using-aws-inferentia2-and-aws-trainium-on-amazon-sagemaker/)
- [Deploy large models at high performance using FasterTransformer on Amazon SageMaker](https://aws.amazon.com/blogs/machine-learning/deploy-large-models-at-high-performance-using-fastertransformer-on-amazon-sagemaker/)

**Comment by kangerts** [comment]
> @kangerts We didn't try this model. But you should be able to try it out with our DJLServing: https://github.com/deepjavalibrary/djl-serving
> 
> Here is a few deploy python model examples: https://github.com/deepjavalibrary/djl-demo/tree/master/djl-serving/python-mode
> 
> And Large language model deployment blogpost:
> 
> * [Deploy Falcon-40B with large model inference DLCs on Amazon SageMaker](https://aws.amazon.com/blogs/machine-learning/deploy-falcon-40b-with-large-model-inference-dlcs-on-amazon-sagemaker/)
> * [Build custom chatbot applications using OpenChatkit models on Amazon SageMaker](https://aws.amazon.com/blogs/machine-learning/build-custom-chatbot-applications-using-openchatkit-models-on-amazon-sagemaker/)
> * [Deploying LLMs On Amazon SageMaker With DJL Serving](https://towardsdatascience.com/deploying-llms-on-amazon-sagemaker-with-djl-serving-8220e3cfad0c)
> * [Achieve high performance with lowest cost for generative AI inference using AWS Inferentia2 and AWS Trainium on Amazon SageMaker](https://aws.amazon.com/blogs/machine-learning/achieve-high-performance-with-lowest-cost-for-generative-ai-inference-using-aws-inferentia2-and-aws-trainium-on-amazon-sagemaker/)
> * [Deploy large models at high performance using FasterTransformer on Amazon SageMaker](https://aws.amazon.com/blogs/machine-learning/deploy-large-models-at-high-performance-using-fastertransformer-on-amazon-sagemaker/)
Okay, thank you.
