### ISSUE TITLE
The 'processor. Encode' and 'processor. Decode' methods of 'SentencePiece' cannot be used, and the 'SpTokenizer' in DJL cannot use the 'getProcessor' method in other classes. Is there any way?

### ISSUE THREAD

**Issue by kkangert** [deepjavalibrary/djl#2681]
The 'processor. Encode' and 'processor. Decode' methods of 'SentencePiece' cannot be used, and the 'SpTokenizer' in DJL cannot use the 'getProcessor' method in other classes. Is there any way?

**Comment by KexinFeng** [comment]
Could you provide the demo code to reproduce the problem?

Also about "the 'SpTokenizer' in DJL cannot use the 'getProcessor' method in other classes, do you think it is due to the Access Modifiers is not public enough?
