### ISSUE TITLE
Safetensor support for Java

### ISSUE THREAD

**Issue by gitarmartin** [deepjavalibrary/djl#2719]
## Description

Safetensors are https://huggingface.co/docs/diffusers/main/en/using-diffusers/using_safetensors

Java support would benefit all Java projects.

## References
- https://rentry.org/safetensorsguide
- https://github.com/huggingface/safetensors
- https://medium.com/@zergtant/what-is-safetensors-and-how-to-convert-ckpt-model-to-safetensors-13d36eb94d57
- https://github.com/Silver267/pytorch-to-safetensor-converter

**Comment by ZhaoGuoXin** [comment]
I am a java developer and my task is to develop a framework to publish AI models as service. Because a lot of stable-diffusion models are saved as .safetensors, if djl support safetensors would be greate.
