### ISSUE TITLE
Does `Create your first deep learning neural network` is out of sync with `model-zoo` ? Kernen Instalatioin verifycation 

### ISSUE THREAD

**Issue by kyxap** [deepjavalibrary/djl#2726]
Hi there,

I started looking in to your tutorial https://github.com/deepjavalibrary/djl/blob/master/jupyter/tutorial/01_create_your_first_network.ipynb 
and got strange feeling that the source code of project example (`model-zoo`) is outdated.

Tutorial says to add `maven` repo and snapshot but the example project uses `gradle` https://github.com/deepjavalibrary/djl/blob/master/model-zoo/build.gradle 

Also its not clear when and how `Jupyter` will be used and if there specific place for Jupyter and kernals installation because I see there 0 installed kernels are running.

![image](https://github.com/deepjavalibrary/djl/assets/3080529/2821d71a-0620-435e-8de6-2fb56b8b7a08)

Please let me know what I'm missing, thank you!

**Comment by zachgk** [comment]
The way that you build the examples and the Jupyter notebooks are slightly different. The model-zoo `build.gradle` is not for example purposes, but how the DJL project will internally build the `model-zoo` module.

If you are attempting to make a project using DJL, you can pick a build system:

- Jupyter notebooks - See https://github.com/deepjavalibrary/djl/blob/master/jupyter/README.md for install instructions
- Maven - See example pom.xml https://github.com/deepjavalibrary/djl/blob/master/examples/pom.xml
- Gradle - See example build.gradle https://github.com/deepjavalibrary/djl/blob/master/examples/build.gradle

Within the Jupyter system, you use the `%maven` system to add a maven repository. Note that the Maven repository system is shared across most JVM build tools. The same maven repository can be read from both the Maven and Gradle build tools, along with the Jupyter notebook Maven integration.

You can also look into our [demo repository](https://github.com/deepjavalibrary/djl-demo) for standalone DJL examples.

**Comment by kyxap** [comment]
it seems like im missing basic understanding on how that Jupyter works and why java library uses python... and those tutorial does not help or point me to the right direction to start my learning process. 

After `Jupyter` installation how do I need to add maven _repository_ `%mave` ?
Do I need to open python console and run that magic command? :) 

![image](https://github.com/deepjavalibrary/djl/assets/3080529/2286b1e2-89ac-4ac7-9179-f9a869a43383)
