### ISSUE TITLE
Add support for int4 to PyTorch Engine.

### ISSUE THREAD

**Issue by mymagicpower** [deepjavalibrary/djl#2736]
## Description
Add int4 support to pytorch engine.

Will this change the current api? How?
This will allow the user to run more performant inference using int4 models rather than fp16/int8.

Who will benefit from this enhancement?
Users who are running inference at scale and need to maximize their GPU compute available for LLM, e.g．:

## References
https://huggingface.co/THUDM/chatglm2-6b-int4

**Comment by frankfliu** [comment]
@mymagicpower 

int4 is not currently a real datatype: https://pytorch.org/docs/stable/tensor_attributes.html, It's more of quantization.

Do you have any proposal how to support int4 in PyTorch?

**Comment by mymagicpower** [comment]
https://github.com/pytorch/pytorch/issues/74627
