### ISSUE TITLE
How to query DJL for OpenCV version specific information?

### ISSUE THREAD

**Issue by joson1205** [deepjavalibrary/djl#2739]
How to query DJL for OpenCV version specific information? Can you do iterative updates?

**Comment by frankfliu** [comment]
@joson1205 

Each DJL version uses a specific OpenCV. You can use [BOM](https://docs.djl.ai/bom/index.html) to ensure the dependencies are consistent.

To find out with OpenCV DJL is using, see: https://github.com/deepjavalibrary/djl/blob/master/gradle.properties#L45

**Comment by joson1205** [comment]
> @joson1205
> 
> Each DJL version uses a specific OpenCV. You can use [BOM](https://docs.djl.ai/bom/index.html) to ensure the dependencies are consistent.
> 
> To find out with OpenCV DJL is using, see: https://github.com/deepjavalibrary/djl/blob/master/gradle.properties#L45

tks!!
