### ISSUE TITLE
PytorchStreamReader failed reading zip archive, but example documentation code does not produce zip file

### ISSUE THREAD

**Issue by yangkl96** [deepjavalibrary/djl#2756]
## Description
The documentation here (https://docs.djl.ai/docs/tensorflow/how_to_import_tensorflow_models_in_DJL.html) explains how to make a saved model in .pb format. I am then instructed to load the model (https://docs.djl.ai/docs/load_model.html), but it is looking for a zip archive rather than my .pb file.

### Expected Behavior
Identifying .pb file.

### Error Message
[main] INFO ai.djl.util.Platform - Found placeholder platform from: cpu-win-x86_64:2.0.1
[main] INFO ai.djl.pytorch.engine.PtEngine - PyTorch graph executor optimizer is enabled, this may impact your inference latency and throughput. See: https://docs.djl.ai/docs/development/inference_performance_optimization.html#graph-executor-optimization
[main] INFO ai.djl.pytorch.engine.PtEngine - Number of inter-op threads is 6
[main] INFO ai.djl.pytorch.engine.PtEngine - Number of intra-op threads is 6
Exception in thread "main" ai.djl.engine.EngineException: PytorchStreamReader failed reading zip archive: failed finding central directory
	at ai.djl.pytorch.jni.PyTorchLibrary.moduleLoad(Native Method)
	at ai.djl.pytorch.jni.JniUtils.loadModule(JniUtils.java:1719)
	at ai.djl.pytorch.engine.PtModel.load(PtModel.java:92)
	at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:161)
	at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:172)
	at Testing.main(Testing.java:25)

## How to Reproduce?
Ran the following in python:
`lrelu = lambda x: tf.keras.activations.relu(x, alpha=0.1, max_value=20.0)`
`loaded_model = keras.models.load_model("model.hdf5", custom_objects={'<lambda>': lrelu})
tf.saved_model.save(loaded_model, "my_model/")`

Then ran this in IntellijIDEA:
```
public class Testing {
    public static void main(String[] args) throws IOException, MalformedModelException, ModelNotFoundException {
        Path modelDir = Paths.get("C:/path/to/my_model/");

        Criteria<Image, Classifications> criteria = Criteria.builder()
                .setTypes(Image.class, Classifications.class)
                .optModelPath(modelDir)
                .optModelName("saved_model.pb").build();

        ZooModel<Image, Classifications> model = criteria.loadModel();
    }
}
```

I have the following Maven dependencies loaded:
`    <dependencies>
        
        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-engine</artifactId>
            <version>0.23.0</version>
        </dependency>
        
        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-native-cpu</artifactId>
            <version>2.0.1</version>
        </dependency>
        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.36</version>
        </dependency>
    </dependencies>`

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

## Environment Info

Please run the command `./gradlew debugEnv` from the root directory of DJL (if necessary, clone DJL first). It will output information about your system, environment, and installation that can help us debug your issue. Paste the output of the command below:

```
PASTE OUTPUT HERE
```

**Comment by yangkl96** [comment]
Figured out I had to download the tensorflow engine instead of pytorch

**Comment by frankfliu** [comment]
You need to use TensorFlow engine to load the model.

You have to update your pom.xml and remove pytorch and add tensorflow engine
