### ISSUE TITLE
No matching cuda flavor for win found: cu112mkl/sm_86.

### ISSUE THREAD

**Issue by eleven-dimension** [deepjavalibrary/djl#2775]
Hi, team. I am trying to run TrainMnist in [examples](https://github.com/deepjavalibrary/djl/blob/master/examples/README.md) on gpu in windows os but get this warning so DJL is running on CPU. Is this the result of a downloading problem? How can I fix it?

Thank you very much!

**Comment by eleven-dimension** [comment]
After going through the source code, I find only cuda 11.8 is supported :(

**Comment by frankfliu** [comment]
@eleven-dimension 
PyTorch cu118 is compatible with cu12.2. You should be able to run run PyTorch with cud112.

See: https://github.com/deepjavalibrary/djl/issues/2485

**Comment by frankfliu** [comment]
@eleven-dimension 
My bad. cu-112 is bit too old. Would you please upgrade to 11.8?

It should still work if you set `PYTORCH_FLAVOR`, but remember there are issues with 112

**Comment by eleven-dimension** [comment]
Fine! Solved after upgrading. Thanks for your help!

**Comment by eleven-dimension** [comment]
![image](https://github.com/deepjavalibrary/djl/assets/53202752/448cde43-e151-469e-bf03-8e01e017801b)

My build passes device test but cpu is still used in TrainMnist example. I set breakpoints and it seems that `win/cu118mkl/mxnet_86.dll.gz` doesn't exist and it can't be found at the url `https://publish.djl.ai/mxnet-1.9.1/win/cu118mkl/mxnet_86.dll.gz` as I expected. Where can it be downloaded?

**Comment by frankfliu** [comment]
Can set default engine to PyTorch to avoid using MXNet?

**Comment by eleven-dimension** [comment]
Okay, thanks for your time!
