### ISSUE TITLE
Why are non-English models skipped in conversion?

### ISSUE THREAD

**Issue by aghasemi** [deepjavalibrary/djl#2787]
Hello. [Here in the model conversion script](https://github.com/deepjavalibrary/djl/blob/15fd0d0e061b1902c26acd596f2165e7bb9a8b27/extensions/tokenizers/src/main/python/huggingface_models.py#L88), non-English models are   "skipped" practically making it impossible to use them in DJL. Is there a technical reason for that?

Many thanks

**Comment by frankfliu** [comment]
@aghasemi 

The script doesn't have a validation prompt for non-engine models, so we didn't enable it. You can update the script to import any model, but you need to verify the converted the model produce correct result.

**Comment by frankfliu** [comment]
@aghasemi 
now you can set environment variable: `export HF_IMPORT_ALL=true` to import non-english model. But you may need to verify the model works as expected for your language.

See: https://github.com/deepjavalibrary/djl/blob/master/extensions/tokenizers/src/main/python/huggingface_models.py#L86C58-L86C71
