### ISSUE TITLE
Getting to use a non-English model from HuggingFace

### ISSUE THREAD

**Issue by aghasemi** [deepjavalibrary/djl#2790]
## Description
Hello,
I'm trying to get a non-English sentiment analysis model working (https://huggingface.co/oliverguhr/german-sentiment-bert). I converted it to TorchScript using the script in the `extensions/tokenizers` folder, but when trying to use it, I get the following expectation:

```
Exception in thread "main" ai.djl.repository.zoo.ModelNotFoundException: No model with the specified URI or the matching Input/Output type is found.
        at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:184)
        at MLTest.main(MLTest.java:82)
Caused by: ai.djl.repository.zoo.ModelNotFoundException: No matching default translator found. The valid input and output classes are: 
        (ai.djl.ndarray.NDList, ai.djl.ndarray.NDList)

        at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:91)
        at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:172)
```

If the valid input and out types are both NDList, then how do I convert between `NDList` and `String`? And how do I determine the correct input and out put types? Both `model.describeInput()` and `model.describeOutput()` return `null`.

Here is the relevant part of the code:

```


        var criteria = Criteria.builder()
                .optApplication(Application.NLP.SENTIMENT_ANALYSIS)
                .setTypes(String.class, Object.class)
                .optModelPath(new File("../djl/extensions/tokenizers/model/nlp/text_classification/ai/djl/huggingface/pytorch/oliverguhr/german-sentiment-bert/0.0.1/german-sentiment-bert.zip").toPath())
                .optEngine("PyTorch")
                .optTranslatorFactory(new TextEmbeddingTranslatorFactory())
                .build();

        try (var model = criteria.loadModel();var predictor = model.newPredictor();var manager = NDManager.newBaseManager("PyTorch")) {
            System.err.println(model.describeInput());
            System.err.println(model.describeOutput());
            System.out.println(model.getDataType());

            System.out.println(predictor.predict("Hallo"));

        }
```

Thanks

**Comment by frankfliu** [comment]
@aghasemi 
A few problem in your code:
1. This is a TextClassification model, you use use `TextClassificationTranslatorFactory`
2. The criteria type should be <String, Classifications>

I'm able to get result with the following code:

```
        Path path =
                Paths.get("../extensions/tokenizers/src/main/python/model/nlp/text_classification/ai/djl/huggingface/pytorch/oliverguhr/german-sentiment-bert/0.0.1/german-sentiment-bert.zip");
        Criteria<String, Classifications> criteria = Criteria.builder()
                .setTypes(String.class, Classifications.class)
                .optModelPath(path)
                .optEngine("PyTorch")
                .optTranslatorFactory(new TextClassificationTranslatorFactory())
                .build();

        try (ZooModel<String, Classifications> model = criteria.loadModel();
             Predictor<String, Classifications> predictor = model.newPredictor()) {
            return predictor.predict("Mit keinem guten Ergebniss");
        }
```

```
[INFO ] - [
        {"class": "negative", "probability": 0.99757}
        {"class": "positive", "probability": 0.00234}
        {"class": "neutral", "probability": 0.00007}
]
```

To your original question, you must understand which type of application your model is. In this case, this is a "textclassification" (you can find it in huggingface tag), the input is string and output and a classification with probability.

You can find TextClassification code which convert input String to NDList: https://github.com/deepjavalibrary/djl/blob/master/extensions/tokenizers/src/main/java/ai/djl/huggingface/translator/TextClassificationTranslator.java#L65

**Comment by aghasemi** [comment]
Many thanks. That was exactly my problem: How to determine input and output Java classes. Is there a guide to know more.

And btw many thanks for the great work. Is the project affiliated with Amazon in some capacity?

**Comment by frankfliu** [comment]
DJL is an open source project under apache 2.0 license. This is one of Amazon open source initiatives to democratize deep learning. Multiple parties have contributed to this project.

**Comment by aghasemi** [comment]
Is this the relevant documentation to learn more about Translators and using them? https://docs.djl.ai/docs/demos/malicious-url-detector/docs/translators.html

**Comment by frankfliu** [comment]
Here is a jupyter notebook that explains the Translator: https://github.com/deepjavalibrary/djl/blob/master/jupyter/pytorch/load_your_own_pytorch_bert.ipynb
