### ISSUE TITLE
nested exception is ai.djl.engine.EngineException: PytorchStreamReader failed locating file constants.pkl: file not found

### ISSUE THREAD

**Issue by 201723201401012** [deepjavalibrary/djl#2802]
nested exception is ai.djl.engine.EngineException: PytorchStreamReader failed locating file constants.pkl: file not found
为啥加载yolov5的pt文件就会报错，加载yolov5转换好的onnx却能成功呢

**Comment by frankfliu** [comment]
Your model is not torch script model. You need trace it. See: https://docs.djl.ai/docs/pytorch/how_to_convert_your_model_to_torchscript.html

**Comment by frankfliu** [comment]
Feel free to reopen the issue if you still have questions.
