### ISSUE TITLE
关于aarch64 onnx无法加载的问题

### ISSUE THREAD

**Issue by 90600** [deepjavalibrary/djl#2807]
我描述一下我的问题，有两个基础docker镜像，一个是x86另一个是arm架构的，里面环境是一样的就是Java和tomcat，同一份代码，在x86里可以正常使用，arm里就是一直报加载错误，onnx引擎都下下来了，这个问题我改如何解决呢

可以看下图片所需要的引擎都下载下来了
<img width="1309" alt="image" src="https://github.com/deepjavalibrary/djl/assets/147969415/4c8f075c-84ff-4698-9e33-3de22660e812">

主要错误：
1.Caused by: java.lang.UnsatisfiedLinkError: Unable to load library '/root/.djl.ai/mxnet/1.9.1-mkl-linux-aarch64/libmxnet.so':
2.Caused by: ai.djl.engine.EngineException: Failed to load MXNet native library

想请问下，我aarch64架构是缺少啥东西么？

**Comment by frankfliu** [comment]
@90600 

MXNet doesn't support aarch64. Only PyTorch and OnnxRuntime works for aarch64. Please make sure only include onnx and pytorch engine in your project.

**Comment by 90600** [comment]
首先谢谢你可以回答我的问题。
1.我把模型换成pytorch引擎后，在aarch64环境里可以正常运行了，但是推理特别慢，需要3～6秒，推理一张图片。
2.在x86架构中，pytorch引擎会报错，x86架构中不能运行pytorch引擎么
  报错信息：
<img width="1427" alt="image" src="https://github.com/deepjavalibrary/djl/assets/147969415/cbb7ccdd-468c-43a4-b970-d2fda3fc30c8">

 并没有下载pytorch引擎
<img width="686" alt="image" src="https://github.com/deepjavalibrary/djl/assets/147969415/34b6d79c-6e4e-434c-8037-84d7b7f5cf66">

3.我是一名java工作者，对深度学习不是很了解，onnx推理要比pyroch快么？OnnxRuntime也是用onnx推理的吧

**Comment by 90600** [comment]
我使用OnnxRuntime进行推理，报错java.lang.UnsupportedOperationException: This NDArray implementation does not currently support this operation
Creating a new SqlSession

我的maven依赖
<dependency>
            <groupId>ai.djl</groupId>
            <artifactId>api</artifactId>
        </dependency>









        









        <dependency>
            <groupId>ai.djl.onnxruntime</groupId>
            <artifactId>onnxruntime-engine</artifactId>
            <scope>runtime</scope>
        </dependency>
我还需要引入别的相关依赖么

**Comment by frankfliu** [comment]
@90600 
We didn't observe performance issue on aarch64 machine. It actually running a bit faster on AWS graviton3 instance. It might be related to your linux environment missing some math library. You can enable `Metrics` to see where the time spend on.

For OnnxRuntime, it doesn't support NDArray operations, you need use it with PyTorch together. See: https://docs.djl.ai/docs/hybrid_engine.html
