### ISSUE TITLE
Yolov8Detection has issues

### ISSUE THREAD

**Issue by liautumn** [deepjavalibrary/djl#2827]
Has been reasoning non-stop, and then the computer black screen, memory continued to grow, yolov8 demo

[
![image](https://github.com/deepjavalibrary/djl/assets/93562667/19779b62-4dfb-4add-bdee-864181390095)
](url)

**Comment by 90600** [comment]
yolov5也会，如果内存不回收没办法用在上生产环境上，好多人提出内存不回收，不知道为啥他们一直肯定他们没有问题

**Comment by kkangert** [comment]
我也存在这个问题。

**Comment by frankfliu** [comment]
Feel free to re-open this issue if still can reproduce in latest version.
