### ISSUE TITLE
推理慢

### ISSUE THREAD

**Issue by 201723201401012** [deepjavalibrary/djl#2828]
使用pytorch引擎，在x86环境上推理一张图片，一百多毫秒，在aarch64 却要十秒多，是缺少什么组件么

**Comment by frankfliu** [comment]
@201723201401012 
Can you try python on your aarch64 and and if python is working fine?

Here is how we build: https://github.com/deepjavalibrary/djl/blob/master/.github/workflows/native_jni_s3_pytorch.yml#L264-L273

We have a lot of customer running DJL on AWS c6g and c7g instance. Our benchmark show c7g actually a bit faster the x86

**Comment by 201723201401012** [comment]
@frankfliu 
python可以正常运行，我的基础镜像用的是ubuntu20，里面就下了jdk和tomcat，我们有两份环境x86和aarch64 ，aarch64推理就很慢，不知道如何排查，https://github.com/deepjavalibrary/djl/blob/master/.github/workflows/native_jni_s3_pytorch.yml#L264-L273 这个里面用了amazonlinux:2这个镜像，难道我要切换到这个基础镜像？

**Comment by 201723201401012** [comment]
@frankfliu Can you help me? This is very important to me
