### ISSUE TITLE
How to get byte[] of ai.djl.modality.cv.Image?

### ISSUE THREAD

**Issue by SidneyLann** [deepjavalibrary/djl#2839]
I want to save the image to hbase, How to get byte[] of ai.djl.modality.cv.Image?

**Comment by frankfliu** [comment]
@SidneyLann 

There is `Image.save(OutputStream, String)` function, you can save the image to `ByteArrayOutputStream` and get the byte[] from the outputstream

**Comment by SidneyLann** [comment]
Thanks.
