### ISSUE TITLE
PaddleOCR - The JVM memory is not released

### ISSUE THREAD

**Issue by hfwanggh** [deepjavalibrary/djl#2848]
## Description
When dealing with multithreaded tasks, the following three Predictor objects should not be created as singletons. If I use singletons when testing multithreaded tasks, my application will crash directly. Instead of using multiple cases, which means reloading a new Predictor each time you use it, the Predictor works fine. However, JVM memory can grow significantly as more concurrent requests occur, and the memory footprint is not released until the task completes the response. After that, I obtained the heapdump file for several times and analyzed it with MAT (I will give some screenshots below). Up to now, I have not determined the reason for the non-release of memory. I look forward to receiving your reply, so that I can solve this problem faster, thank you very much.
```
Here are the three Predictor objects I loaded:

Criteria<Image, DetectedObjects> detectedCriteria = Criteria.builder()
                    .optEngine("PaddlePaddle")
                    .setTypes(Image.class, DetectedObjects.class)
                    .optModelPath(Paths.get(getPath() +"ch_PP-OCRv4_det_infer.tar"))
                    .optTranslator(new PpWordDetectionTranslator(new ConcurrentHashMap<String,String>()))
                    .build();
ZooModel<Image, DetectedObjects> detectionModel = detectedCriteria.loadModel();
Predictor<Image, DetectedObjects> detectorPredictor = detectionModel.newPredictor();					
					
Criteria<Image, Classifications> classifyModel = Criteria.builder()
                    .optEngine("PaddlePaddle")
                    .setTypes(Image.class, Classifications.class)
                    .optModelPath(Paths.get(getPath() +"ch_ppocr_mobile_v2.0_cls_infer.tar"))
                    .optTranslator(new PpWordRotateTranslator())
                    .build();
ZooModel<Image, Classifications> rotateModel = classifyModel.loadModel();
Predictor<Image, Classifications> classifyPredictor = rotateModel.newPredictor();

Criteria<Image, String> recognizerCriteria = Criteria.builder()
                    .optEngine("PaddlePaddle")
                    .setTypes(Image.class, String.class)
                    .optModelPath(Paths.get(getPath() +"ch_PP-OCRv4_rec_infer.tar"))
                    .optTranslator(new PpWordRecognitionTranslator())
                    .build();
ZooModel<Image, String> recognitionModel = recognizerCriteria.loadModel();
Predictor<Image, String> recognizerPredictor = recognitionModel.newPredictor();
```
```
This is the Service code:

public List<RecognizeWords> recognizeImage(MultipartFile imageFile,Integer rotateTimes,PaddleOCRConfig config){
	    List<RecognizeWords> textList = new ArrayList<>();
            Predictor<Image, DetectedObjects> det = config.getDec();
            Predictor<Image, Classifications> cls = config.getCls();
            Predictor<Image, String> rec = config.getRec();

            try (InputStream is = imageFile.getInputStream()){
               Image img = ImageFactory.getInstance().fromInputStream(is);
               Image resize = img.resize(img.getWidth()*2, img.getHeight()+img.getHeight()/3, true);
               if (rotateTimes!=null) resize = rotateImg(resize,rotateTimes);

               DetectedObjects detectedObj = det.predict(resize);
               List<DetectedObjects.DetectedObject> boxes = detectedObj.items();

              for (int i = 0; i < boxes.size(); i++) {
                 BoundingBox boundingBox = boxes.get(i).getBoundingBox();
                 Image subImg = subImage(resize,boundingBox);

                 Classifications.Classification result = cls.predict(subImg).best();
                 if ("Rotate".equals(result.getClassName()) && result.getProbability() > 0.8 && rotateTimes!=null)
                     subImg = rotateImg(subImg,rotateTimes);

                 String text = rec.predict(subImg);
                 RecognizeWords recognizeWords = new RecognizeWords();
                 recognizeWords.setWords(text);
                 textList.add(recognizeWords);
              }
        } catch (IOException e) {
            throw new RuntimeException(e);
        } catch (TranslateException e) {
            throw new RuntimeException(e);
        }finally {
            det.close();
            cls.close();
            rec.close();
        }

	   return textList;
}
```
```
This is the Controller code: 

@PostMapping(value = "/recognize", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
@ResponseBody
public List<RecognizeWords> recognizeImage(@RequestParam("file") MultipartFile file){
    List<RecognizeWords> wordsResult = new ArrayList<>();
    PaddleOCRConfig config = new PaddleOCRConfig();
    if (file!=null && judge(config))
        wordsResult = paddleService.recognizeImage(file,null,config);
    return wordsResult;
}
```
### Here are some images of MAT analyzing the heapdump file

![1-1](https://github.com/deepjavalibrary/djl/assets/128673578/23d7edd3-26ab-4114-990c-91829a42d31d)
![1-2](https://github.com/deepjavalibrary/djl/assets/128673578/2044b85e-5c7b-407c-bbb8-dab295767ef8)
![2-1](https://github.com/deepjavalibrary/djl/assets/128673578/458aab89-b9bb-43c0-a63f-fcf0ccb351e1)
![2-2](https://github.com/deepjavalibrary/djl/assets/128673578/a2c4b931-535a-4356-b41b-75420a817ee0)
![2-3](https://github.com/deepjavalibrary/djl/assets/128673578/e1002657-5791-4280-9e57-3edecd37a2ba)
![3-1](https://github.com/deepjavalibrary/djl/assets/128673578/4216eac5-a858-42ee-b70f-b98b42167127)
![3-3](https://github.com/deepjavalibrary/djl/assets/128673578/7abdd775-f59d-4003-b5f1-5b48739df4b6)

**Comment by zachgk** [comment]
I am not clear with what you are doing with your predictor management. Our general recommendation is that each Predictor should not be considered thread-safe. If you want to do multi-threading, consider having a pool of predictors created off the same base model. Internally, we will do as much or as little work as necessary. For more information, see our [Memory Management Guide](http://docs.djl.ai/docs/development/memory_management.html#inference-use-case).

If you are creating a new predictor as part of `new PaddleOCRConfig()`, that could be expensive. Beyond that, are you also loading the models as part of `new PaddleOCRConfig()` as well? If so, you need to close the model too
