### ISSUE TITLE
Updating Quarkus extension for DJL

### ISSUE THREAD

**Issue by PetoMichalak** [deepjavalibrary/djl#2856]
Hello,
    We have been attempting to update DJL's support for Quarkus in 'djl-demo' to the latest versions of DJL (0.24.0) and Quarkus (3.5.1).
The updating of the Demo to DJL 0.24.0, was successful and straightforward, but we are having problems updating Quarkus to 3.5.1. This appears to be due to the changes in how the DJL's Quarkus Extension now needs to accomplish Dependency and Context injection. We are wondering if any one had looked at this, and had come to a conclusion on the best approach.

Will this change the current api? How?
No.

Who will benefit from this enhancement?
Quarkus community.

**Comment by zachgk** [comment]
Can you share more details about the problem you were facing? Was there any error message or in-progress code that we can take a look at?
