### ISSUE TITLE
LlamaTokenizer support

### ISSUE THREAD

**Issue by iamlockelightning** [deepjavalibrary/djl#2862]
## Description

LlamaTokenizer support
<img width="855" alt="image" src="https://github.com/deepjavalibrary/djl/assets/12706469/f42ac086-76cb-42ad-b5b1-33ae5d3d479c">

Will this change the current api? How?
No.

Who will benefit from this enhancement?
All LLM lovers.

## References
- https://huggingface.co/docs/transformers/model_doc/llama2#transformers.LlamaTokenizer

**Comment by frankfliu** [comment]
You can manually save `tokenizer.json` file in a folder, and use `HuggingfaceTokenizer` to load the tokenizer from file

**Comment by frankfliu** [comment]
@iamlockelightning 
Here is my code to save `tokenizer.json` file:

```
from transformers import AutoTokenizer

def main():
tokenizer = AutoTokenizer.from_pretrained("mistralai/Mistral-7B-v0.1")
tokenizer.save_pretrained("converted")
```

**Comment by frankfliu** [comment]
@iamlockelightning 

You can also use `LlamaTokenizerFast` instead of `LlamaTokenizer`

**Comment by iamlockelightning** [comment]
@frankfliu Thank you for your detailed answer. It works! 🎉
