### ISSUE TITLE
Should not download same files everytime

### ISSUE THREAD

**Issue by SidneyLann** [deepjavalibrary/djl#2887]
![image](https://github.com/deepjavalibrary/djl/assets/5990314/3ee7e274-16da-44b9-a62d-45a8ea82a921)

Should not download same files everytime when call criteria.loadModel();

**Comment by frankfliu** [comment]
Can you set DJL cache folder to somewhere else? See: https://docs.djl.ai/docs/development/cache_management.html

In some weird windows machine, Java failed to move tmp files. You should see some Permission error when this happen. The work around is to use a different cache folder.

**Comment by SidneyLann** [comment]
Ok now, it just use different folder for tmp file. It use the same folder after downloaded.
