### ISSUE TITLE
YoloV8Translator performance is not suitable for real-time applications 

### ISSUE THREAD

**Issue by gevant** [deepjavalibrary/djl#2899]
https://github.com/deepjavalibrary/djl/blob/1eb54c0378bfeb6230a02cf21ea17308f93e76cb/api/src/main/java/ai/djl/modality/cv/translator/YoloV8Translator.java#L64
**_Issue_**: suboptimal performance of Yelov8 translator

**_Description:_** Method getFloat() at the line 64 above is being executed 8400x80 times. On a consumer grade GPU RTX 2060 with CUDA 11 current Implementation takes up to 4 sec per image for inference (object detection).
**_Enhancement proposal_** : 
In comparison to it the plain [][] array solution is up to 50 fold faster on cpu vs NGArray managed  (getFloat()) on GPU with pytorch.
Optimization using getFloatArray() can bring Yelow8 implementation closer to be useful in real-time use cases.

**Comment by gevant** [comment]
you can assign this issue to me I will fix it

**Comment by frankfliu** [comment]
@gevant 

Thanks you for your offering. We should use the same approach as  `YoloV5Translator`, retrieve the float[] from the NDArray, and do all operations in java heap.

**Comment by gevant** [comment]
@frankfliu This can be closed. Changes are merged?

**Comment by frankfliu** [comment]
This is merged and available in 0.26.0 release
