### ISSUE TITLE
Unable to load a pretrained model locally pytorch

### ISSUE THREAD

**Issue by Samarth26** [deepjavalibrary/djl#2932]
I have a pytorch model which I have converted to torchscript and wish to use for inference in Java. It takes Float array as an input and the output is just a float. However, The Criteria Module is always unable to locate the Model. Currently my Criteria builder looks like this: 

Criteria<Float[], Float> criteria = Criteria.builder()
                .setTypes(Float[].class, Float.class)
                .optModelPath(get("build/pytorch_models/pretrainedModel"))
                .optProgress(new ProgressBar()).build(); 

Please let me know if something like this is supported by DJL as this is not a normal ZooModel.

**Comment by frankfliu** [comment]
You need to create a `Translator` to convert the input `Float[]` to `NDList` and convert `NDList` output back to `Float`

**Comment by frankfliu** [comment]
@Samarth26 

Here is an example:

```
        Translator<float[], Float> translator = new Translator<float[], Float>() {

            @Override
            public NDList processInput(TranslatorContext ctx, float[] input) {
                return new NDList(ctx.getNDManager().create(input));
            }
            @Override
            public Float processOutput(TranslatorContext ctx, NDList list) {
                return list.head().getFloat(0);
            }
        };

        Criteria<float[], Float> criteria =
                Criteria.builder()
                        .setTypes(float[].class, Float.class)
                        .optTranslator(translator)
                        .build();
```

**Comment by Samarth26** [comment]
Thank you so much for your response. That worked great for me. I have one question about the file structure. Currently, the criteria.loadModel() only picks up my pre-trained model if I have named it resnet18.pt. Is there any workaround so that I can use my model with a different name? 

As shown in the image below I had to create a copy of my traced_fyp_model and rename it to resnet18.pt for it to be picked up by criteria.loadModel()

<img width="1348" alt="image" src="https://github.com/deepjavalibrary/djl/assets/30769771/a1958132-5aa6-4df7-bb1c-6a9ffd751b6f">

**Comment by frankfliu** [comment]
There are multiple ways to achieve that:
1. use `.optModelName("traced_fyp_model")` to specify the model file name
2. ponit to your .pt file directly: `.optModelPath(Paths.get("traced_fyp_model.pt"))`
3. Add a `serving.properties` file in the model folder, and add `option.modelName=traced_fyp_model`

**Comment by Samarth26** [comment]
Thanks, resolved!
