### ISSUE TITLE
能否增强YoloV8Translator，支持YoloV8-seg模型，YoloV8-pose模型

### ISSUE THREAD

**Issue by yongyupei** [deepjavalibrary/djl#2936]
## Description

目前以YoloV8为基座开发了一系列的模型，用来支持分割、POSE检测等场景，djl的YoloV8Translator能否进行相关增强，以适配不同的下游任务

**Comment by frankfliu** [comment]
We added `yolov8n-seg` and `yolov8n-pose` model into our model zoo.
