### ISSUE TITLE
Implementation of Change Detection Function

### ISSUE THREAD

**Issue by StreakerHan** [deepjavalibrary/djl#2942]
The change detection model we are currently using is to input two images for detection, but how can we input two images simultaneously using DJL?

**Comment by zachgk** [comment]
There are different ways it can be done. You can use an NDArray with shape like `Shape(batch,2,3,height,width)`. You can also have an NDList containing the two images. You will have to take a look at the model and see what kind of input it expects. One way to do that is to load the model and call `model.getBlock().getInputShapes()`
