### ISSUE TITLE
Make commons-compress an optional dependency

### ISSUE THREAD

**Issue by StefanOltmann** [deepjavalibrary/djl#2949]
I'm experiencing difficulties with ProGuard and commons-compress. This has led me to consider the possibility of excluding the commons-compress dependency, allowing the application to function smoothly unless a zipped model that requires unzipping is explicitly specified. This approach would enable me to circumvent ProGuard issues associated with commons-compress while reducing unnecessary dependencies.

**Comment by frankfliu** [comment]
Can you exclude `commons-compress` from your project if you are not using any `.tar` file?

This should be pretty easy from gradle:

```
    implementation platform("ai.djl:bom:0.26.0")
    implementation("ai.djl:api") {
          exclude group: "org.apache.commons", module: "commons-compress"
    }
```

**Comment by StefanOltmann** [comment]
@frankfliu Do you have an estimate when the next release including this fix will be available?

I see you seem to have monthly releases.

**Comment by frankfliu** [comment]
We just released 0.26.0, 0.27.0 will be in March, see: https://docs.djl.ai/index.html#release-notes

For the meantime, you can use our nightly snapshot release: https://docs.djl.ai/docs/get.html#nightly-snapshots

**Comment by StefanOltmann** [comment]
@frankfliu I've tested the latest snapshot version and found that it functions smoothly with ProGuard. There seems to be something off with commons-compress that hinders optimization. I'm glad I don't need that library as long as I'm not using TAR files. Thank you for quickly fixing this!

Considering March is a considerable time away, I was wondering if you could consider releasing a `v0.26.1` fix version. I'm a bit hesitant to deploy a snapshot version in a production environment, as it might introduce breaking changes at any moment.

**Comment by StefanOltmann** [comment]
@zachgk Thank you for showing me a workaround. I guess I need to try that then.

I still must say I’m a bit surprised that you have so long and fixes release schedules and that it’s such an effort to do a release. Sounds to me like something is off.

Maybe you should consider reworking your CI pipeline for more automation. I maintain two libraries with Maven Central artifacts and releasing a new one is just a matter creating a GitHub release (which builds everything using GitHub actions and uploads to Maven Central) and confirming in the Sonatype Nexus that the artifacts should be released to Maven Central.

**Comment by frankfliu** [comment]
@StefanOltmann 
Releasing DJL is non-trivial work. We have 11 engines and need to test on to following platforms:
- macOS
- macOS M1
- ubuntu
    - x86_64
    - aarch64
    - cuda 112, cuda 113, cuda 118
    - cuda 12.1
- amazlinux:2 x86_64 and aarch64
- centos 7
- Widnows server 2019+

For each release, we publish over 70+ artifacts. And a we more than 6 downstream github repo (djl-serving, djl-demo, springboot-start, docs, jupyter notebooks etc) to be updated to new version.

**Comment by StefanOltmann** [comment]
The artifact count shouldn’t matter with the automation, but I see your point with the downstream repos.
