### ISSUE TITLE
support paddlepaddle for macOS aarch64

### ISSUE THREAD

**Issue by crosslover** [deepjavalibrary/djl#2959]
## Description

It seems that the official already support the mac arm arch. Hope it will be supported.

## References

- list reference and related literature
- list known implementations
![image](https://github.com/deepjavalibrary/djl/assets/11575251/818a5069-d981-4b05-8994-70bb124eb287)

**Comment by frankfliu** [comment]
We dropped PaddlePaddle support start from 0.28.0 since it has low adoption.
