### ISSUE TITLE
Could not find artifact ai.djl.pytorch:pytorch-native-cu118:jar:linux-x86_64:2.1.1

### ISSUE THREAD

**Issue by jestiny0** [deepjavalibrary/djl#2961]
## Description
I see the configuration as follows at this [link](https://docs.djl.ai/engines/pytorch/pytorch-engine/index.html#linux-gpu)
```
<dependency>
    <groupId>ai.djl.pytorch</groupId>
    <artifactId>pytorch-native-cu118</artifactId>
    <classifier>linux-x86_64</classifier>
    <version>2.1.1</version>
    <scope>runtime</scope>
</dependency>
<dependency>
    <groupId>ai.djl.pytorch</groupId>
    <artifactId>pytorch-jni</artifactId>
    <version>2.1.1-0.26.0</version>
    <scope>runtime</scope>
</dependency>
```

I couldn't find version 2.1.1 at the following maven repo link, 
https://mvnrepository.com/artifact/ai.djl.pytorch/pytorch-native-cu118
but I found it at another link
https://mvnrepository.com/artifact/ai.djl.pytorch/pytorch-native-cu121

### Expected Behavior
support pytorch 2.1.1 with cu118 instead of cu121

**Comment by frankfliu** [comment]
Can you use `pytorch-native-cu118:2.0.1` ?

```
<dependency>
    <groupId>ai.djl.pytorch</groupId>
    <artifactId>pytorch-native-cu118</artifactId>
    <classifier>linux-x86_64</classifier>
    <version>2.0.1</version>
    <scope>runtime</scope>
</dependency>
<dependency>
    <groupId>ai.djl.pytorch</groupId>
    <artifactId>pytorch-jni</artifactId>
    <version>2.0.1-0.26.0</version>
    <scope>runtime</scope>
</dependency>
```

**Comment by frankfliu** [comment]
I created a PR to fix document: https://github.com/deepjavalibrary/djl/pull/2963
