### ISSUE TITLE
How to support paddlepaddle on an aarch64 FT Phytium S2500/64 machine? 

### ISSUE THREAD

**Issue by Maglanyulan** [deepjavalibrary/djl#2998]
## Description
Before in accordance with this step on the Kunpeng Kirin v10 chip to adapt, reasoning no problem, https://github.com/deepjavalibrary/djl/issues/2221#issuecomment-1599111210

Now I want to complete the adaptation on the FT Phytium S2500/64  chip, and found that there is a segment error in the reasoning
![bfa1de0a81b084ce1481e4949](https://github.com/deepjavalibrary/djl/assets/40079055/e0e1715e-b1d6-476c-9233-065aa3551ad2)
### Steps to reproduce
(Paste the commands you ran that produced the error.)

1, compiled paddle on this machine, generated paddle_inference.so

2, run gradlew :engines:paddledle:paddlepaddle-native:compileJNI to build JNI, generate libpaddle.so

3. Load paddle_inference.so into the LD directory.

But start the java program preprocessing no problem, to paddle forward on the report paragraph error

## What have you tried to solve it?

Loaded the so package via c++, verified that the so package is fine
![c++](https://github.com/deepjavalibrary/djl/assets/40079055/cb1c6f88-0157-4420-ae68-1c9bc359c757)

**Comment by frankfliu** [comment]
paddle support in DJL is deprecated.
