### ISSUE TITLE
Run tensorflow model on arm architecture

### ISSUE THREAD

**Issue by posuhov** [deepjavalibrary/djl#3000]
Hi team, 

I'm using DJL version 0.23.0 and I want to run a tensorflow model on Raspberry PI. I've build a tensorflow version 2.10.1 from the sources. As result I have following files:
- libtensorflow_jni.so
- libtensorflow.so
-  libtensorflow_framework.so

But DJL library wants to load jnitensorflow,so
I've tried to run my app on ubuntu x64 and libjnitensorflow.so has been downloaded automatically(I believe from https://repo1.maven.org/maven2/ai/djl/tensorflow/tensorflow-native-cpu/2.10.1/). But the size looks very different(780kb) from what I got after tensorflow build(39Mb). Could you please tell me what is libjnitensorflow.so  and how it can be built if it's part of DJL?

**Comment by frankfliu** [comment]
@posuhov 

DJL use [tensorflow/java](https://github.com/tensorflow/java) directly. You can follow the instruction to build the project.

Here is the gradle tasks that repackage tensorflow into DJL package: https://github.com/deepjavalibrary/djl/blob/master/engines/tensorflow/tensorflow-native/build.gradle#L23

**Comment by posuhov** [comment]
ok, thanks
