### ISSUE TITLE
NDArrays.concat has a different behaviour as np.concatenate

### ISSUE THREAD

**Issue by vm3538** [deepjavalibrary/djl#3003]
## Description
It looks like concatenating lists doesn't work as in Python.

### Expected Behavior
I was expecting to get an array with the same shape as in Python.

### Error Message
No errors, but here are the outputs:
Python:
```
(2, 10, 5)
(20, 5)
```

Java:
```
[(2, 10, 5)]
(2, 10, 5)
```

## How to Reproduce?
Python code:
``` python
import numpy as np

arr = np.arange(100).reshape((2, 10, 5))

print(arr.shape)
print(np.concatenate(arr).shape)
```

Java code:
``` java
NDManager manager = NDManager.newBaseManager();
NDList arr = new NDList(manager.arange(100).reshape(new Shape(2, 10, 5)));
System.out.println(Arrays.toString(arr.getShapes()));
System.out.println(NDArrays.concat(arr).getShape());
```

### Steps to reproduce

1. Run the Python code
2. Run the Java code

## What have you tried to solve it?
I did not find another method in Java do get the same result as in Python.

## Environment Info
djl 0.26.0
pytorch 1.13.1

**Comment by vm3538** [comment]
Thanks for your reply!
I'm not very familiar with NDArrays/Lists, would this be the best way to replicate numpy's concatenate with only one list input?

``` java
NDArray concatenate(NDList list) {
    NDArray arr = list.singletonOrThrow();
    long sections = arr.getShape().head();
    NDArray concat = NDArrays.concat(arr.split(sections), 1);
    return concat.reshape(concat.getShape().slice(1));
}
```

**Comment by frankfliu** [comment]
You can write your own wrapper function if you want to get numpy like behavior:

```
    NDArray npCat(NDList list) {
        if (list.size() > 1) {
            return NDArrays.concat(list);
        }
        NDArray arr = list.singletonOrThrow();
        long sections = arr.getShape().head();
        NDArray concat = NDArrays.concat(arr.split(sections), 1);
        return concat.squeeze(0);
    }
```
