### ISSUE TITLE
OnnxRuntime 引擎官网案例报错

### ISSUE THREAD

**Issue by javadoge** [deepjavalibrary/djl#3036]
本地环境：windows，cuda117，djl0.26.0

使用官网案例，运行报错

参考官网案例：https://docs.djl.ai/docs/demos/jupyter/onnxruntime/machine_learning_with_ONNXRuntime.html

报错信息：

Exception in thread "main" java.lang.UnsatisfiedLinkError: ai.onnxruntime.OrtEnvironment$ThreadingOptions.createThreadingOptions(J)J
	at ai.onnxruntime.OrtEnvironment$ThreadingOptions.createThreadingOptions(Native Method)
	at ai.onnxruntime.OrtEnvironment$ThreadingOptions.<init>(OrtEnvironment.java:392)
	at ai.djl.onnxruntime.engine.OrtEngine.<init>(OrtEngine.java:44)
	at ai.djl.onnxruntime.engine.OrtEngine.newInstance(OrtEngine.java:64)
	at ai.djl.onnxruntime.engine.OrtEngineProvider.getEngine(OrtEngineProvider.java:43)
	at ai.djl.engine.Engine.getEngine(Engine.java:216)
	at ai.djl.Model.newInstance(Model.java:99)
	at ai.djl.repository.zoo.BaseModelLoader.createModel(BaseModelLoader.java:196)
	at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:159)
	at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:172)

代码如下：

public class OnnxTest {
	public static void main(String[] args) {
		try {
			String modelUrl = "https://mlrepo.djl.ai/model/tabular/softmax_regression/ai/djl/onnxruntime/iris_flowers/0.0.1/iris_flowers.zip";
			Criteria<IrisFlower, Classifications> criteria = Criteria.builder()
			        .setTypes(IrisFlower.class, Classifications.class)
			        .optModelUrls(modelUrl)
			        .optTranslator(new MyTranslator())
			        .optEngine("OnnxRuntime") // use OnnxRuntime engine by default
			        .build();
			ZooModel<IrisFlower, Classifications> model = criteria.loadModel();
			Predictor<IrisFlower, Classifications> predictor = model.newPredictor();
			IrisFlower info = new IrisFlower(1.0f, 2.0f, 3.0f, 4.0f);
			predictor.predict(info);
		} catch (Exception e) {
			e.printStackTrace();
		}
		
	}
}

**Comment by javadoge** [comment]
![1710839425103](https://github.com/deepjavalibrary/djl/assets/5305836/33b8c983-6800-484d-a42d-4449970415a2)
maven配置：

<dependency>
            <groupId>ai.djl.onnxruntime</groupId>
            <artifactId>onnxruntime-engine</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.microsoft.onnxruntime</groupId>
                    <artifactId>onnxruntime</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.microsoft.onnxruntime</groupId>
            <artifactId>onnxruntime</artifactId>
            <version>${onnx.version}</version>
            <scope>runtime</scope>
        </dependency>

**Comment by javadoge** [comment]
![1710840308824](https://github.com/deepjavalibrary/djl/assets/5305836/873f6f7d-ad7b-4f27-9ef7-3b2d8a453f3b)
这是windows system32  onnxruntime.dll 依赖关系，跟这个有关系么

**Comment by frankfliu** [comment]
`UnsatisfiedLinkError` most likely you don't have DLL that onnxruntime is depends on. Can you try to install  install [Visual C++ 2019 Redistributable Packages](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) and reboot

**Comment by javadoge** [comment]
![1710894535075](https://github.com/deepjavalibrary/djl/assets/5305836/a5705685-184c-4a1b-afaa-d033f3f08fc2)
我把之前的Visual C++都删了，安装了下2019这个版本，电脑也重启了，还是不行

**Comment by javadoge** [comment]
![1710896938179](https://github.com/deepjavalibrary/djl/assets/5305836/14c8ce80-cf4b-4bde-8e92-234f3ea62f73)
即便 重新下载一个  onnxruntime ，加载指定的onnxruntime.dll文件，也不行呢，看DLL依赖也没报错。原因大概率是windows环境问题，但是好难排查

**Comment by frankfliu** [comment]
You can try to install VS, and use `dumpbin.exe` to check dependencies

**Comment by javadoge** [comment]
> dumpbin

Dump of file C:\Windows\System32\onnxruntime.dll

File Type: DLL

  Image has the following dependencies:

    api-ms-win-core-file-l1-1-0.dll
    api-ms-win-core-errorhandling-l1-1-0.dll
    api-ms-win-core-string-l1-1-0.dll
    api-ms-win-core-processenvironment-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-locale-l1-1-0.dll
    api-ms-win-crt-private-l1-1-0.dll
    api-ms-win-core-synch-l1-2-0.dll
    api-ms-win-core-synch-l1-1-0.dll
    api-ms-win-core-processthreads-l1-1-0.dll
    api-ms-win-core-localization-l1-2-0.dll
    api-ms-win-core-profile-l1-1-0.dll
    api-ms-win-core-sysinfo-l1-2-0.dll
    api-ms-win-core-util-l1-1-0.dll
    api-ms-win-core-heap-l2-1-0.dll
    api-ms-win-core-handle-l1-1-0.dll
    api-ms-win-core-libraryloader-l1-2-0.dll
    api-ms-win-core-rtlsupport-l1-1-0.dll
    api-ms-win-core-processthreads-l1-1-1.dll
    api-ms-win-core-sysinfo-l1-1-0.dll
    api-ms-win-core-interlocked-l1-1-0.dll
    api-ms-win-core-debug-l1-1-0.dll
    api-ms-win-core-fibers-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-core-path-l1-1-0.dll
    api-ms-win-core-heap-l1-1-0.dll
    api-ms-win-core-memory-l1-1-0.dll
    api-ms-win-core-processtopology-obsolete-l1-1-0.dll
    api-ms-win-core-processthreads-l1-1-3.dll
    api-ms-win-core-file-l1-2-0.dll
    api-ms-win-eventing-provider-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-core-libraryloader-l1-2-1.dll

  Image has the following delay load dependencies:

    d3d12.dll
    dxgi.dll
    DirectML.dll
    OLEAUT32.dll
    api-ms-win-core-com-l1-1-0.dll

  Summary

       15000 .data
        1000 .didat
       2B000 .pdata
      10F000 .rdata
        9000 .reloc
        1000 .rsrc
      5F5000 .text
        1000 _RDATA

**Comment by frankfliu** [comment]
There are two dll in the jar file. `ai/onnxruntime/native/win-x64/onnxruntime4j_jni.dll` and `ai/onnxruntime/native/win-x64/onnxruntime.dll`, can you check both dependencies?

And also why you copy onnxruntime.dll to system32 directory? It supposed to be extracted to temp folder at runtime.

```
dumpbin /dependents onnxruntime4j_jni.dll
```

**Comment by frankfliu** [comment]
feel free to re-open this issue if still have questions.
