### ISSUE TITLE
Java Doc Api web pages can not open.

### ISSUE THREAD

**Issue by devtommy2** [deepjavalibrary/djl#3076]
## Description
The api doc provided by GitHub Readme cannot be opened.
website: https://javadoc.djl.ai/ has already deprecated, the Java Api Doc site in the Readme.md should be updated: https://javadoc.io/doc/ai.djl/api/latest/index.html

### Error Message
<img width="1017" alt="image" src="https://github.com/deepjavalibrary/djl/assets/74338779/aca414e4-501c-4021-b3af-4b134cd5cea8">

**Comment by frankfliu** [comment]
The current page is here: https://djl.ai/website/javadoc.html

Can you let me know where this link is used? I can update the reference page.

**Comment by devtommy2** [comment]
> The current page is here: https://djl.ai/website/javadoc.html
> 
> Can you let me know where this link is used? I can update the reference page.

<img width="1512" alt="image" src="https://github.com/deepjavalibrary/djl/assets/74338779/096d54ea-2553-43c2-8f24-33704bdd0de7">

**Comment by frankfliu** [comment]
Thanks for reporting this issue, I created a PR to fix broken link: https://github.com/deepjavalibrary/djl/pull/3077

**Comment by frankfliu** [comment]
Fixed.
