### ISSUE TITLE
Does Lightgbm support multi-class inference?

### ISSUE THREAD

**Issue by llmmddCoder** [deepjavalibrary/djl#3223]
## Description

The multi-classification model encounters an error during the inferenceMat lightgbmlib.delete_doubleArray() stage, while binary classification and others can execute normally.

<img width="540" alt="image" src="https://github.com/deepjavalibrary/djl/assets/21168273/e59aa2a7-e806-4814-84de-e5ba3672c049">

**Comment by frankfliu** [comment]
This sounds like a bug in lightgbm. You might want to create an issue in https://github.com/microsoft/LightGBM
