### ISSUE TITLE
[pytorch] UnsatisfiedLinkError on Windows11/Intel

### ISSUE THREAD

**Issue by enpasos** [deepjavalibrary/djl#3232]
When running operations on pytorch engine 2.3.0 on a Windows11/Intel board, I get a java.lang.UnsatisfiedLinkError. 
While the operations run fine on pytorch engine 2.2.2 on the same system.

It seems that torch_cpu.dll needs the dependency mkl_intel_thread.1.dll which is missing. 

Windows version: 11 Pro, 23H2, 22631.3593
CPU: Intel(R) Xeon(R) E-2286M
DJL: 0.29.0-SNAPSHOT as of 2024-05-31

**Comment by frankfliu** [comment]
Yes, this is known PyTorch issue, PyTorch will statically link mkl in 2.3.1.

**Comment by frankfliu** [comment]
The default PyTorch version for DJL is still 2.2.2

**Comment by enpasos** [comment]
Thanks for the info. I see: The solution for my case is to stay with 2.2.2 until 2.3.1. Then no problem on DJL side.

**Comment by enpasos** [comment]
I tried with pytorch engine 2.3.1 on djl 0.29.0. I still see a linkage problem with mkl. Should it work?

**Comment by frankfliu** [comment]
2.3.1 should work on Windows: https://github.com/deepjavalibrary/djl-demo/actions/runs/10027117347/job/27712357407

**Comment by enpasos** [comment]
Thx for the info. I ran the canary test locally and still see the same error as when running my code

` java.lang.UnsatisfiedLinkError: C:\Users\enpasos\.djl.ai\pytorch\2.3.1-cu121-win-x86_64\torch_cpu.dll: Can't find dependent libraries`

Dependencies(x64) claims ...
![grafik](https://github.com/user-attachments/assets/682362b4-eb1f-4466-a5d6-16a6fe592535)

**Comment by frankfliu** [comment]
Oh, you are using cu121 for windows. It seems we missed a couple files in the `files.txt` file (We don't have window GPU test to catch the issue).

Would you please remove cache folder and try it again.

If you use CPU, it should works.

**Comment by enpasos** [comment]
I tried (on cu121) with my code and the canary test. Both worked perfectly. Thx, for the solution!
