### ISSUE TITLE
Torchscript is in maintenance mode. Supporting it's replacement 

### ISSUE THREAD

**Issue by ethiel** [deepjavalibrary/djl#3348]
We all know that DJL supports loading models saved into Torchscript format. But since Torchscript is already on maintenance mode and it won't be supported to add features or solving bugs, is it planned to support a new way to load python models (like torch.export, for instance) or will be the PyTorch engine deprecated?.

**Comment by frankfliu** [comment]
`torch.export` is still an experimental feature and in active development stage. We are waiting for their GA release.

**Comment by frankfliu** [comment]
If you run into issues with torchscript, you might want to try convert it to onnx

**Comment by ethiel** [comment]
My issue is the infamous "Torchscript pin device issue" which we solved by creating different models pinned for different devices. I have tried with onnx and the results were promising despite the extra effort for transforming all our models.
Thanks for answering so fast, both of you :)

**Comment by ethiel** [comment]
I close this issue since onnx is a solution. 
Thanks.
