### ISSUE TITLE
Support PyTorch 2.4

### ISSUE THREAD

**Issue by enpasos** [deepjavalibrary/djl#3364]
It is so great that DJL already supports PyTorch 2.3.1!

Just a hint: [PyTorch 2.4](https://pytorch.org/blog/pytorch2-4/) has just been released on July 24th. It supports CUDA 12.4.

**Comment by frankfliu** [comment]
https://github.com/deepjavalibrary/djl/pull/3369

**Comment by enpasos** [comment]
Runs nicely on my system - Win11, cuda 12.4.1, cudnn 9.2.1, Java 21.  Thank you :-)
