### ISSUE TITLE
To train in TF engine

### ISSUE THREAD

**Issue by SidneyLann** [deepjavalibrary/djl#337]
## Description
TF engine can only be used for inference, when can be used for trainning?

### Will this change the current api? How?
Yes. Wrap TF java api 2.x.

### Who will benefit from this enhancement?
Many people.

## References
- list reference and related literature
- list known implementations
https://github.com/tensorflow/java
https://gitter.im/tensorflow/sig-jvm

**Comment by lanking520** [comment]
Currently DJL does not offer training feature on TensorFlow. But we will have this done when it is necessary. You are more than welcome to contribute to the TF training feature and we will be happy to help you on the way :)

**Comment by lanking520** [comment]
We had an RFC in TF JNI build in discussion now. @SidneyLann Have you tried to train with DJL with MXNet engine? It is mostly working.

**Comment by SidneyLann** [comment]
I found DL4J has more functinalities than MXNet java, lik conv1d, conv2d, conv3d, conv4d and gnn.

**Comment by stu1130** [comment]
@SidneyLann we also have conv1d, conv2d, conv3d. Modern frameworks like TF, PT doesn't have conv4d. Can you elaborate your use case? Thanks

**Comment by SidneyLann** [comment]
Human action in a video(a sequence of images), like conv3d+sequence images, it maybe not a realy conv4d.
