### ISSUE TITLE
Memory Leak when calling RsNDArray.toByteBuffer()

### ISSUE THREAD

**Issue by markap14** [deepjavalibrary/djl#3413]
## Description
When calling NDArray.toFloatArray() or NDArray.toByteBuffer(), it appears to use native memory that is never released.

### Expected Behavior
Native memory should not be allocated or should be released

### Error Message
10's of GB of ram are used by the Java process and then the process gets killed with sigkill -9

## How to Reproduce?
It is easily reproduced with the following code in a unit test or `public static void main(String[] args) {...}` method:

```
// Create a small float buffer and fill it with some 0's
final FloatBuffer buffer = FloatBuffer.allocate(3 * 128 * 384);
final float[] small = new float[384];

for (int i = 0; i < buffer.capacity() / small.length; i++) {
    buffer.put(small);
    buffer.rewind();
}

// Create an NDArray and constantly call array.toByteBuffer();
try (final NDManager manager = NDManager.newBaseManager();
     final NDArray array = manager.create(buffer, new Shape(3, 128, 384))) {

    for (int i = 0; i < 1_000_000; i++) {
        // Here, we can use array.toByteBuffer(false) or array.toByteBuffer(true) or array.toFloatArray(), it doesn't matter.
        array.toByteBuffer(false);
    }
}
```

Same result happens using the following code:
```
// Create a small float buffer and fill it with some 0's
final FloatBuffer buffer = FloatBuffer.allocate(3 * 128 * 384);
final float[] small = new float[384];

for (int i = 0; i < buffer.capacity() / small.length; i++) {
    buffer.put(small);
    buffer.rewind();
}

// Continually create a new NDArray to wrap the buffer, then convert to a float array
try (final NDManager manager = NDManager.newBaseManager()) {
    for (int i = 0; i < 1_000_000; i++) {
        buffer.rewind();

        try (final NDArray array = manager.create(buffer, new Shape(3, 128, 384))) {
            array.toFloatArray();
        }
    }
}
```

### Steps to reproduce
Run the above code

**Comment by hansonhanshuo** [comment]
I also encountered the same problem. Do you have any plans for when to release it @frankfliu

**Comment by frankfliu** [comment]
> I also encountered the same problem. Do you have any plans for when to release it @frankfliu

See: https://github.com/deepjavalibrary/djl?tab=readme-ov-file#release-notes, for the mean time, you can use SNAPSHOT release for testing
