### ISSUE TITLE
SAM系列模型能力非常强大，未来是否有计划集成SAM模型到djl的modelzoo中

### ISSUE THREAD

**Issue by yongyupei** [deepjavalibrary/djl#3448]
## Description

(A clear and concise description of what the feature is.)
SAM系列模型能力非常强大，未来是否有计划集成SAM模型到djl的modelzoo中，通过集成SAM系列模型分割一切的能力扩展djl平台的应用范围；

## References

- list reference and related literature
- list known implementations

**Comment by frankfliu** [comment]
I created a PR for sam2 model: https://github.com/deepjavalibrary/djl/pull/3449
