### ISSUE TITLE
Change Pikachu dataset to custom dataset and got some error 将皮卡丘训练的案例中的数据集改成本机数据集报错问题

### ISSUE THREAD

**Issue by XiaoQiao6Shui** [deepjavalibrary/djl#345]
## Question
`package com.djl.examples.inference;

import java.io.IOException;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.apache.commons.cli.ParseException;

import com.djl.examples.training.util.Arguments;

import ai.djl.Device;
import ai.djl.Model;
import ai.djl.basicdataset.ImageFolder;
import ai.djl.basicdataset.ImageFolder.Builder;
import ai.djl.basicmodelzoo.cv.object_detection.ssd.SingleShotDetection;
import ai.djl.metric.Metrics;
import ai.djl.modality.cv.transform.Resize;
import ai.djl.modality.cv.transform.ToTensor;
import ai.djl.ndarray.types.Shape;
import ai.djl.nn.Block;
import ai.djl.nn.SequentialBlock;
import ai.djl.training.DefaultTrainingConfig;
import ai.djl.training.EasyTrain;
import ai.djl.training.Trainer;
import ai.djl.training.TrainingResult;
import ai.djl.training.evaluator.BoundingBoxError;
import ai.djl.training.evaluator.SingleShotDetectionAccuracy;
import ai.djl.training.listener.CheckpointsTrainingListener;
import ai.djl.training.listener.TrainingListener;
import ai.djl.training.loss.SingleShotDetectionLoss;
import ai.djl.translate.Pipeline;
import ai.djl.translate.TranslateException;

public class TrainDemo {
	public static void main(String[] args) throws ParseException, IOException, TranslateException {
		Arguments arguments = Arguments.parseArgs(args);
		Model model = Model.newInstance("face");
		model.setBlock(getSsdTrainBlock());
		DefaultTrainingConfig config = setupTrainingConfig(arguments);
		try (Trainer trainer = model.newTrainer(config)) {
			trainer.setMetrics(new Metrics());
			Shape inputShape = new Shape(arguments.getBatchSize(), 3, 256, 256);
			trainer.initialize(inputShape);
			ImageFolder trainingSet = getImageFolder("D:\\training");
			ImageFolder validateSet = getImageFolder("D:\\validate");
			EasyTrain.fit(trainer, arguments.getEpoch(), trainingSet, validateSet);
			System.out.println(trainer.getTrainingResult());
		}

	}

	// 创建的
	private static ImageFolder getImageFolder(String path) throws IOException, TranslateException {
		int NEW_WIDTH = 28;
		int NEW_HEIGHT = 28;
		int BATCH_SIZE = 1;
		Builder builder = ImageFolder.builder();
		builder.setRepositoryPath(Paths.get(path));
		Pipeline pipeline = new Pipeline();
		pipeline.add(new Resize(NEW_WIDTH, NEW_HEIGHT));
		pipeline.add(new ToTensor());
		builder.optPipeline(pipeline);
		builder.setSampling(BATCH_SIZE, true);
		ImageFolder build = builder.build();
		build.prepare();
		return build;
	}

   //照抄自皮卡丘案例
	public static Block getSsdTrainBlock() {
		int[] numFilters = { 16, 32, 64 };
		SequentialBlock baseBlock = new SequentialBlock();
		for (int numFilter : numFilters) {
			baseBlock.add(SingleShotDetection.getDownSamplingBlock(numFilter));
		}

		List<List<Float>> sizes = new ArrayList<>();
		List<List<Float>> ratios = new ArrayList<>();
		for (int i = 0; i < 5; i++) {
			ratios.add(Arrays.asList(1f, 2f, 0.5f));
		}
		sizes.add(Arrays.asList(0.2f, 0.272f));
		sizes.add(Arrays.asList(0.37f, 0.447f));
		sizes.add(Arrays.asList(0.54f, 0.619f));
		sizes.add(Arrays.asList(0.71f, 0.79f));
		sizes.add(Arrays.asList(0.88f, 0.961f));

		return SingleShotDetection.builder().setNumClasses(1).setNumFeatures(3).optGlobalPool(true).setRatios(ratios)
				.setSizes(sizes).setBaseNetwork(baseBlock).build();
	}
	//照抄自皮卡丘案例
	private static DefaultTrainingConfig setupTrainingConfig(Arguments arguments) {
		String outputDir = arguments.getOutputDir();
		CheckpointsTrainingListener listener = new CheckpointsTrainingListener(outputDir);
		listener.setSaveModelCallback(trainer -> {
			TrainingResult result = trainer.getTrainingResult();
			Model model = trainer.getModel();
//			float accuracy = result.getValidateEvaluation("classAccuracy");
//			model.setProperty("ClassAccuracy", String.format("%.5f", accuracy));
//			model.setProperty("Loss", String.format("%.5f", result.getValidateLoss()));
		});

		return new DefaultTrainingConfig(new SingleShotDetectionLoss())
				.addEvaluator(new SingleShotDetectionAccuracy("classAccuracy"))
				.addEvaluator(new BoundingBoxError("boundingBoxError"))
				.optDevices(Device.getDevices(arguments.getMaxGpus()))
				.addTrainingListeners(TrainingListener.Defaults.logging(outputDir)).addTrainingListeners(listener);
	}
}
`
下面是日志信息
`SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/ykp/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/ykp/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.12.1/log4j-slf4j-impl-2.12.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
17:22:56.626 [main] DEBUG ai.djl.mxnet.jna.LibUtils - Loading mxnet library from: C:\Users\ykp\eclipse-workspace\FastAi\.\mxnet.dll
17:22:56.972 [main] DEBUG ai.djl.engine.Engine - Engine loaded from provider: MXNet
17:22:56.972 [main] DEBUG ai.djl.engine.Engine - Found default engine: MXNet
17:22:57.026 [main] INFO ai.djl.training.listener.LoggingTrainingListener - Training on: cpu().
17:22:57.027 [main] INFO ai.djl.training.listener.LoggingTrainingListener - Load MXNet Engine Version 1.7.0 in 0.037 ms.
17:22:58.624 [main] DEBUG ai.djl.basicdataset.AbstractImageFolder - Loaded 2995 images in D:\training\AFLW, class: 0
17:22:58.690 [main] DEBUG ai.djl.basicdataset.AbstractImageFolder - Loaded 8585 images in D:\training\lfw_5590, class: 1
17:22:58.798 [main] DEBUG ai.djl.basicdataset.AbstractImageFolder - Loaded 7876 images in D:\validate\net_7876, class: 0
17:22:58.864 [main] INFO ai.djl.training.listener.LoggingTrainingListener - forward P50: 13.510 ms, P90: 13.510 ms
Exception in thread "main" ai.djl.engine.EngineException: MXNet engine call failed: MXNetError: Check failed: param.kernel[0] <= dshape_nchw[2] + 2 * param.pad[0]: kernel size (2) exceeds input (1 padded to 1)
Stack trace:
  File "..\src\operator\nn\pooling.cc", line 190

	at ai.djl.mxnet.jna.JnaUtils.checkCall(JnaUtils.java:1808)
	at ai.djl.mxnet.jna.JnaUtils.imperativeInvoke(JnaUtils.java:502)
	at ai.djl.mxnet.jna.FunctionInfo.invoke(FunctionInfo.java:91)
	at ai.djl.mxnet.jna.FunctionInfo.invoke(FunctionInfo.java:75)
	at ai.djl.mxnet.engine.MxNDManager.invoke(MxNDManager.java:324)
	at ai.djl.mxnet.engine.MxNDManager.invoke(MxNDManager.java:342)
	at ai.djl.mxnet.engine.MxNDArrayEx.maxPool(MxNDArrayEx.java:274)
	at ai.djl.nn.pooling.Pool.maxPool2d(Pool.java:70)
	at ai.djl.nn.pooling.Pool.lambda$maxPool2dBlock$1(Pool.java:465)
	at ai.djl.nn.LambdaBlock.lambda$singleton$0(LambdaBlock.java:58)
	at ai.djl.nn.LambdaBlock.forward(LambdaBlock.java:68)
	at ai.djl.nn.Block.forward(Block.java:117)
	at ai.djl.nn.SequentialBlock.forward(SequentialBlock.java:133)
	at ai.djl.nn.Block.forward(Block.java:117)
	at ai.djl.basicmodelzoo.cv.object_detection.ssd.SingleShotDetection.forward(SingleShotDetection.java:79)
	at ai.djl.nn.Block.forward(Block.java:153)
	at ai.djl.training.Trainer.forward(Trainer.java:167)
	at ai.djl.training.EasyTrain.trainBatch(EasyTrain.java:80)
	at ai.djl.training.EasyTrain.fit(EasyTrain.java:45)
	at com.djl.examples.inference.TrainDemo.main(TrainDemo.java:48)
`
@hyandell Lanking

**Comment by XiaoQiao6Shui** [comment]
希望您能提供一个能在本机某个路径下的训练图像识别的案例

**Comment by frankfliu** [comment]
@XiaoQiao6Shui See: https://github.com/aws-samples/djl-demo/tree/master/footwear_classification

**Comment by XiaoQiao6Shui** [comment]
Can this run on arm platform ？Only predict @frankfliu

**Comment by frankfliu** [comment]
We only support android for now. There is an issue already: https://github.com/awslabs/djl/issues/195
We are currently:
1. looking into ARM build pipeline to enable arm base CI, so we can have ARM support.
2. we are also working on TVM support, that will have arm based support

**Comment by XiaoQiao6Shui** [comment]
@frankfliu I'll follow the example you gave me and replace the dataset with the local face dataset. After running, take any photo to test the accuracy rate is 1. There are 8000 face pictures trained. What is the reason for this?

**Comment by frankfliu** [comment]
Closing this old issue, feel free to raise a new old if you still have questions.
