### ISSUE TITLE
Inquiry About T5 Tokenizer Compatibility with HuggingFaceTokenizer in DJL

### ISSUE THREAD

**Issue by tigflanker** [deepjavalibrary/djl#3574]
## Description

Dear DJL Maintenance Engineer,

Happy New Year to you!

I hope this message finds you well. I have a query regarding the support for T5 tokenizer models (`spiece.model`) by `ai.djl.huggingface.tokenizers.HuggingFaceTokenizer`. When I attempt to instantiate the tokenizer using the following code:

```java
HuggingFaceTokenizer tokenizer = HuggingFaceTokenizer.newInstance(Paths.get("D:/Data/t5-efficient-tiny-update_step5/spiece.model"));
```

I encounter some compatibility error messages. Could you please confirm whether `HuggingFaceTokenizer` currently supports the T5 model's tokenizer (`spiece.model`)? If not, could you provide guidance on how to proceed or any updates on when such support might be available?

Thank you for your assistance.

**Comment by frankfliu** [comment]
@tigflanker 

DJL only support `FastTokenizer`, which means you have to use `tokenizer.json` file. If you the model doesn't provides `tokenizer.json` file you have to use `tokenizer.save_pretrained()` to convert it.

For T5 model you can use the following code to load it:

```
        tokenizer = HuggingFaceTokenizer.newInstance("google/t5-efficient-tiny");
```

**Comment by tigflanker** [comment]
@frankfliu Thank you, Frank. I will try to convert it.
