### ISSUE TITLE
DJL serving plugin support

### ISSUE THREAD

**Issue by frankfliu** [deepjavalibrary/djl#591]
## Description

DJL serving itself is a web container, it's capable to serve static web page and customized REST API calls. We'd like to allow user to add customized feature to DJL serving without making changes to DJL serving core code base.

[ ] Plugin framework design
[ ] PluginManager to load plugin and it's metadata
[ ] Implement static page URLHandler as plugin
[ ] Implement DJL serving management portal as plugin
[ ] Implement DJL serving monitoring as plugin
[ ] Implement DJL model browser as plugin

**Comment by ebamberg** [comment]
@frankfliu I would like to pick this up. and at least make a start with the PluginManager/framework. 
I have no write access to assign this to me. Can we flag this ?

**Comment by stu1130** [comment]
@ebamberg I just assigned it to you

**Comment by frankfliu** [comment]
@ebamberg 
Github requires you to comments the issue first. Otherwise we are not able to assign it to you. So please comment on the issue if you are interested, then we can assign it to you.

**Comment by ebamberg** [comment]
> @ebamberg
> Github requires you to comments the issue first. Otherwise we are not able to assign it to you. So please comment on the issue if you are interested, then we can assign it to you.

I commented this issue 4 days ago. Or somewhere else where I have to drop a comment ?

**Comment by frankfliu** [comment]
@ebamberg This issue is currently assigned to you, you should be able to move the status from "to do" to "In progress". You can find "Projects" section in the right side of this issue.
