### ISSUE TITLE
[Question] How to make custom dataset 自定义数据集问题

### ISSUE THREAD

**Issue by ma2695212419** [deepjavalibrary/djl#655]
我自己有一些目标检测数据，我如何构建自己的数据集并训练目标检测，并定位到目标

------------------------------

I had some Object Detection dataset. Just wondering how to build my own dataset in DJL and run Object Detection?

**Comment by Jzow** [comment]
您好，您可以参考djl官网如何创建自定义的数据集

[创建数据集](https://docs.djl.ai/docs/development/how_to_use_dataset.html)

**Comment by ma2695212419** [comment]
我阅读了官网的例子，我的数据是有坐标的，而官网的示例没有，万分感谢，我是一个新手

**Comment by ma2695212419** [comment]
还有就是关于目标的定位问题，如何进行转换
我看示例的坐标类似于0.46545这种

**Comment by stu1130** [comment]
You can refer to [CocoDetection](https://github.com/awslabs/djl/blob/master/basicdataset/src/main/java/ai/djl/basicdataset/cv/CocoDetection.java) where each image has multiple bounding boxees
