### ISSUE TITLE
Rename ModelZoo, ZooModel

### ISSUE THREAD

**Issue by cowwoc** [deepjavalibrary/djl#73]
I suggest renaming ModelZoo, ZooModel classes because:

1) It's not intuitive when you should use one versus the other (the name doesn't make it obvious).
2) If this is meant to model a collection of models, please just call it a ModelCollection. The use of the word "Zoo" doesn't add any useful meaning to first-time readers and in my case just caused confusion.

Just my 2 cents :)

**Comment by frankfliu** [comment]
@cowwoc thanks for your suggestion. Here is my thought:
1. ZooModel is indeed not intuitive. But I just could not find a good name. We are open to suggest a better class name
2. ModelZoo may be confusion for user who not familiar with DL. But actually it's widely used in DL world, TF/PT/MXNet/Keras all has Model Zoo concept. I think it's OK to introduce new concept to new Java user. ModelZoo is meant to be extended. User can create their own ModelZoo (e.g. MyNlpModelZoo, etc), ModelCollection is a bit too generic.  when creating subClass, MyNlpModelCollection is more like a variable name then a class name.

**Comment by cowwoc** [comment]
This sounds like terminology specific to the NN space. Coming from a Java perspective, I don't find `ModelCollection` to be too generic. You could also try `ModelBundle`, `ModelModule` (similar to Tensorflow Module), `Models` or even `Bundle`, `Module` without the model name in it.

Another question is whether you even need an interface. Maybe all you need is a concrete implementation that users call to load their models. Is subclassing strictly necessary?

**Comment by frankfliu** [comment]
Today, it seems ModelZoo class has been well accepted.
And developers are happy with ZooModel as well.
Closing this RFC if there isn't a better alternative come up.
