### ISSUE TITLE
Memory/Device management cpu and gpu

### ISSUE THREAD

**Issue by ThomasZiegenhein** [deepjavalibrary/djl#740]
Great work with the djl package, very nice handling, and great performance!

## Description
I have a machine with a GPU, but I want to use only the CPU for training a model. In general, it works to set the devices to CPU and to compute everything on the CPU. However, the memory of the GPU is still used, which I cannot avoid. A small code example is below taken from a loop over the batches:

                        NDList data = batch.getData();
                        NDList label = batch.getLabels();
                        Device[] a = trainer.getDevices();
                        Device b = data.head().getDevice();
                        Device c = label.head().getDevice();
                        Device d = trainer.getModel().getNDManager().getDevice();
                        System.out.println("length a:" + a.length);
                        System.out.println("a:" + a[0]);
                        System.out.println("b:" + b);
                        System.out.println("c:" + c);
                        System.out.println("d:" + d);
                        //Here in the forward step are around 1 GB GPU RAM allocated
                        NDList forw = trainer.forward(data, label);

### Expected Behavior
The GPU is not used.

### Error Message
Something is allocated in the GPU RAM

## What have you tried to solve it?

Set every possible device I could find to CPU with Device.cpu()

## Environment Info

djl 0.10.0

```
PASTE OUTPUT HERE
```

length a:1
a:cpu()
b:cpu()
c:cpu()
d:cpu()

Thank you and best wishes
Thomas

**Comment by stu1130** [comment]
@ThomasZiegenhein which engine are you using? If you want to train a model with CPU, you can set optDevice(Device.cpu()) in DefaultTrainingConfig

**Comment by ThomasZiegenhein** [comment]
@stu1130 thanks for the quick answer. I use the MXNet engine 

ai.djl.mxnet:mxnet-engine:0.10.0

Yes I use the DefaultTrainingConfig with .optDevices(new Device[]{Device.cpu()}). And nothing is computed on the GPU during training.

I tried a little bit more around and can more specify the problem - sorry if it gets confusing with my initial posting:

My default device (Device.defaultDevice()) is gpu(0). When I load a model and data, it has the gpu(0) attached to it. When I set  .optDevices(new Device[]{Device.cpu()}), everything is computed on the CPU. But, in the first loop over my batches, the GPU RAM is used once. Now I try forcing to load my model and data to the Device.cpu(). When I do this, the GPU RAM is not used but I get the following error message in the backward step: 

 MXNet engine call failed: MXNetError: Check failed: !AGInfo: :IsNone(*i)

**Comment by stu1130** [comment]
@ThomasZiegenhein can I get the code snippet that can reproduce the issue?

Usually when you do any operation on GPU, engine(mxnet) will reserve certain memory as a pool because the cudaMalloc() is pretty expensive. and it will not free the pool until the program(process) exit

**Comment by ThomasZiegenhein** [comment]
@stu1130 thanks for your reply and sorry for my late response.

I try to reproduce it in a minimal example in the next hours/days.

When I use everywhere _Device.cpu()_ (DefaultTrainingConfig, Model,RandomAccessDataset), I get the following error message when I call the _backward()_ method from the GradientCollector ( _Engine.getInstance().newGradientCollector()_ or over the trainer _trainer.newGradientCollector()_ makes no difference) 

_MXNet engine call failed: MXNetError: Check failed: !AGInfo: :IsNone(*i)_

When I leave everything the same, but create a new Instance of Model on the default device of the Engine, which is the GPU ( _Model mod = Model.newInstance(modelName, Engine.getInstance().defaultDevice());_ ) I don't get the error message but in the forward ( _trainer.forward(data, label)_ ) step memory is allocated to the GPU. This makes somehow sense since the trainer is created from the model which is on the GPU: _mod.newTrainer(config)_ . However, nothing is computed on the GPU ever, except in the first epoch, when the memory is allocated to the GPU.

The problem is in the end not that memory is allocated on the GPU but that the _MXNet engine crashes when I put the model on the CPU instead of the GPU - but it seems that these things are somehow connected. On my laptop, without a GPU everything works fine when I use the cpu() device.

**Comment by stu1130** [comment]
That sounds like a bug. Do you have complete error stacktrace for 
_MXNet engine call failed: MXNetError: Check failed: !AGInfo: :IsNone(*i)_

**Comment by ThomasZiegenhein** [comment]
Sorry for the delay, I prepared a minimum example here:

https://github.com/ThomasZiegenhein/MinExGPUCPUdjl

It seems that the gradient collector is not attached to the model. I don't really see from the API how I can check if it is attached or the gradients are recorded -  I used the EasyTrain.java from the djl/example repo to make it more general. The error stack trace is:

Exception in thread "main" ai.djl.engine.EngineException: MXNet engine call failed: MXNetError: Check failed: !AGInfo: :IsNone(*i): Cannot differentiate node because it is not in a computational graph. You need to set is_recording to true or use autograd.record() to save computational graphs for backward. If you want to differentiate the same graph twice, you need to pass retain_graph=True to backward.
Stack trace:
  File "..\src\imperative\imperative.cc", line 295

	at ai.djl.mxnet.jna.JnaUtils.checkCall(JnaUtils.java:1909)
	at ai.djl.mxnet.jna.JnaUtils.autogradBackward(JnaUtils.java:663)
	at ai.djl.mxnet.engine.MxGradientCollector.backward(MxGradientCollector.java:117)
	at ai.djl.mxnet.engine.MxGradientCollector.backward(MxGradientCollector.java:106)
	at ai.djl.training.EasyTrain.trainBatch(EasyTrain.java:95)
	at ai.djl.training.EasyTrain.fit(EasyTrain.java:53)
	at minexample.djl.cpugpumgmt.Run.main(Run.java:47)


Thank you! Let me know if I can help somehow

**Comment by ThomasZiegenhein** [comment]
The problem was, that the gradients of the Parameter.array (NDArray) are not attached when I load an MXNet Model from outside in.
since the Parameter.array is private, I cannot really call `array.attachGradient(gradientFormat)` from outside with the standard Gradle releases. The workaround is to call initialize on the parameters - since the parameters are initialized/loaded, the Parameter.array is not changed but only the gradient is attached.

The model is evaluated before training so I go forward through the network. I couldn't find why it was working on the gpu but not on the cpu. With the code below everything works:

`MxModel mod = // some load method
                    mod.getBlock().setInitializer(Initializer.ONES);                   
                    for (Parameter parameter : mod.getBlock().getParameters().values()) {
                        if(!parameter.isInitialized()){
                            System.out.println("Block not initialized");
                            throw new MalformedModelException("Model not initialized");
                        }
                        parameter.initialize(mod.getNDManager(), mod.getDataType(), new Shape[]{mod.describeInput().get("data")});
                    }`

**Comment by aksrajvanshi** [comment]
@ThomasZiegenhein I tried running your code with the given changes. Did you make any other changes since I get the gradient values are all zeros error.

**Comment by ThomasZiegenhein** [comment]
@aksrajvanshi yes the gradients are zeros (labels = 0 equals predictions = 0) - the error was that the gradient collector didn't have any NDArrays attached. So when the gradients are zero - the collector has them attached and everything works as it should. For me, the gradients were attached when the MXNet model was loaded on the GPU, but were not attached when the model was loaded on the CPU. Calling the array.attachGradient() for the model parameters via the parameter.initialize (the array in parameters is private), solved the unattached gradients.

**Comment by aksrajvanshi** [comment]
Ok. The reason I asked was I made the changes you did and still getting the gradient zero error. I see the parameters are getting initialized.

**Comment by ThomasZiegenhein** [comment]
The gradient zero is not the problem, when you don't initialize the MXModel by hand, you get `MXNet engine call failed: MXNetError: Check failed: !AGInfo: :IsNone(*i)` , which was the problem.

**Comment by aksrajvanshi** [comment]
I understand :) The reason I'm asking about it is even after the fix you suggest, the code is throwing errors.

**Comment by ThomasZiegenhein** [comment]
Ouh, yeah I am sorry :) The example case might be too simple, I created the example to show the original error. I think my example MXModel which is loaded in might produce no non-zero-gradients, with an MLP created with djl it was actually training when I remember correctly.

**Comment by aksrajvanshi** [comment]
@ThomasZiegenhein So the problem seems to be from the model loading. The model loaded needs to have a layer that has params with attached gradients. In your case, if we look into the `lossValue`, the property `hasGradient()` evaluates to false. That is because the model you imported doesn't have params with gradients attached and nothing to do learning from. 

@frankfliu can add more to it if you feel it can be explained better.
