### ISSUE TITLE
sklearn onnx TFIDF 

### ISSUE THREAD

**Issue by jonathanfostercannon** [deepjavalibrary/djl#803]
## Description

I found this onnx sklearn implementation https://docs.djl.ai/jupyter/onnxruntime/machine_learning_with_ONNXRuntime.html, and am exploring DJL Onnx as a solution to implement tfidf vectorization as found here: http://onnx.ai/sklearn-onnx/auto_examples/plot_tfidfvectorizer.html#sphx-glr-auto-examples-plot-tfidfvectorizer-py 

The conversion from python happens here-- 

```python
model_onnx = convert_sklearn(
    pipeline, "tfidf",
    initial_types=[("input", StringTensorType([None, 2]))],
    options=seps, target_opset=12)
```

and the input to the model is StringTensorType. 

I'm able to serialize the TFIDF model successfully on the python end and load it in DJL. 

However, in DJL, I found that the NDList class doesn't support String[], only byte[] or numerical types--

https://javadoc.djl.ai/api/0.2.0/ai/djl/ndarray/NDManager.html#create-boolean-

```java

public class StringQuery {

    public byte[] queryBytes;

    public StringQuery(String query) {
        this.queryBytes = query.getBytes();
    }
}

// VectorizerTranslator implements Translator<StringQuery, NDList> 
    public NDList processInput(TranslatorContext ctx, StringQuery stringQuery) {
        NDArray array = ctx.getNDManager().create(stringQuery.queryBytes, new Shape(1, 1));
        return new NDList(array);
    }
```

### Error Message
(Paste the complete error message, including stack trace.)

This runs, but when I call the model: 

```java
ZooModel<StringQuery, Classifications> model = ModelZoo.loadModel(criteria);
Predictor<StringQuery, Classifications> predictor = model.newPredictor();         
StringQuery predictorInput = new StringQuery("query");
NDList prediction = predictor.predict(predictorInput);
```

I get: 

```
Caused by: ai.onnxruntime.OrtException: Error code - ORT_INVALID_ARGUMENT - 
message: Unexpected input data type. Actual: (N11onnxruntime17PrimitiveDataTypeIaEE) , expected: (N11onnxruntime17PrimitiveDataTypeISsEE)
```

I can't find the code where those data types are defined, but this is somewhat obviously a mismatch between "StringTensorType" in skl2onnx and byte[] in the DJL translator that the underlying libraries can't reconcile.  

Similarly, if I switch the input to CharBuffer, I get:

```
Caused by: java.lang.IllegalArgumentException: 
Unsupported buffer type: HeapCharBuffer
        at ai.djl.ndarray.types.DataType.fromBuffer(DataType.java:109) ~[api-0.10.0.jar:na]
```

I can't find a datatype in skl2onnx that corresponds to byte[]: 
https://github.com/onnx/sklearn-onnx/blob/master/skl2onnx/common/data_types.py

```python
from onnxconverter_common.data_types import (  # noqa
    Int64TensorType, Int32TensorType, BooleanTensorType,
    FloatTensorType, StringTensorType, DoubleTensorType,
    DictionaryType, SequenceType)
```

My question is-- am I missing something and is there a way around this issue? 

Otherwise, I should conclude that DJL onnx isn't a solution for my use case?

**Comment by frankfliu** [comment]
@jonathanfostercannon We added String tensor support in 0.11.0-SNAPSHOT version, you should be able to create String type NDArray: https://github.com/awslabs/djl/blob/master/api/src/main/java/ai/djl/ndarray/NDManager.java#L261
```
NDManager manager;
String[] strings;
NDArray array = manager.create(strings);
```

**Comment by frankfliu** [comment]
@jonathanfostercannon You need add snapshot maven repo:
```
    repositories {
        jcenter()
        maven {
            url 'https://oss.sonatype.org/content/repositories/snapshots/'
        }
    }

```

**Comment by jonathanfostercannon** [comment]
@frankfliu sorry, I'm still getting the type error:

```java
error: no suitable method found for create(String[],Shape
        NDArray array = ctx.getNDManager().create(stringQuery.query, new Shape(1, 1));
                                          ^
    method NDManager.create(Buffer,Shape) is not applicable
      (argument mismatch; String[] cannot be converted to Buffer)
    method NDManager.create(Shape,DataType) is not applicable
      (argument mismatch; String[] cannot be converted to Shape)
    method NDManager.create(float[],Shape) is not applicable
      (argument mismatch; String[] cannot be converted to float[])
    method NDManager.create(int[],Shape) is not applicable
      (argument mismatch; String[] cannot be converted to int[])
    method NDManager.create(double[],Shape) is not applicable
      (argument mismatch; String[] cannot be converted to double[])
    method NDManager.create(long[],Shape) is not applicable
      (argument mismatch; String[] cannot be converted to long[])
    method NDManager.create(byte[],Shape) is not applicable
      (argument mismatch; String[] cannot be converted to byte[])
    method NDManager.create(boolean[],Shape) is not applicable
      (argument mismatch; String[] cannot be converted to boolean[])
```

Which was the previous error. 

my gradle build: 

```
repositories {
	mavenCentral()
	jcenter()
	maven {
		url 'https://oss.sonatype.org/content/repositories/snapshots/'
	}
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'com.google.code.gson:gson:2.8.6'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'

	implementation "ai.djl:api:0.11.0-SNAPSHOT"
	runtimeOnly "ai.djl.onnxruntime:onnxruntime-engine:0.11.0-SNAPSHOT"
	runtimeOnly "ai.djl.pytorch:pytorch-engine:0.11.0-SNAPSHOT"

	runtimeOnly "com.microsoft.onnxruntime:onnxruntime:1.4.0"
	runtimeOnly "ai.djl.pytorch:pytorch-native-auto:1.7.0"
}

```

I'm a bit confused, the signature of the method you posted is `create(String[] data)`, but when I remove the Shape from the call above-- `create(stringQuery.query, new Shape(1, 1))` -- I get a null error.

**Comment by frankfliu** [comment]
`NDManager` only expose `create(String[] str)` API, if you want to call `create(String[] str, Shape shape)`, you have to use `OrtNDManager`:

```
(OrtNDManager)ctx.getNDManager().create(stringQuery.query, new Shape(1, 1));
```

And you have to change your dependency:
```
implementation "ai.djl.onnxruntime:onnxruntime-engine:0.11.0-SNAPSHOT"
runtimeOnly "com.microsoft.onnxruntime:onnxruntime:1.7.0"

# runtimeOnly "ai.djl.pytorch:pytorch-engine:0.11.0-SNAPSHOT"
# runtimeOnly "ai.djl.pytorch:pytorch-native-auto:1.7.0"
```

If you include pytorch engine with onnxruntime engine, you may not be able to OrtNDManager.

**Comment by frankfliu** [comment]
@jonathanfostercannon 
Feel free to reopen the issue if you have further questions.
