### ISSUE TITLE
NullPointerException on trainer initializing

### ISSUE THREAD

**Issue by nikkisingh111333** [deepjavalibrary/djl#858]
hey why i m getting error while setting shape with trainer and initializing it heres my code:

**_`_ Model model = Model.newInstance("pikachu-ssd");
            float detectionThreshold = 0.6f;
            // load parameters back to original training block
            model.setBlock(ssd);
             // append prediction logic at end of training block with parameter loaded
            Block ssdTrain = model.getBlock();
            model.setBlock(ssdPredict);
          var epoch=10;
    var train_config= new DefaultTrainingConfig(new SingleShotDetectionLoss())
                .addEvaluator(new SingleShotDetectionAccuracy("classAccuracy"))
                .addEvaluator(new BoundingBoxError("boundingBoxError"))
                .optDevices(new Device[]{Device.gpu(0)})
                .addTrainingListeners(TrainingListener.Defaults.logging());
                Trainer trainer = model.newTrainer(train_config);
 SingleShotDetectionTranslator translator =
                    SingleShotDetectionTranslator.builder()
                            .addTransform(new ToTensor())
                            .optSynset(Collections.singletonList("pikachu"))
                            .optThreshold(detectionThreshold)
                            .build();
                            trainer.setMetrics(new Metrics());
                            System.out.println("whaaat");
               trainer.initialize(new Shape(150, 3, 256, 256));
                 for (int i = 0; i < epoch; ++i) {
                         int index = 0;
                          for (var batch : trainer.iterateDataset(pikachuData)) {
                              System.out.println("loo");
                               EasyTrain.trainBatch(trainer, batch);
                                 trainer.step();
                                 batch.close();
                          }
 // reset training and validation evaluators at end of epoch
                            trainer.notifyListeners(listener -> listener.onEpoch(trainer));
                  
  }_`_**

And I m Getting This :
`**     **java.lang.NullPointerException: null**

        at ai.djl.mxnet.engine.MxNDArray.createGradient(MxNDArray.java:244)
	
        at ai.djl.mxnet.engine.MxNDArray.attachGradient(MxNDArray.java:229)

	at ai.djl.nn.Parameter.initialize(Parameter.java:213)

	at ai.djl.nn.AbstractBlock.initialize(AbstractBlock.java:269)

	at ai.djl.nn.SequentialBlock.initializeChildBlocks(SequentialBlock.java:143)

	at ai.djl.nn.AbstractBlock.initialize(AbstractBlock.java:271)

	at ai.djl.nn.SequentialBlock.initializeChildBlocks(SequentialBlock.java:143)

	at ai.djl.nn.AbstractBlock.initialize(AbstractBlock.java:271)

	at ai.djl.basicmodelzoo.cv.object_detection.ssd.SingleShotDetection.initialize(SingleShotDetection.java:184)

	at ai.djl.nn.SequentialBlock.initializeChildBlocks(SequentialBlock.java:143)

	at ai.djl.nn.AbstractBlock.initialize(AbstractBlock.java:271)

	at ai.djl.training.Trainer.initialize(Trainer.java:113)

	at .(#249:1)**

`
No  clues whats pointing this error heres my maven and import tree take a look:

**%maven** ai.djl:api:0.10.0
%maven ai.djl:model-zoo:0.10.0
%maven ai.djl.mxnet:mxnet-engine:0.10.0
%maven ai.djl.mxnet:mxnet-model-zoo:0.10.0
%maven org.slf4j:slf4j-api:1.7.26
%maven org.slf4j:slf4j-simple:1.7.26
%maven net.java.dev.jna:jna:5.3.0
%maven ai.djl:basicdataset:0.10.0
// See https://github.com/awslabs/djl/blob/master/mxnet/mxnet-engine/README.md
// for more MXNet library selection options
%maven ai.djl.mxnet:mxnet-native-cu101mkl:1.7.0-backport
import ai.djl.Device;
import ai.djl.MalformedModelException;
import ai.djl.Model;
import ai.djl.basicdataset.cv.PikachuDetection;
import ai.djl.basicmodelzoo.cv.object_detection.ssd.SingleShotDetection;
//import ai.djl.examples.training.util.Arguments;
import ai.djl.inference.Predictor;
import ai.djl.metric.Metrics;
import ai.djl.modality.cv.Image;
import ai.djl.modality.cv.ImageFactory;
import ai.djl.modality.cv.MultiBoxDetection;
import ai.djl.modality.cv.output.DetectedObjects;
import ai.djl.modality.cv.transform.ToTensor;
import ai.djl.modality.cv.translator.SingleShotDetectionTranslator;
import ai.djl.ndarray.NDArray;
import ai.djl.ndarray.NDList;
import ai.djl.ndarray.types.Shape;
import ai.djl.nn.Block;
import ai.djl.nn.LambdaBlock;
import ai.djl.nn.SequentialBlock;
import ai.djl.training.DefaultTrainingConfig;
import ai.djl.training.EasyTrain;
import ai.djl.training.Trainer;
import ai.djl.training.TrainingResult;
import ai.djl.training.dataset.Dataset;
import ai.djl.training.dataset.RandomAccessDataset;
import ai.djl.training.evaluator.BoundingBoxError;
import ai.djl.training.evaluator.SingleShotDetectionAccuracy;
import ai.djl.training.listener.SaveModelTrainingListener;
import ai.djl.training.listener.TrainingListener;
import ai.djl.training.loss.SingleShotDetectionLoss;
import ai.djl.training.util.ProgressBar;
import ai.djl.translate.Pipeline;
import ai.djl.translate.TranslateException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;**
 
help me out please ..

**Comment by zachgk** [comment]
It looks like you are using a Jupyter notebook. If you want to use a debugger to help figure it out, it may be easier to switch to an IDE. What block are you using? Are you working based on the [TrainPikachu](https://github.com/awslabs/djl/blob/master/examples/src/main/java/ai/djl/examples/training/TrainPikachu.java) example?

**Comment by nikkisingh111333** [comment]
yes i m just getting started to play with detection problems...and trainPickachu example itself messy ..i mean i just did most of the part...i m using sequential block as ...evrything is copied from example...what i m doing wrong ..?

**Comment by nikkisingh111333** [comment]
hey i m waiting for reply please suggest me something kindly...

**Comment by zachgk** [comment]
Looking at your code again, you are setting the model to use ssdPredictBlock, but it should be ssdTrainBlock. The SingleShotDetectionLoss is expecting the output you would get from a train block

**Comment by nikkisingh111333** [comment]
i dont understand what it is...predict block inheriting ssdtrain box then adding output to it makes it fully connected network thats what i m assuming should be done....would you please like to send me the code with a little bit of modification that you are talking about..please ?

**Comment by aksrajvanshi** [comment]
```
Model model = Model.newInstance("pikachu-ssd");
float detectionThreshold = 0.6f;
// load parameters back to original training block
model.setBlock(ssd);
// append prediction logic at end of training block with parameter loaded
Block ssdTrain = model.getBlock();
model.setBlock(ssdPredict); 
var epoch=10;
```

In your code, the line `model.setBlock(ssdPredict); ` should be `model.setBlock(ssdTrain); ` since you had your Block named as ssdTrain just the line before. Your model comprises of Block structure.

**Comment by nikkisingh111333** [comment]
It worked. training is happening now ....

**Comment by nikkisingh111333** [comment]
hey after doing training on testing phase i m getting this result :
![Screenshot (52)](https://user-images.githubusercontent.com/49682940/115146760-88b34580-a075-11eb-89e6-b206288025b6.png)

my questions are:
is Non-Maximum Suppression happening bydefault or i need to make one and how ?
how to get bounding box covering all region ?
sugest me please

**Comment by zachgk** [comment]
There doesn't seem to be non-maximum suppression, so you would have to implement it yourself. You can use http://d2l.ai/chapter_computer-vision/anchor.html as a reference.

You shouldn't need to get a bounding box covering all regions, as the model should give you one. Note that the pikachu dataset is a simple example and I believe it uses the same image of pikachu as well. I don't think it would generalize well to new images (but it is just a simplified example anyway)

**Comment by nikkisingh111333** [comment]
Thanks for the tip! But what should I do? Now from here...And how will I
implement this model on my own dataset ...Please suggest me

**Comment by nikkisingh111333** [comment]
anchor parts seems too much complicated ...how can i simply get bounding
box of size of an object....please suggest something .?

**Comment by zachgk** [comment]
That is how. The model is not working right here. It should look like a single bounding box surrounding the entire pikachu. Because the model is not working well, it is seeing this single pikachu and thinking that it is many pikachus

If the model were working well, it should look like this: https://github.com/deepjavalibrary/djl/blob/master/examples/docs/object_detection.md where single bounding boxes directly surround the object

**Comment by nikkisingh111333** [comment]
OKK so what should i suppose to do now...???? ....should try yolo ..and train again....???

**Comment by zachgk** [comment]
I think the problem you are having here is just that the image is too big. The dataset is really stupid and only has the same exact pikachu image in the same exact size. That reason all of the bounding boxes the model is guessing are the same size is because it learned that there is only 1 correct pikachu size. But, your image has a bigger pikachu which is different from what it learned. You would either need to choose a test image more in line with the dataset or get a better dataset.

At this point, you could start working on your own dataset. I recommend using the https://github.com/deepjavalibrary/djl/blob/master/basicdataset/src/main/java/ai/djl/basicdataset/cv/ObjectDetectionDataset.java as a base for implementing your custom dataset and it should make it fairly easy.

**Comment by nikkisingh111333** [comment]
hey can you tell me where i can find this new BoundingBox(----) class all i
m seeing is just interface not actuall class ..
heres my code :
`
DetectedObjects detectedObjects = predictor.predict(image);
                image.drawBoundingBoxes(detectedObjects);

                // return number of pikachu detected
                 detectedObjects.getNumberOfObjects();
                  Map<String, List<Rectangle>> ret = new ConcurrentHashMap<>();

            int imageWidth = image.getWidth();
            int imageHeight = image.getHeight();
            Map<String,Float> prlist=new ConcurrentHashMap<>();
            List<DetectedObjects.DetectedObject> detections =
detectedObjects.items();
            int n=1;
            for (DetectedObjects.DetectedObject detection : detections) {
                String className = detection.getClassName();
                float probability = (float) detection.getProbability();
                Rectangle rect = detection.getBoundingBox().getBounds();

                double x =  rect.getX() * imageWidth;
                double y = rect.getY() * imageHeight;
                double w = rect.getWidth() * imageWidth;
                double h = rect.getHeight() * imageHeight;
                if(probability>0.97){
                 prlist.put(className+"_"+n,probability);
                 n++;
                }
                ret.compute(
                        className,
                        (k, list) -> {
                            if (list == null) {
                                list = new ArrayList<>();
                            }
                           list.add(new BoundingBox( x, y, w, h));

                            return list;
                        });
            }
`....???????????????

**Comment by frankfliu** [comment]
BoundingBox is an interface, there are three built-in implementations:
1. ai.djl.modality.cv.output.Rectangle
2. ai.djl.modality.cv.output.Mask
3. ai.djl.modality.cv.output.Landmark

In your cases, you can directly use Rectangle

**Comment by nikkisingh111333** [comment]
Thanks, I'll check it out. But I can't find Landmark class..Rectangle and
point mark are already there but where landmark..I m implementing face
detection translator where landmark is used..But cannot find symbol error
is popping...???

**Comment by frankfliu** [comment]
Landmark class in in the master branch: https://github.com/deepjavalibrary/djl/blob/master/api/src/main/java/ai/djl/modality/cv/output/Landmark.java

It's only available in 0.11.0-SNAPSHOT version.

**Comment by nikkisingh111333** [comment]
so it means i need to change it to cuda 11 and pytorch 11..

**Comment by frankfliu** [comment]
pytorch 1.8.1 still have cuda102 package: http://docs.djl.ai/pytorch/pytorch-engine/index.html#linux-gpu

**Comment by nikkisingh111333** [comment]
okk but how can i install cuda 10.2 for pytorch i currently have 10.1 ..i m googling for an hour but not getting it...i m getting this error always when i m loading pytorch model ..i m guessing this error is related to cuda version incompatibility..

`java.lang.NoClassDefFoundError: Could not initialize class ai.djl.repository.zoo.DefaultModelZoo
at ai.djl.repository.zoo.Criteria$Builder.optModelUrls(Criteria.java:390)
at .(#116:4)`

**Comment by frankfliu** [comment]
Closing old issue, feel free to re-open it if you still have questions.
