### ISSUE TITLE
Provide fast adaptation between Maven and springboot

### ISSUE THREAD

**Issue by jiasu-hezhip** [deepjavalibrary/djl#859]
When I deployed a pytorch project, I didn't learn how to build a server with Python, and I was very familiar with Java, so I want that a java project can directly use the trained pytorch model. Djl is a good project, but i hope to provide Maven support and project management integrated in SpringCloud.

**Comment by frankfliu** [comment]
DJL package is published to maven central, you can use maven to create your project.

DJL examples uses both gradle and maven build script, you can find the pom.xml: https://github.com/awslabs/djl/blob/master/examples/pom.xml

DJL also support Srpingboot starter: https://github.com/frankfliu/djl-spring-boot-starter
And you can find demo for using springbootstarter: https://github.com/frankfliu/djl-spring-boot-starter-demo

**Comment by frankfliu** [comment]
Feel free to reopen this issue if you have further questions.
