### ISSUE TITLE
Raspberry Pi 4B Failed to load MXNet native library

### ISSUE THREAD

**Issue by hackedbyxx** [deepjavalibrary/djl#860]
When I first  run,it shows dowload info,it looks like has download  the library, but even I can't see the path /root/.djl.ai/ from the error message `Native library (root/.djl.ai/mxnet/1.7.0-backport-mkl-linux-x86_64/libmxnet.so) not found in resource path`,
I tried to read the issue  #375 , and download mxnet on Raspberry ,but i don't know how to be used on DJL

**Comment by frankfliu** [comment]
DJL doesn't provide native library for Rassberry PI by default. You have to build MXNet from source and copy libmxnet.so file manually to your machine.
then you need to set MXNET_LIBRARY_PATH environment variable:

```
export MXNET_LIBRARY_PATH=/root/mxnet/libmxnet.so
```

See: http://docs.djl.ai/docs/development/troubleshooting.html#4-how-to-run-djl-using-other-versions-of-apache-mxnet

**Comment by Applooza** [comment]
My workaround is to replace libmxnet.so in /root/.djl.ai/mxnet/1.8.0-mkl-linux-aarch64. Also, for anyone else building mxnet from source, make sure you checkout the 1.8.x branch before you start building to avoid doing it twice...

**Comment by DenisNovac** [comment]
For anyone who bump into this struggling to pack app with DJL in docker on Mac M2 - use crossbuild for amd64 arch:
```
docker buildx build --platform linux/amd64 .
```
