### ISSUE TITLE
 ai.djl 0.10.0 & pytorch-native-auto 1.8.1 may conflict

### ISSUE THREAD

**Issue by codeMan2018** [deepjavalibrary/djl#887]
When I ran this case (https://docs.djl.ai/jupyter/load_pytorch_model.html), the following problems occurred：
`If you have recently updated the caffe2.proto file to add a new device type, did you forget to update the DeviceTypeName() function to reflect such recent changes?`

If I change ‘pytorch-native-auto’ version to 1.7.1, its all right, So is there a conflict between  ai.djl 0.10.0 and pytorch-native-auto 1.8.1

Error env：
%maven ai.djl:api:0.10.0
%maven ai.djl.pytorch:pytorch-engine:0.10.0
%maven org.slf4j:slf4j-api:1.7.26
%maven org.slf4j:slf4j-simple:1.7.26
%maven net.java.dev.jna:jna:5.8.0
%maven ai.djl.pytorch:pytorch-native-auto:1.8.1

Error location：
![image](https://user-images.githubusercontent.com/38805586/115649956-e89e3a80-a35a-11eb-9ac1-b70b4fcaee79.png)

**Comment by frankfliu** [comment]
@codeMan2018 Thanks for reporting this issue.

pytorch 1.8.1 can only work with DJL 0.11.0-SNAPSHOT. You have to use pytorch 1.7.1 if you are using DJL 0.10.0.

Will update the document to make it clear.

**Comment by codeMan2018** [comment]
> @codeMan2018 Thanks for reporting this issue.
> 
> pytorch 1.8.1 can only work with DJL 0.11.0-SNAPSHOT. You have to use pytorch 1.7.1 if you are using DJL 0.10.0.
> 
> Will update the document to make it clear.

**Comment by frankfliu** [comment]
@codeMan2018 I updated pytorch document: https://github.com/deepjavalibrary/djl/pull/898

Feel free to reopen this issue if you have further questions.
