### ISSUE TITLE
SSD Custom DataSet Error ??

### ISSUE THREAD

**Issue by nikkisingh111333** [deepjavalibrary/djl#918]
Hey ...i m making HandGesuture Detection ....heres my data Pipeline...Correct Me If im doing anything wrong...

**Builder builder = ImageFolder.builder();
    builder.setRepositoryPath(Paths.get("//content//drive//MyDrive//Colab Notebooks//train_gesture//"));
    builder.optPipeline(
        new Pipeline()
            .add(new Resize(416,416))
            .add(new ToTensor()));
    builder.setSampling(4, true);
  ImageFolder build = builder.build();
build.prepare(new ProgressBar());
List<String> synset = build.getSynset();
Builder builder_validate = ImageFolder.builder();
    builder_validate.setRepositoryPath(Paths.get("//content//drive//MyDrive//Colab Notebooks//Validated//"));
    builder_validate.optPipeline(
        new Pipeline()
            .add(new Resize(416,416))
            .add(new ToTensor()));
    builder_validate.setSampling(4, true);
  
  ImageFolder build_valid = builder_validate.build();
build_valid.prepare(new ProgressBar());
synset**

...After that everything is same as Pickachu Detector...

And i m getting this Error on training phase ....

`ai.djl.engine.EngineException: MXNet engine call failed: MXNetError: Check failed: lshape.ndim() == 3 (1 vs. 3) : Label should be    [batch, num_labels, label_width] tensor
Stack trace:
  File "src/operator/contrib/./multibox_target-inl.h", line 224
  at ai.djl.mxnet.jna.JnaUtils.checkCall(JnaUtils.java:1909)
at ai.djl.mxnet.jna.JnaUtils.imperativeInvoke(JnaUtils.java:519)
	at ai.djl.mxnet.jna.FunctionInfo.invoke(FunctionInfo.java:72)
	at ai.djl.mxnet.engine.MxNDManager.invoke(MxNDManager.java:289)
	at ai.djl.mxnet.engine.MxNDArrayEx.multiBoxTarget(MxNDArrayEx.java:1071)
	at ai.djl.modality.cv.MultiBoxTarget.target(MultiBoxTarget.java:74)
	at ai.djl.training.loss.SingleShotDetectionLoss.inputForComponent(SingleShotDetectionLoss.java:53)
	at ai.djl.training.loss.AbstractCompositeLoss.evaluate(AbstractCompositeLoss.java:66)
	at ai.djl.training.EasyTrain.trainBatch(EasyTrain.java:94)
	at ai.djl.training.EasyTrain.fit(EasyTrain.java:53)
	at .(#310:1)`

Heres my training code......

** Model model = Model.newInstance("GestureDetector");
            float detectionThreshold = 0.6f;
            // load parameters back to original training block
            model.setBlock(ssd);
            // append prediction logic at end of training block with parameter loaded
            Block ssdTrain = model.getBlock();
           model.setBlock(ssdPredict);
            model.setBlock(ssdTrain);
       var epoch=10;
    var train_config= new DefaultTrainingConfig(new SingleShotDetectionLoss())
                .addEvaluator(new SingleShotDetectionAccuracy("classAccuracy"))
                .addEvaluator(new BoundingBoxError("boundingBoxError"))
                .optDevices(new Device[]{Device.gpu(0)})
                .addTrainingListeners(TrainingListener.Defaults.logging());
                Trainer trainer = model.newTrainer(train_config);
 SingleShotDetectionTranslator translator =
                    SingleShotDetectionTranslator.builder()
                            .addTransform(new ToTensor())
                            .optSynset(synset)
                            .optThreshold(detectionThreshold)
                            .build();
                            trainer.setMetrics(new Metrics());
                            System.out.println("whaaat");
               trainer.initialize(new Shape(4, 3, 416, 416));       
                              System.out.println("loo");
                               EasyTrain.fit(trainer,10,build,build_valid);
                           trainer.notifyListeners(listener -> listener.onEpoch(trainer));
                    **

what i m missing ....???? suggest me

**Comment by zachgk** [comment]
I think your problem is that you are using the ImageFolderDataset which is a dataset for image classification (see CV applications at https://javadoc.io/doc/ai.djl/api/latest/ai/djl/Application.CV.html). But, your model is a model for object detection. Both your model and dataset need to be for the same application.

**Comment by nikkisingh111333** [comment]
how can i create ObjectDetectionDataset....i cant find any clue....please share some info ?

**Comment by frankfliu** [comment]
I think you have to create your own dataset.
1. You need a metadata file for your label, similar to index.file for [PikachuDetection](https://github.com/deepjavalibrary/djl/blob/master/basicdataset/src/main/java/ai/djl/basicdataset/cv/PikachuDetection.java#L98)
2. You can leverage some of ImageFolder code to scan the files
3. You need a way to link the and label by it's filename.

**Comment by nikkisingh111333** [comment]
Can you please me refer to some code for dataset.creation....I m unable to
find any help from docs..

**Comment by nikkisingh111333** [comment]
thanks but this is for csv dataset...i already work with that ...i want to create object detector databaase...i have two folders of 1000 images each..two folders represent two classes...how can i make it one...can you send some code pieaces if available..please..?

**Comment by frankfliu** [comment]
Here is the code in PikachuDetection the extract the boundbox label from Json file:
https://github.com/deepjavalibrary/djl/blob/master/basicdataset/src/main/java/ai/djl/basicdataset/cv/PikachuDetection.java#L97-L111

And CocoDetection is using a more complicated label data structure:
https://github.com/deepjavalibrary/djl/blob/master/basicdataset/src/main/java/ai/djl/basicdataset/cv/CocoDetection.java#L117-L134

**Comment by nikkisingh111333** [comment]
thanks i m gonna check it out then i'll report you ...

**Comment by frankfliu** [comment]
Closing this old issue. Feel free to raise a new issue if you still have questions.
