### ISSUE TITLE
Add support for Float16 to PyTorch Engine.

### ISSUE THREAD

**Issue by hodovo** [deepjavalibrary/djl#922]
## Description

Add Float16 support to pytorch engine.

Will this change the current api? How?

This will allow the user to run more performant inference using fp16 models rather than fp32. Java does not have 2 byte float support natively, however, we can use a short (2 bytes) to store the bytes of the fp16 and then parse it with some bitwise operations.

Who will benefit from this enhancement?

Users who are running inference at scale and need to maximize their GPU compute available.

Using YOLOv5s, switching the inference process to fp16 in DJL with some adjustments, I am able to increase the throughput by over 400 images per second (~1250/s -> ~1680/s) on a single RTX 3090.

## Recommendations

Add improved integration for DataType to be used throughout the inference process. Right now, the PtModel assumes a dataType of fp32 which does not allow for much flexibility. We can add support directly for fp16, or create a few abstractions to allow for the parsing of the raw data to be customized by the user. For instance, YoloV5Translator.processFromBoxOutput calls toFloatArray(). If we allow the user to specify a dataType for this translator or we create a separate method for the flattening of the NDList, we can introduce more flexibility in the performance of the inference process.

Here is my example of parsing a float16 from a short (A big thanks to https://github.com/cheminfo-js/float16 for the translating of a 16 bit integer to a float):

```java
    /**
     * Parse a float16 (2 bytes) value from a short (2 bytes) into a float (4 bytes)
     *
     * @param value the value of a float16 represented as a short.
     * @return the float (4 bytes) parsed from the float16 represented as a short.
     */
    public static float parseFloat16(short value) {
        boolean negative = ((value >> 15) & 1) != 0;
        byte mask = 0b11111;
        short exponent = (short) ((value >> 10) & mask);
        short significand = (short) (value & 0b1111111111);
        if (exponent == 0 && significand == 0) {
            return negative ? -0 : 0;
        }
        if (exponent == mask && significand == 0) {
            return negative ? -Short.MAX_VALUE : Short.MAX_VALUE;
        }
        float f;
        if (exponent == 0) {
            f = (float) (significand / 512.0);
        } else {
            f = (float) (1.0 + significand / 1024.0);
        }
        return (float) ((negative ? -1.0 : 1.0) * Math.pow(2, exponent - 15) * f);
    }
```

For an example, we can add the method NDArray.toFloat16Array() as follows:

```java
    /**
     * Converts this {@code NDArray} to a float array.
     *
     * @return a float array
     * @throws IllegalStateException when {@link DataType} of this {@code NDArray} mismatches
     */
    default float[] toFloat16Array() {
        if (getDataType() != DataType.FLOAT16) {
            throw new IllegalStateException(
                    "DataType mismatch, Required float16, Actual " + getDataType());
        }
        int index = 0;
        ShortBuffer buffer = toByteBuffer().asShortBuffer();
        float[] ret = new float[buffer.remaining()];
        while (buffer.hasRemaining()) {
            short value = buffer.get();
            ret[index++] = NDUtils.parseFloat16(value);
        }
        return ret;
    }
```

This is rough code and requires more testing and debugging. Please let me know your thoughts on this enhancement. Thank you :)

**Comment by frankfliu** [comment]
@hodovo This is great initiative.
Java doesn't natively support float16/uint8, this makes API a bit complicated.
You changes definitely improved user experience when using float16. Please go ahead and submit a PR.

On the other hand, we also need to consider what the best way for java user to create a float16 NDArray from java data type.
It's not clear to me what's the preferred way to create float16 NDArrays. Currently user can already create a uint8/float32 NDArray and then convert to float16. Is this sufficient for user? Is there a need that user want to create a float16 NDArray directly from float[]? We don't have to implement this, but something to consider.

**Comment by hodovo** [comment]
I just made a pull request #924. The goal of the design was to avoid making major changes across the code base to improve support of dataType. I look forward to any and all feedback :)
