### ISSUE TITLE
Not A Bug ..BoundingBox creation?

### ISSUE THREAD

**Issue by nikkisingh111333** [deepjavalibrary/djl#928]
Hey i m using retinaFaceDetector and i m getting bounding box array like this:
`[x=0.338, y=0.286, width=0.364, height=0.466]`
i m searching for drawBoundingBox implementation so that i can get some info regarding how to make bounding boxes..but all i m seeing is just interface of name Image but no class that implemented it in docs..how can i navigate to Image interface implemented class..for bounding boxes.....help me please  ...or just give me idea of i can make bounding box on my image using following cooordinates...

**Comment by zachgk** [comment]
If you are looking to ask questions, you can put them in the [Q&A section of the discussion forum](https://github.com/deepjavalibrary/djl/discussions/categories/q-a) instead of titling your issue "Not a bug".

You can create an `Image` object by using:

```
ImageFactory imageFactory = ImageFactory.getInstance();
Image image = imageFactory.fromNDArray(...);
// or .fromFile, .fromUrl, .fromInputStream, .fromImage(bufferedImage)
image.drawBoundingBoxes(detections);
```

**Comment by nikkisingh111333** [comment]
Okk I will take care of it next time....Actually that's not my problem ..I have already created bounding box on image..But I want to extract x y w h coordinated and use them with opencv..I m creating facial key point detection and adding some features using key points for that I first need to extract facial part ..Which I m guessing I can do it with opencv for that I need coordinated .. I m using this code `detection.item(0).getBounds()` I m getting rectangle object of coordinates `[x=0.338, y=0.286, width=0.364, height=0.466]`..How can I turn these coordinator with respect to my image size and create bounding box..Eg my image is of 600x600 face on center.please suggest me..

**Comment by zachgk** [comment]
They are a a percentage of the image size. Just multiply x and width by imageWidth (600). Multiply y and height by imageHeight (600).

**Comment by nikkisingh111333** [comment]
okk i get it ....i watched deeplearning4j tinyyolo example recently 5 min ago..thanks for your confirmation .....
