### ISSUE TITLE
[Homebrew] Checking into uploaded djl-serving v0.11.0 SHA difference

### ISSUE THREAD

**Issue by cho-m** [deepjavalibrary/djl#941]
At Homebrew, we are seeing a SHA mismatch described here: Homebrew/homebrew-core#76668
This is for the file: https://djl-ai.s3.amazonaws.com/publish/djl-serving/serving-0.11.0.tar

Due to security reasons, we would like to confirm the reason for retagging / SHA difference.

I see that the `djl-serving` formula was added back in March to download v0.11.0, while this GitHub repo shows that v0.11.0 released in May.

For reference, the Homebrew formula for `djl-serving` is available at:
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/djl-serving.rb
It was added with v0.11.0 in PR Homebrew/homebrew-core#73649

**Comment by aksrajvanshi** [comment]
@frankfliu did we make any changes to the djl-serving tar file recently ?

**Comment by frankfliu** [comment]
Yes this is a bug:
1. When we publish djl-serving brew package, it was based on 0.11.0-SNAPSHOT on March 23
2. On May, we updated djl-serving binary to 0.11.0 release version, but we didn't update brew package

What we can do is release a version 0.11.0-post1 in brew to address this issue.

**Comment by cho-m** [comment]
@frankfliu 
On Homebrew side, it is possible to just update SHA in linked PR once we have confirmation that this was an intended modification.

For future updates, it would be best to make sure the filename changes once published, otherwise the Formula will break.
This is especially the case for unbottled formulas like this.

**Comment by aksrajvanshi** [comment]
A new revision has been created on homebrew's side. Closing this issue.
