### ISSUE TITLE
Segmentation Model Downloading Time error?

### ISSUE THREAD

**Issue by nikkisingh111333** [deepjavalibrary/djl#945]
hey ...i m using instance segmentation heres my code :
`Criteria<Image, DetectedObjects> criteria =
                Criteria.builder()
                        .optApplication(Application.CV.INSTANCE_SEGMENTATION)
                        .setTypes(Image.class, DetectedObjects.class)
                        .optFilter("backbone", "resnet18")
                        .optFilter("flavor", "v1b")
                        .optFilter("dataset", "coco")
                        .optProgress(new ProgressBar())
                        .build();
ZooModel<Image, DetectedObjects> model = ModelZoo.loadModel(criteria);
Predictor<Image, DetectedObjects> predictor = model.newPredictor();
 Image img = ImageFactory.getInstance().fromUrl("https://cars.usnews.com/pics/size/640x420/static/images/article/202002/128389/1_title_2020_kia_optima.jpg");
 Image newImage = img.duplicate(Image.Type.TYPE_INT_ARGB);
        newImage.drawBoundingBoxes(detection);
        newImage.getWrappedImage();`

while running this model starts downloading BUT its taking too much time and also consumed my internet data..
**Downloading: 100% |████████████████████████████████████████|
Loading:     100% |████████████████████████████████████████|
[IJava-executor-1] INFO ai.djl.mxnet.jna.LibUtils - Downloading libgfortran.so.3 ...
[IJava-executor-1] INFO ai.djl.mxnet.jna.LibUtils - Downloading libgomp.so.1 ...
[IJava-executor-1] INFO ai.djl.mxnet.jna.LibUtils - Downloading libquadmath.so.0 ...
[IJava-executor-1] INFO ai.djl.mxnet.jna.LibUtils - Downloading libmxnet.so ...**

its about 2 hours now..and still its executing ....when i check libmxnet.so on browser..its giving me unknown error..
WHY ITS TAKING SO MUCH TIME..IT DIDNT HAPPEND BEFORE..ON ANY OTHER MODEL I HAVE USED..
please do Suggest Me ?

**Comment by frankfliu** [comment]
Feel free to reopen this issue if you have further questions.
