### ISSUE TITLE
What is this Index.file.?

### ISSUE THREAD

**Issue by nikkisingh111333** [deepjavalibrary/djl#947]
hello...i want to create our own ObjectDetection Dataset following PikchuDetection Example 👍 
i want to know whats this index.file and how can i create one...i cant find any thing related this..docs are confusing ..found an issue related to this which suggesting use AmazonSagemaker but Its Too Complicated...please guide me how can i create Index.file..Label file for ObjDetection....?

**Comment by nikkisingh111333** [comment]
here's what i m doing 👍 :Similar to PickachuDtection
`public class GestureDataset extends ObjectDetectionDataset {
    
private static final String VERSION = "1.0";
    private static final String ARTIFACT_ID = "gesture";
    private Usage usage;
    private List<Path> imagePaths;
    private PairList<Long, Rectangle> labels;

    private Resource resource;
    private boolean prepared;

    protected GestureDataset(Builder builder) {
        super(builder);
        usage = builder.usage;
        imagePaths = new ArrayList<>();
        labels = new PairList<>();
        MRL mrl = MRL.dataset(CV.ANY, builder.groupId, builder.artifactId);
        resource = new Resource(builder.repository, mrl, VERSION);
    }

    /**
     * Creates a new builder to build a {@link PikachuDetection}.
     *
     * @return a new builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /** {@inheritDoc} */
    @Override
    public void prepare(Progress progress) throws IOException {
        if (prepared) {
            return;
        }

        Artifact artifact = resource.getDefaultArtifact();
        resource.prepare(artifact, progress);

        Path root = resource.getRepository().getResourceDirectory(artifact);
        Path usagePath;
        switch (usage) {
            case TRAIN:
                usagePath = Paths.get("//content//drive//MyDrive//Colab Notebooks//train_gesture//");
                break;
            case TEST:
                usagePath = Paths.get("//content//drive//MyDrive//Colab Notebooks//Validated//");
                break;
            case VALIDATION:
            default:
                throw new UnsupportedOperationException("Validation data not available.");
        }
        usagePath = root.resolve(usagePath);
        Path indexFile = usagePath.resolve("index.file");
        try (Reader reader = Files.newBufferedReader(indexFile)) {
            Type mapType = new TypeToken<Map<String, List<Float>>>() {}.getType();
            Map<String, List<Float>> metadata = JsonUtils.GSON.fromJson(reader, mapType);
            for (Map.Entry<String, List<Float>> entry : metadata.entrySet()) {
                String imgName = entry.getKey();
                imagePaths.add(usagePath.resolve(imgName));

                List<Float> label = entry.getValue();
                long objectClass = label.get(4).longValue();
                Rectangle objectLocation =
                        new Rectangle(
                                new Point(label.get(5), label.get(6)), label.get(7), label.get(8));
                labels.add(objectClass, objectLocation);
            }
        }
        prepared = true;
    }

    @Override
    public PairList<Long, Rectangle> getObjects(long index) {
        return new PairList<>(Collections.singletonList(labels.get((int) index)));
    }

    /** {@inheritDoc} */
    @Override
    protected long availableSize() {
        return imagePaths.size();
    }

    @Override
    protected Image getImage(long index) throws IOException {
        int idx = Math.toIntExact(index);
        return ImageFactory.getInstance().fromFile(imagePaths.get(idx));
    }

    @Override
    public Optional<Integer> getImageWidth() {
        return Optional.empty();
    }

    @Override
    public Optional<Integer> getImageHeight() {
        return Optional.empty();
    }

    /** A builder for a {@link PikachuDetection}. */
    public static final class Builder extends ImageDataset.BaseBuilder<Builder> {

        Repository repository;
        String groupId;
        String artifactId;
        Usage usage;

        /** Constructs a new builder. */
        Builder() {
            repository = BasicDatasets.REPOSITORY;
            groupId = BasicDatasets.GROUP_ID;
            artifactId = ARTIFACT_ID;
            usage = Usage.TRAIN;
        }

        /** {@inheritDoc} */
        @Override
        public Builder self() {
            return this;
        }

        /**
         * Sets the optional usage.
         *
         * @param usage the usage
         * @return this builder
         */
        public Builder optUsage(Usage usage) {
            this.usage = usage;
            return self();
        }

        /**
         * Sets the optional repository.
         *
         * @param repository the repository
         * @return this builder
         */
        public Builder optRepository(Repository repository) {
            this.repository = repository;
            return self();
        }

        /**
         * Sets optional groupId.
         *
         * @param groupId the groupId}
         * @return this builder
         */
        public Builder optGroupId(String groupId) {
            this.groupId = groupId;
            return this;
        }

        /**
         * Sets the optional artifactId.
         *
         * @param artifactId the artifactId
         * @return this builder
         */
        public Builder optArtifactId(String artifactId) {
            if (artifactId.contains(":")) {
                String[] tokens = artifactId.split(":");
                groupId = tokens[0];
                this.artifactId = tokens[1];
            } else {
                this.artifactId = artifactId;
            }
            return this;
        }

        public GestureDataset build() {
            if (pipeline == null) {
                pipeline = new Pipeline(new ToTensor());
            }
            return new GestureDataset(this);
        }
    }
}`
the problem is index.file...should i just call GestureDataset.build() and index would automatically generated or should i need to create index.file which i offcourse dont know how..?? guide me please ...i want to make my hand gesture detector..then after that i ll do create landmarks on them....

**Comment by zachgk** [comment]
You need to create the `index.file` yourself. Look at the code you wrote in `GestureDataset.prepare`. It is reading the data from the `index.file` and storing it in the instance variables.

Here is a question. Where is the data for your gesture dataset coming from? Is it on a site somewhere?

You have two options:
1.  Use that data to build an `index.file`
2. modify the `GestureDataset.prepare` to read that data directly instead of reading `index.file`

**Comment by nikkisingh111333** [comment]
okk heres the link of dataset i m using ....check it out and tell me if i m using right stuff for detection task ..i doubt i m not...?
let me hear from you....?
 GESTURE DATASET LINK:
[https://www.kaggle.com/ahmedkhanak1995/sign-language-gesture-images-dataset](url)

**Comment by zachgk** [comment]
I looked at it. You are not using the right data for object detection. The dataset only includes a class label for each image, so it can be used for [image classification](https://javadoc.io/static/ai.djl/api/0.11.0/ai/djl/Application.CV.html#IMAGE_CLASSIFICATION).

If you want to do object detection, you must either label it yourself or find a different dataset
