### ISSUE TITLE
CPU running faster than GPU

### ISSUE THREAD

**Issue by markbookk** [deepjavalibrary/djl#952]
## Description
I was running [this code](https://github.com/markbookk/java-d2l-IDE/tree/main/section14_4) on CPU and GPU and CPU seemed to run faster for some odd reason. I also made sure the code was the same.

CPU environment:
MacBook Pro
2.6 GHz 6-Core Intel Core i7
16 GB 2667 MHz DDR4
OS: MacOS

GPU environment:
AWS p3.2xlarge
OS: Windows

### Expected Behavior
GPU p3 instance should run way faster than CPU.

## How to Reproduce?
Clone [repo](https://github.com/markbookk/java-d2l-IDE/tree/main/section14_4) and make sure to be using auto library for MXNet to detect GPU. If it isn't, change pom.xml accordingly.

**Comment by zachgk** [comment]
I don't find that too surprising. There is a cost to transfer data from memory into the GPU. It is worth it to pay for this cost if you have a ton of highly parallelizable computations. Things like models with big NDArrays and lots of convolutions. If you have something which is not very easily parallelized or requires very little work per data item, it may be better to save the GPU transfer and just run it on CPU.

**Comment by markbookk** [comment]
Is the difference highly noticeable? I ask because in my code, I do see a huge difference on CPU over GPU in this case. I also found weird that this happens in Java but not on Python (code is not exactly 100% the same so maybe I am not leveraging highly parallelizable computations as in Python side).

**Comment by hongyaohongyao** [comment]
I meet the same problem when use the onnxruntime engine

**Comment by frankfliu** [comment]
> I meet the same problem when use the onnxruntime engine

@hongyaohongyao 
Please make sure you are using GPU for ONNXRuntime. 
1. We recently fixed a bug on ONNXRuntime for GPU: https://github.com/deepjavalibrary/djl/pull/979, you have to use snapshot release to run on GPU
2. You need make sure use GPU dependency: https://github.com/deepjavalibrary/djl/tree/master/onnxruntime/onnxruntime-engine#install-gpu-package

**Comment by hongyaohongyao** [comment]
> > I meet the same problem when use the onnxruntime engine
> 
> @hongyaohongyao
> Please make sure you are using GPU for ONNXRuntime.
> 
> 1. We recently fixed a bug on ONNXRuntime for GPU: #979, you have to use snapshot release to run on GPU
> 2. You need make sure use GPU dependency: https://github.com/deepjavalibrary/djl/tree/master/onnxruntime/onnxruntime-engine#install-gpu-package

how to config snapshot release in maven?

**Comment by frankfliu** [comment]
@hongyaohongyao 
https://github.com/deepjavalibrary/djl/blob/master/examples/pom.xml#L17-L22

**Comment by hongyaohongyao** [comment]
> @hongyaohongyao
> https://github.com/deepjavalibrary/djl/blob/master/examples/pom.xml#L17-L22

Thanks for reply. but it doesn't work out. the gpu mode is still slower. I had checked the task manager and I‘m sure that my gpu was running. By the way, the terminate show that
```
2021-06-08 00:43:05.2981161 [W:onnxruntime:ort-java, cuda_execution_provider.cc:1983 onnxruntime::CUDAExecutionProvider::GetCapability] CUDA kernel not found in registries for Op type: DepthToSpace node name: DepthToSpace_151
2021-06-08 00:43:05.2981717 [W:onnxruntime:ort-java, cuda_execution_provider.cc:1983 onnxruntime::CUDAExecutionProvider::GetCapability] CUDA kernel not found in registries for Op type: DepthToSpace node name: DepthToSpace_154
2021-06-08 00:43:05.2981952 [W:onnxruntime:ort-java, cuda_execution_provider.cc:1983 onnxruntime::CUDAExecutionProvider::GetCapability] CUDA kernel not found in registries for Op type: DepthToSpace node name: DepthToSpace_157
```
or it isn't the problem of your frame

**Comment by frankfliu** [comment]
@hongyaohongyao 
This looks like onnxruntime issue. Not all operators are supported by OnnxRuntime, especially for CUDA. Can you try to use ort directly?

**Comment by hongyaohongyao** [comment]
> @hongyaohongyao
> This looks like onnxruntime issue. Not all operators are supported by OnnxRuntime, especially for CUDA. Can you try to use ort directly?

Thanks, I will try it near the future. And another question, I found that the program re-download the onnx library to path `userfile/AppData/local/Temp` with a new fold name every time unlike other engine that download their library to the fixed path. How can I solve it?

**Comment by frankfliu** [comment]
@hongyaohongyao The behavior is done by Microsoft ort. I would be too hacky to change this behavior from DJL side. You can try to file an issue on onnxruntime project. If they they can provide a way to customize it, we can make it default on DJL side.

**Comment by frankfliu** [comment]
Feel free to re-open it if you still have questions.
