### ISSUE TITLE
Infrence shape error ?

### ISSUE THREAD

**Issue by nikkisingh111333** [deepjavalibrary/djl#967]
hey i have trained vgg16 as decribed in your tutorial..on FashionMinst ..the shape of the images in the dataset is (1,96,96) ..after training i was trying to predict an image to test the model :

**List l=Arrays.asList("0","1","2","3","4","5","6","7","8","9");
 ImageClassificationTranslator translator =
                ImageClassificationTranslator.builder()
                        .setPipeline(new Pipeline().add(new Resize(96)))
                        .addTransform(new ToTensor())
                        .optSynset(l)
                        .build();
Image img = ImageFactory.getInstance().fromUrl("https://cdn.shopify.com/s/files/1/0008/6550/1302/products/ON_21_SHOE_RCX_BLACK_BACK_WEB_200x.png?v=1609802141");
var predictor = model.newPredictor(translator);
 var classs = predictor.predict(img);
classs**

and i was getting this error which i know why ...?
`ai.djl.translate.TranslateException: ai.djl.engine.EngineException: MXNet engine call failed: MXNetError: Shape inconsistent, Provided = [16,1,3,3], inferred shape=(16,3,3,3)`
since i m passing 3 channel image on model which is trained on 1 channel dataset..how can i convert `img` from 3 channel to 1 channel please suggest me..?

**Comment by frankfliu** [comment]
You need specify load image as grayscale:
```
ImageClassificationTranslator translator = ImageClassificationTranslator.builder()
        .optFlag(Image.Flag.GRAYSCALE)

```
