### ISSUE TITLE
PtModel load cause file descriptor leak

### ISSUE THREAD

**Issue by wangtieqiao** [deepjavalibrary/djl#976]
## Description

Model.load(Path) --> cause file descriptor leak

PtModel.load(InputStream) --> if user close the inputStream correctly, it will not cause fd leak

### To Reproduce it -- Kotlin code
        import ai.djl.Model
        import ai.djl.pytorch.engine.PtModel
        import com.sun.management.UnixOperatingSystemMXBean
        import java.io.File
        import java.lang.management.ManagementFactory
        import java.nio.file.Files
        import java.nio.file.Path
        import java.nio.file.Paths
        
        /**
         * Try to see if it is possible a memory leak that caused by loading pt models
         */
        
        
        fun printOpenFiles() {
            val os = ManagementFactory.getOperatingSystemMXBean()
            if (os is UnixOperatingSystemMXBean) {
                println("Number of open fd: " + os.openFileDescriptorCount)
            }
        }
        
        fun main() {
        
            val n = 100
            // any pytorch scripts model you have
            val modelOrigionalFile = Paths.get("path_to_your_model.pt").toFile()
            printOpenFiles()
            (0 until n).forEach {
                // create a model dir
                val tmpDir = Files.createTempDirectory("djl_ptmodel_loading_isssue")
                val tmpModelFile = Paths.get(tmpDir.toString(), "model.pt").toFile()
                // copy model file into tmp dir
                modelOrigionalFile.copyTo(tmpModelFile)
        
                loadWillCauseFileDescriptorLeak(tmpDir)
            }
            println("After $n load run, cause file descriptor leak")
            printOpenFiles()
        
            (0 until n).forEach {
                // create a model dir
                val tmpDir = Files.createTempDirectory("djl_ptmodel_loading_isssue")
                val tmpModelFile = Paths.get(tmpDir.toString(), "model.pt").toFile()
                // copy model file into tmp dir
                modelOrigionalFile.copyTo(tmpModelFile)
        
                loadWill_NOT_CauseFileDescriptorLeak(tmpModelFile)
            }
            println("After Anotoher $n load run, DID NOT cause file descriptor leak")
            printOpenFiles()
        
        
        }
        
        private fun loadWillCauseFileDescriptorLeak(tmpDir: Path?) {
            Model.newInstance("model", "PyTorch").also { it.load(tmpDir) }.close()
        }
        
        private fun loadWill_NOT_CauseFileDescriptorLeak(modelFile: File) {
            modelFile.inputStream().use { inStream ->
                val m = Model.newInstance("model", "PyTorch") as PtModel
                m.load(inStream)
                m.close()
            }
        }

#### Sample output
      Number of open fd: 246
      [main] WARN ai.djl.pytorch.jni.LibUtils - No matching cuda flavor for linux found: cu113.
      [main] INFO ai.djl.pytorch.engine.PtEngine - Number of inter-op threads is 12
      [main] INFO ai.djl.pytorch.engine.PtEngine - Number of intra-op threads is 24
      After 100 load run, cause file descriptor leak
      Number of open fd: 456
      After Anotoher 100 load run, DID NOT cause file descriptor leak
      Number of open fd: 456

**Comment by frankfliu** [comment]
@wangtieqiao 
I tried to reproduce your test case and see similar result. However the increasing of the file handle isn't really a leak.
When load the model for the first time, DJL has to load multiple shared library and files from the system. After the first model loading, the file handle will not increase any more.

If you switch the order loadWill_NOT_CauseFileDescriptorLeak() and loadWillCauseFileDescriptorLeak() you will see loadWill_NOT_CauseFileDescriptorLeak() won't cause file handle increase.

Feel free to re-open the issue if you still have questions.

**Comment by wangtieqiao** [comment]
**loadWillCauseFileDescriptorLeak() call cause leak** --> issue with this way to load model, (this should be the way for user to call IMO, as user do not need explicitly access PtModel class)

loadWill_NOT_CauseFileDescriptorLeak() will not --> no issue with this way to load model

not sure what you mean switch order, but I think possibly the output not clear enough ...

**Comment by frankfliu** [comment]
If you only run loadWill_NOT_CauseFileDescriptorLeak() in your code, you will also see file handle increase.

The file handle increase is not a handle leak. The increase is expected behavior. The number of file handle increase is not released to model.load(). You can increase the loop count and you will see the increase if fixed number.

**Comment by wangtieqiao** [comment]
loadWill_NOT_CauseFileDescriptorLeak() will print out 10 fd increase no matter how many loops run

**loadWillCauseFileDescriptorLeak() will print out 10 + 2*n fd increased**

      n=100 -> result show 210 fd increase
      n=200 -> result show 410 fd increase
      n=300 -> result show 610 fd increase
      ...

**Comment by frankfliu** [comment]
@wangtieqiao 
I don't see this happening, I tested on both Mac and Linux
See my test case: https://github.com/frankfliu/djl/blob/leak/pytorch/pytorch-engine/src/test/java/ai/djl/pytorch/integration/FileHandleLeakTest.java

```
git clone https://github.com/frankfliu/djl.git -b leak
cd djl/pytorch/pytorch-engine
./gradlew test --tests FileHandleLeakTest

    Before load model:
    Number of open fd: 67

Gradle suite > Gradle test > ai.djl.pytorch.integration.FileHandleLeakTest > testLoadModel STANDARD_ERROR
    [Test worker] INFO ai.djl.pytorch.engine.PtEngine - Number of inter-op threads is 4
    [Test worker] INFO ai.djl.pytorch.engine.PtEngine - Number of intra-op threads is 8

Gradle suite > Gradle test > ai.djl.pytorch.integration.FileHandleLeakTest > testLoadModel STANDARD_OUT
    After first model loading:
    Number of open fd: 77
    Load model with InputStream ...
    Number of open fd: 76
    Load model with Path ...
    Number of open fd: 76
```
```

**Comment by wangtieqiao** [comment]
Thanks, I checked out your code and run your test locally, see same result as yours, no issue.

For my original test, still have same issue, maybe because either different version, or, maybe a Kotlin issue? Anyway, I am good as I can use the version load from input stream with my current working environment
      
          implementation("ai.djl:api:0.11.0")
          implementation("ai.djl.mxnet:mxnet-engine:0.11.0")
          implementation("ai.djl.mxnet:mxnet-model-zoo:0.11.0")
      //    implementation("ai.djl.mxnet:mxnet-native-auto:1.7.0-backport")
          implementation("ai.djl.mxnet:mxnet-native-auto:1.8.0")
      //    implementation("ai.djl.tensorflow:tensorflow-native-auto:2.4.1")
          implementation("ai.djl.pytorch:pytorch-engine:0.11.0")
          implementation("ai.djl.pytorch:pytorch-native-auto:1.8.1")
