### ISSUE TITLE
Training Accuracy Is Stuck on 50%??

### ISSUE THREAD

**Issue by nikkisingh111333** [deepjavalibrary/djl#985]
heyy i m using vgg16 ....heres the dataset i m using its small just limited images ..heres the link of dataset check it out ..
[HandGesture](https://lttm.dei.unipd.it/downloads/gesture/)
I have Two problems:
1.i m only getting accuracy of 50% to 52% and 49% to 51% on training and validating set respectively  SofmaxCrossEntropy error is just stuck on 69% neither increasing nor decreasing..
heres my code :

**Model model = Model.newInstance("vgg-tiny");
SequentialBlock newBlock = VGG(convArch);
model.setBlock(newBlock);
Loss loss = Loss.sigmoidBinaryCrossEntropyLoss("losser",0.5f,true);
float lr=0.01f;
Tracker lrt = Tracker.fixed(lr);
Optimizer sgd = Optimizer.sgd().setLearningRateTracker(lrt).build();
Shape inputShape=new Shape(1,3,96,96);
DefaultTrainingConfig config = new DefaultTrainingConfig(loss).optOptimizer(sgd) // Optimizer (loss function)
                .optDevices(Device.getDevices(1)) // single GPU
                .addEvaluator(new Accuracy())
                .optInitializer(new XavierInitializer()) // Model Accuracy
                .addTrainingListeners(TrainingListener.Defaults.logging()); // Logging
                Trainer trainer = model.newTrainer(config);
NDManager manager = NDManager.newBaseManager() ;
    NDArray X = manager.randomUniform(0f, 1.0f, inputShape);
    trainer.initialize(inputShape);
    Shape currentShape = X.getShape();
    for (int i = 0; i < newBlock.getChildren().size(); i++) {
  Shape[] newShape = newBlock.getChildren().get(i).getValue().getOutputShapes(manager, new Shape[]{currentShape});
        currentShape = newShape[0];
        System.out.println(newBlock.getChildren().get(i).getKey() + " layer output : " + currentShape);
    }**
what should we do to achieve above 80% should i try to hunt for more data or what..i have also tried to reduce dense layer nodes from 4098 to 2046 but nothing work..
heres my network check it out:

**01SequentialBlock layer output : (1, 32, 48, 48)
02SequentialBlock layer output : (1, 64, 24, 24)
03SequentialBlock layer output : (1, 128, 12, 12)
04SequentialBlock layer output : (1, 256, 6, 6)
05SequentialBlock layer output : (1, 512, 3, 3)
06LambdaBlock layer output : (1, 4608)
07Linear layer output : (1, 2048)
08LambdaBlock layer output : (1, 2048)
09Dropout layer output : (1, 2048)
10Linear layer output : (1, 2048)
11LambdaBlock layer output : (1, 2048)
12Dropout layer output : (1, 2048)
13Linear layer output : (1, 2)**

2.when changing output layer from SoftMax to Sigmoid i m getting this error:

`ai.djl.engine.EngineException: MXNet engine call failed: MXNetError: Check failed: src.Size() == dst->Size() (128 vs. 256) : Cannot reshape array of size 128 into shape [128,2]`

please help me to resolve this..

**Comment by zachgk** [comment]
1. Let's start with what will probably not help. Your training loss and validation loss are about the same which is a good sign. Your model is not overfitting the data. Getting more data is used to prevent overfitting, so that will not help you improve the score. What you need is to get your model to more closely fit the data to get a higher accuracy score.

Usually, this can be done by using a different model, changing hyperparameters, and making your model bigger. I would start by looking at a different model as VGG is not a particularly good one. I recommend Resnet as it is a good standard option which we also have built-in in DJL. You could also try using a standard "vgg" instead of "vgg-tiny" which may help.

2. Why is it that you are changing from softmax to sigmoid? Are you referring to changing the loss, because the SoftmaxCrossEntropy is the right loss for image classification.

**Comment by nikkisingh111333** [comment]
No I m not using vgg tiny I m using full vgg 16 with more filters..32 64 128 256 512 ..My dataset only contains 500 images only..What should I do .And please recommend me some hand gesture dataset below 1 gb ..Every dataset is 5 gb or sometimes 12 gb..

**Comment by zachgk** [comment]
You could also try switching to the Adam optimizer, training for more epochs, adding more layers to the model, etc. 500 does not seem like enough images. If the datasets are too big, just use part of it. But, I recommend trying to use the whole dataset. Deep learning does much better when you have a bigger dataset to work withl

**Comment by nikkisingh111333** [comment]
Thanks for the advice! Yes you are right now I m hunting and finding more
data i think data is not enough will 5000 images work well ..Will my
accuracy improve with 5000 images ..??

**Comment by zachgk** [comment]
Your accuracy will not improve with more data. There are two problems a model can have: overfitting and underfitting. Having accuracy which is not high enough on your **training set** is an underfitting problem. Adding more data helps overfitting, not underfitting. Read https://d2l.djl.ai/chapter_multilayer-perceptrons/underfit-overfit.html?highlight=overfitting

**Comment by nikkisingh111333** [comment]
Thanks for the tip! So I understand my model is under fitted..Since
sofmaxcrossentropy loss is 69 always and accuracy is stuck in between
50-53% on both train and validate set..Which means I need little bit more
data and tuning hyperparams Learning rate Optimizers many others..Since I
don't think I have to mess up with model layers ..If so how many layers
should I put at the end ..Dense layer ..And one more think should I change
output activation function from softmax to sigmoid..? Please clarify me

**Comment by nikkisingh111333** [comment]
hey i have just tried to train model on one-one sample ...one image of class 1 and one image of class 2 ....and on that too i m getting 52% trianing accuracy ... and 69% softmaxEntropy....while i was expecting Overfitting of 100% training accuracy why is that i m using these two images only :
![gesture (63)](https://user-images.githubusercontent.com/49682940/120071122-61f02200-c0ab-11eb-80f6-e950e526fd7c.png)
![two (28)](https://user-images.githubusercontent.com/49682940/120071131-69173000-c0ab-11eb-8700-e30ea8f23351.png)
just two sample of two classes for training and still accuracy is not 100% ...is there any serious problem with the model..what should i change?
`[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Epoch 1 finished.
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Train: Accuracy: 0.50, SoftmaxCrossEntropyLoss: 3.39
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Validate: Accuracy: 0.50, SoftmaxCrossEntropyLoss: 0.69
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Epoch 2 finished.
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Train: Accuracy: 0.50, SoftmaxCrossEntropyLoss: 0.71
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Validate: Accuracy: 0.50, SoftmaxCrossEntropyLoss: 0.69
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Epoch 3 finished.
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Train: Accuracy: 0.50, SoftmaxCrossEntropyLoss: 0.70
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Validate: Accuracy: 0.50, SoftmaxCrossEntropyLoss: 0.69
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Epoch 4 finished.
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Train: Accuracy: 0.00E+00, SoftmaxCrossEntropyLoss: 0.70
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Validate: Accuracy: 0.50, SoftmaxCrossEntropyLoss: 0.69
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Epoch 5 finished.
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Train: Accuracy: 0.00E+00, SoftmaxCrossEntropyLoss: 0.70
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Validate: Accuracy: 0.50, SoftmaxCrossEntropyLoss: 0.69
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Epoch 6 finished.
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Train: Accuracy: 0.50, SoftmaxCrossEntropyLoss: 0.69
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Validate: Accuracy: 0.50, SoftmaxCrossEntropyLoss: 0.69
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Epoch 7 finished.
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Train: Accuracy: 0.50, SoftmaxCrossEntropyLoss: 0.69
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Validate: Accuracy: 0.50, SoftmaxCrossEntropyLoss: 0.69
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Epoch 8 finished.
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Train: Accuracy: 0.50, SoftmaxCrossEntropyLoss: 0.69
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Validate: Accuracy: 0.50, SoftmaxCrossEntropyLoss: 0.69
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Epoch 9 finished.
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Train: Accuracy: 0.50, SoftmaxCrossEntropyLoss: 0.70
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Validate: Accuracy: 0.50, SoftmaxCrossEntropyLoss: 0.69
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Epoch 10 finished.
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Train: Accuracy: 0.50, SoftmaxCrossEntropyLoss: 0.70
[IJava-executor-0] INFO ai.djl.training.listener.LoggingTrainingListener - Validate: Accuracy: 0.50, SoftmaxCrossEntropyLoss: 0.69`
 
heres my model:

**01SequentialBlock layer output : (1, 32, 75, 75)
02SequentialBlock layer output : (1, 64, 37, 37)
03SequentialBlock layer output : (1, 128, 18, 18)
04SequentialBlock layer output : (1, 256, 9, 9)
05SequentialBlock layer output : (1, 512, 4, 4)
06LambdaBlock layer output : (1, 8192)
07Linear layer output : (1, 4086)
08LambdaBlock layer output : (1, 4086)
09Dropout layer output : (1, 4086)
10Linear layer output : (1, 4086)
11LambdaBlock layer output : (1, 4086)
12Dropout layer output : (1, 4086)
13Linear layer output : (1, 2)**

Rest of the code is same i have just changed size of input from 96 to 150 and optimizer Adam with default parameters still not helping..and little bit playing around learning rates and batch sizes...I did not normalize dataset.may be its not that much effective i guess.....Please tell me what should i do....i m Clueless..??

**Comment by zachgk** [comment]
Yeah, this is a problem if it can't classify two images 100%. The batch size should be 2 as there are only two training images. This sounds like there should be some bug that needs to be fixed. What happens if you replace your model with an MLP?

**Comment by nikkisingh111333** [comment]
so this is an bug on my model or its Api related ....I haven't trained it
on Mlp ..Perhaps Its giving perfect result on fashion mnist ..And I just
want to know what's wrong with model I have copied it from doc and giving
data which is not so perfect but good enough to get all 70 percent ...I
have also increase data size from 500 to 1000 ..This is only I have able to
find out on internet available..On low size ...All other dataset are above
5 gb which I m not  going to download ....
