### ISSUE TITLE
in 2.0.0 version, is there libdjl_paddle.so   compiled with  GLIBCXX which isn't higher than 3.4.20?

### ISSUE THREAD

**Issue by haha00gou** [deepjavalibrary/djl#991]
## Description

(A clear and concise description of what the feature is.)

Will this change the current api? How?

Who will benefit from this enhancement?

## References
- list reference and related literature
- list known implementations

**Comment by lanking520** [comment]
Which GLIBC version you are looking for?  We are expecting to support GLIBC version from 2.20

**Comment by haha00gou** [comment]
m

> Which GLIBC version you are looking for? We are expecting to support GLIBC version from 2.20

my gcc is 4.9.2 ,report error that "not found GLIBCXX3.4.21"

**Comment by frankfliu** [comment]
Free free to reopen this issue if you still have issue with latest version.
