### ISSUE TITLE
Image Augmentation missing?

### ISSUE THREAD

**Issue by nikkisingh111333** [deepjavalibrary/djl#995]
hey...I was playing with datasets and find nothing like image augmentation pipeline feature.....Since my models overfit too much ..I need to augment image on imagedataset before training how can I use it...Is there any feature in dil...?? Please suggest me

**Comment by zachgk** [comment]
See https://javadoc.io/static/ai.djl/api/0.11.0/ai/djl/modality/cv/transform/package-summary.html

**Comment by nikkisingh111333** [comment]
Thanks for tha response I'll check it out
